(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const input=$('#image-input'), drop=$('#dropzone'), browse=$('#browse-button'), screens=$$('.screen'), dots=$$('[data-step-dot]');
let files=[],active=0,originalBlob=null,resultBlob=null,resultUrl=null,originalUrl=null,ratio=1,format='image/webp',quality=.82;
const tool={id:'image-compressor',name:'Image Compressor',url:'/tools/image/image-compressor/'};
const bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function screen(n){screens.forEach((x,i)=>{x.hidden=i!==n;x.classList.toggle('active',i===n)});dots.forEach((d,i)=>d.classList.toggle('active',i<=n));window.scrollTo({top:0,behavior:'smooth'})}
function error(message=''){const el=$('#upload-error');if(!el)return;el.textContent=message;el.hidden=!message}
function refreshFiles(){$('#file-count').textContent=files.length;$('#file-list').innerHTML=files.map((f,i)=>`<div class="file-item"><span>${esc(f.name)}</span><small>${bytes(f.size)} · ${i===active?'active':''}</small></div>`).join('');const btn=$('[data-action="to-adjust"]');if(btn)btn.disabled=!files.length}
function load(list){error();const picked=[...list].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));if(!picked.length){error('Please choose a JPG, PNG or WebP image.');return}files=picked;active=0;refreshFiles();prepare();window.Nexauren?.trackTool?.('tool_start',tool,{title:'Images selected',count:files.length})}
function prepare(){const f=files[active];if(!f)return;originalBlob=f;if(originalUrl)URL.revokeObjectURL(originalUrl);originalUrl=URL.createObjectURL(f);const im=new Image();im.onload=()=>{$('#active-name').textContent=f.name;$('#original-meta').textContent=`${im.naturalWidth} × ${im.naturalHeight} · ${bytes(f.size)}`;$('#width').value=im.naturalWidth;$('#height').value=im.naturalHeight;ratio=im.naturalWidth/im.naturalHeight;$('#studio-preview').src=originalUrl;$('#original-preview').src=originalUrl};im.onerror=()=>error('This image could not be read by your browser.');im.src=originalUrl}
browse?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();input?.click()});input?.addEventListener('change',e=>{load(e.target.files);e.target.value='' });
drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');load(e.dataTransfer.files)});
$('#quality')?.addEventListener('input',e=>{quality=+e.target.value/100;$('#quality-value').textContent=e.target.value+'%'});
$$('[data-format]').forEach(b=>b.addEventListener('click',()=>{$$('[data-format]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');format=b.dataset.format}));
$('#width')?.addEventListener('input',e=>{if($('#keep-ratio').checked&&e.target.value)$('#height').value=Math.max(1,Math.round(+e.target.value/ratio))});$('#height')?.addEventListener('input',e=>{if($('#keep-ratio').checked&&e.target.value)$('#width').value=Math.max(1,Math.round(+e.target.value*ratio))});
$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const im=$('#studio-preview');if(!im.naturalWidth)return;const p=+b.dataset.preset;$('#width').value=Math.max(1,Math.round(im.naturalWidth*p));$('#height').value=Math.max(1,Math.round(im.naturalHeight*p))}));
$('[data-action="reset-size"]')?.addEventListener('click',prepare);
function compress(){if(!originalBlob)return;const im=new Image();im.onload=()=>{const w=Math.max(1,+$('#width').value||im.naturalWidth),h=Math.max(1,+$('#height').value||im.naturalHeight),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(format==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h)}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(im,0,0,w,h);c.toBlob(b=>{if(!b){error('The image could not be compressed.');return}resultBlob=b;if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(b);$('#compressed-preview').src=resultUrl;const saved=Math.max(0,originalBlob.size-b.size),pct=originalBlob.size?Math.round(saved/originalBlob.size*100):0;$('#metric-original').textContent=bytes(originalBlob.size);$('#metric-compressed').textContent=bytes(b.size);$('#metric-saved').textContent=bytes(saved);$('#metric-percent').textContent=pct+'%';$('#saving-badge').textContent=pct+'% saved';$('#original-size').textContent=bytes(originalBlob.size);$('#compressed-size').textContent=bytes(b.size);$('#estimated-meta').textContent=`Estimated: ${bytes(b.size)}`;window.Nexauren?.trackTool?.('tool_process',tool,{title:'Image compressed',originalBytes:originalBlob.size,resultBytes:b.size});screen(2)},format,format==='image/png'?undefined:quality)},originalUrl)}
$('[data-action="compress"]')?.addEventListener('click',compress);$('[data-action="to-adjust"]')?.addEventListener('click',()=>{if(files.length)screen(1)});$('[data-action="back-select"]')?.addEventListener('click',()=>screen(0));$('[data-action="back-adjust"]')?.addEventListener('click',()=>screen(1));$('[data-action="to-download"]')?.addEventListener('click',()=>screen(3));$('[data-action="back-compare"]')?.addEventListener('click',()=>screen(2));
$('[data-action="fit"]')?.addEventListener('click',()=>{$('#studio-preview').style.objectFit='contain'});$('[data-action="actual"]')?.addEventListener('click',()=>{$('#studio-preview').style.maxWidth='none';$('#studio-preview').style.maxHeight='none';setTimeout(()=>{$('#studio-preview').style.maxWidth='100%';$('#studio-preview').style.maxHeight='100%'},1200)});
const modal=$('#download-modal');const open=()=>{modal.hidden=false;modal.setAttribute('aria-hidden','false')};const close=()=>{modal.hidden=true;modal.setAttribute('aria-hidden','true')};
$('[data-action="download"]')?.addEventListener('click',()=>{if(resultBlob){$('#final-size').textContent=bytes(resultBlob.size);open()}});$('[data-action="close-modal"]')?.addEventListener('click',close);$('[data-action="confirm-download"]')?.addEventListener('click',()=>{if(!resultBlob)return;const ext=format==='image/jpeg'?'jpg':format.split('/')[1],u=URL.createObjectURL(resultBlob),a=document.createElement('a');a.href=u;a.download=`nexauren-compressed-image.${ext}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);window.Nexauren?.trackTool?.('tool_download',tool,{title:'Image downloaded',bytes:resultBlob.size});close()});
window.Nexauren?.loadTools?.().catch(()=>{}).then(()=>window.Nexauren?.trackTool?.('tool_open',tool));window.addEventListener('beforeunload',()=>{if(originalUrl)URL.revokeObjectURL(originalUrl);if(resultUrl)URL.revokeObjectURL(resultUrl)});
})();