import original from './.worker-build/worker.js';
const j=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const n=v=>Number(v||0); const now=()=>Math.floor(Date.now()/1000);
async function admin(req,env,ctx){try{const u=new URL('/api/admin/users?limit=1',req.url);const r=await original.fetch(new Request(u,{method:'GET',headers:req.headers}),env,ctx);return r.status===200}catch{return false}}
async function q(env,sql,...args){try{return (await env.DB.prepare(sql).bind(...args).first())||{}}catch{return {}}}
async function count(env,table,since){const r=await q(env,`SELECT COUNT(*) total FROM ${table}${since?' WHERE created_at>=?1':''}`,...(since?[since]:[]));return n(r.total)}
async function stats(req,env,ctx){if(!await admin(req,env,ctx))return j({error:'Forbidden'},403);const u=new URL(req.url);let days=Math.min(365,Math.max(1,n(u.searchParams.get('days'))||7));const end=now(),start=end-days*86400;const users=await q(env,'SELECT COUNT(*) total FROM users');const newUsers=await count(env,'users',start);const active=await q(env,"SELECT COUNT(DISTINCT user_id) total FROM sessions WHERE expires_at>?1",end);const sent=await q(env,"SELECT COUNT(*) total FROM nexauren_notification_recipients r JOIN nexauren_notifications x ON x.id=r.notification_id WHERE x.status IN ('SENT','ACTIVE') AND r.created_at>=?1",start);const read=await q(env,"SELECT COUNT(*) total FROM nexauren_notification_recipients r JOIN nexauren_notifications x ON x.id=r.notification_id WHERE x.status IN ('SENT','ACTIVE') AND r.read_at IS NOT NULL AND r.created_at>=?1",start);const forms=await count(env,'forms',start);const reviews=await count(env,'reviews',start);let tools=0;for(const t of ['tool_usage','tool_usages','tools_usage']){const x=await q(env,`SELECT COUNT(*) total FROM ${t} WHERE created_at>=?1`,start);if(x.total!=null){tools=n(x.total);break}}
const series=async(sql)=>{try{return (await env.DB.prepare(sql).bind(start).all()).results||[]}catch{return []}};const usersSeries=await series("SELECT strftime('%Y-%m-%d',datetime(created_at,'unixepoch')) label,COUNT(*) value FROM users WHERE created_at>=?1 GROUP BY label ORDER BY label");const notifSeries=await series("SELECT strftime('%Y-%m-%d',datetime(r.created_at,'unixepoch')) label,COUNT(*) value FROM nexauren_notification_recipients r JOIN nexauren_notifications x ON x.id=r.notification_id WHERE x.status IN ('SENT','ACTIVE') AND r.created_at>=?1 GROUP BY label ORDER BY label");const readSeries=await series("SELECT strftime('%Y-%m-%d',datetime(r.read_at,'unixepoch')) label,COUNT(*) value FROM nexauren_notification_recipients r JOIN nexauren_notifications x ON x.id=r.notification_id WHERE x.status IN ('SENT','ACTIVE') AND r.read_at>=?1 GROUP BY label ORDER BY label");const toolsSeries=[];for(const t of ['tool_usage','tool_usages','tools_usage']){try{const x=(await env.DB.prepare(`SELECT name label,COUNT(*) value FROM ${t} WHERE created_at>=?1 GROUP BY name ORDER BY value DESC LIMIT 10`).bind(start).all()).results||[];if(x.length){toolsSeries.push(...x);break}}catch{}}
return j({range_label:days===1?'Today':`Last ${days} days`,overview:{total_users:n(users.total),active_users:n(active.total),new_users:newUsers,notifications_sent:n(sent.total),notifications_read:n(read.total),forms,reviews,tools_used:tools},series:{users:usersSeries,notifications:notifSeries.map(x=>({label:x.label,value:n(x.value)})),growth:usersSeries.map((x,i)=>({label:x.label,value:usersSeries.slice(0,i+1).reduce((a,b)=>a+n(b.value),0)})),activity:usersSeries,notifications_read:readSeries},top:{tools:toolsSeries,users:[],content:[],events:[]}})}
export default {async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/api/admin/statistics'&&request.method==='GET'){try{return await stats(request,env,ctx)}catch(e){console.error(e);return j({error:'Unable to calculate statistics.'},500)}}return original.fetch(request,env,ctx)}};