/* Nexauren authentication and frontend Worker. */
"use strict";
const SESSION_DAYS=7,MIN_PASSWORD_LENGTH=8,MAX_PASSWORD_LENGTH=200,MAX_NAME_LENGTH=100,MAX_EMAIL_LENGTH=254,PBKDF2_ITERATIONS=100000,LOGIN_WINDOW_MS=900000,LOGIN_LIMIT=10;
export default{async fetch(request,env){try{const url=new URL(request.url);if(request.method==="OPTIONS")return handleOptions(request);const response=url.pathname==="/api"||url.pathname.startsWith("/api/")?await handleApi(request,env,url):await handleFrontend(request,env,url);return withSecurity(response)}catch(error){console.error("Nexauren Worker Error",error);return withSecurity(json({success:false,message:"Internal server error."},500,request))}}};
async function handleFrontend(request,env,url){if(request.method!=="GET"&&request.method!=="HEAD")return new Response("Method Not Allowed",{status:405,headers:{Allow:"GET, HEAD, OPTIONS"}});const path=url.pathname,publicFiles=new Set(["/pages/login.html","/pages/register.html","/pages/forgot-password.html","/pages/reset-password.html","/pages/signup.html"]),publicRoutes={"/":"/","/login":"/pages/login.html","/register":"/pages/register.html","/signup":"/pages/register.html","/forgot-password":"/pages/forgot-password.html","/reset-password":"/pages/reset-password.html"},protectedRoutes={"/account":"/pages/account.html","/account/":"/pages/account.html","/dashboard":"/dashboard/index.html","/dashboard/":"/dashboard/index.html"};if(Object.prototype.hasOwnProperty.call(publicRoutes,path))return asset(request,env,publicRoutes[path]);if(publicFiles.has(path))return env.ASSETS.fetch(request);const staticResource=/\.(?:css|js|mjs|map|png|jpg|jpeg|gif|webp|svg|ico|avif|bmp|woff|woff2|ttf|otf|eot|mp3|wav|ogg|mp4|webm|json|txt)$/i.test(path)||path.startsWith("/assets/")||path.startsWith("/static/")||path.startsWith("/favicon");if(staticResource)return env.ASSETS.fetch(request);if(!await requireUser(request,env))return redirectToLogin(request,url);if(protectedRoutes[path])return asset(request,env,protectedRoutes[path]);if(path.length>1&&path.endsWith("/")){const target=protectedRoutes[path.slice(0,-1)];if(target)return asset(request,env,target)}return env.ASSETS.fetch(request)}
function asset(request,env,path){return env.ASSETS.fetch(new Request(new URL(path,request.url).toString(),request))}
function redirectToLogin(request,url){const login=new URL("/login",request.url),next=url.pathname+url.search;if(next.length<=2000)login.searchParams.set("next",next);const headers=new Headers({Location:login.toString(),"Cache-Control":"no-store"});if(getSessionToken(request))headers.set("Set-Cookie",clearSessionCookie());return new Response(null,{status:302,headers})}
async function handleApi(request,env,url){const path=url.pathname;if(path==="/api"||path==="/api/health")return request.method==="GET"?json({success:true,service:"Nexauren API",status:"online"},200,request):methodNotAllowed("GET");if(path==="/api/register"||path==="/api/auth/register")return request.method==="POST"?register(request,env):methodNotAllowed("POST");if(path==="/api/login"||path==="/api/auth/login")return request.method==="POST"?login(request,env):methodNotAllowed("POST");if(path==="/api/me"||path==="/api/account/me")return request.method==="GET"?currentUser(request,env):methodNotAllowed("GET");if(path==="/api/logout"||path==="/api/auth/logout")return request.method==="POST"?logout(request,env):methodNotAllowed("POST");if(path==="/api/account/deactivate")return request.method==="POST"?deactivate(request,env):methodNotAllowed("POST");if(path==="/api/account/delete")return request.method==="POST"?deleteAccount(request,env):methodNotAllowed("POST");return json({success:false,message:"API endpoint not found."},404,request)}
async function register(request,env){if(!env.DB)return json({success:false,message:"Database is not configured."},500,request);const data=await readJson(request);if(!data)return json({success:false,message:"Invalid request."},400,request);const name=String(data.name??data.display_name??"").trim(),email=String(data.email??"").trim().toLowerCase(),password=String(data.password??"");if(!name||name.length>MAX_NAME_LENGTH)return json({success:false,message:"Please enter a valid name."},400,request);if(!email||email.length>MAX_EMAIL_LENGTH||!isValidEmail(email))return json({success:false,message:"Please enter a valid email."},400,request);if(password.length<MIN_PASSWORD_LENGTH||password.length>MAX_PASSWORD_LENGTH)return json({success:false,message:"Password must contain between 8 and 200 characters."},400,request);try{const exists=await env.DB.prepare("SELECT id FROM users WHERE email = ? LIMIT 1").bind(email).first();if(exists)return json({success:false,message:"An account with this email already exists."},409,request);const passwordHash=await hashPassword(password),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO users (id,email,password_hash,display_name,status) VALUES (?,?,?,?, 'active')").bind(id,email,passwordHash,name).run();const session=await createSession(env,id);return json({success:true,message:"Account created successfully.",user:{id,name,email}},201,request,{"Set-Cookie":buildSessionCookie(session.token)})}catch(error){console.error("Registration error",error);return json({success:false,message:"Unable to create account. Please try again."},500,request)}}
async function login(request,env){if(!env.DB)return json({success:false,message:"Database is not configured."},500,request);const limit=await checkLoginLimit(request);if(!limit.allowed)return json({success:false,message:"Too many login attempts. Please try again later."},429,request,{"Retry-After":String(limit.retryAfter)});const data=await readJson(request);if(!data)return json({success:false,message:"Invalid request."},400,request);const email=String(data.email??"").trim().toLowerCase(),password=String(data.password??"");if(!email||!isValidEmail(email)||!password||password.length>MAX_PASSWORD_LENGTH){await recordLoginFailure(request);return json({success:false,message:"Invalid email or password."},401,request)}try{const user=await env.DB.prepare("SELECT id,email,display_name,password_hash,status FROM users WHERE email = ? LIMIT 1").bind(email).first();if(!user||user.status!=="active"||!(await verifyPassword(password,user.password_hash))){await recordLoginFailure(request);return json({success:false,message:"Invalid email or password."},401,request)}await clearLoginFailures(request);const session=await createSession(env,user.id);return json({success:true,message:"Signed in successfully.",user:{id:user.id,name:user.display_name||"Nexauren user",email:user.email}},200,request,{"Set-Cookie":buildSessionCookie(session.token)})}catch(error){console.error("Login error",error);return json({success:false,message:"Unable to sign in. Please try again."},500,request)}}
async function createSession(env,userId){const bytes=crypto.getRandomValues(new Uint8Array(32)),token=bytesToBase64Url(bytes),tokenHash=await sha256(token),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO sessions (id,user_id,token_hash,expires_at) VALUES (?, ?, ?, datetime('now','+7 days'))").bind(id,userId,tokenHash).run();return{id,token}}
async function requireUser(request,env){if(!env.DB)return null;const token=getSessionToken(request);if(!token)return null;try{const hash=await sha256(token);return await env.DB.prepare("SELECT sessions.id AS session_id,users.id,users.email,users.display_name AS name,users.status FROM sessions INNER JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND sessions.expires_at>CURRENT_TIMESTAMP AND sessions.revoked_at IS NULL AND users.status='active' LIMIT 1").bind(hash).first()}catch(error){console.error("Authentication lookup error",error);return null}}
async function currentUser(request,env){const user=await requireUser(request,env);if(!user)return json({success:true,authenticated:false},200,request,{"Set-Cookie":clearSessionCookie()});return json({success:true,authenticated:true,user:{id:user.id,name:user.name||"Nexauren user",email:user.email}},200,request)}
async function logout(request,env){const token=getSessionToken(request);if(token&&env.DB)try{await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha256(token)).run()}catch(error){console.error("Logout error",error);return json({success:false,message:"Unable to sign out."},500,request)}return json({success:true,message:"Signed out successfully."},200,request,{"Set-Cookie":clearSessionCookie()})}
async function deactivate(request,env){const user=await requireUser(request,env);if(!user)return unauthorized(request);try{await env.DB.prepare("UPDATE users SET status='disabled',disabled_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(user.id).run();await env.DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(user.id).run();return json({success:true,message:"Your account has been deactivated."},200,request,{"Set-Cookie":clearSessionCookie()})}catch(error){console.error("Deactivate error",error);return json({success:false,message:"Unable to deactivate your account."},500,request)}}
async function deleteAccount(request,env){const user=await requireUser(request,env);if(!user)return unauthorized(request);try{await env.DB.prepare("DELETE FROM users WHERE id=?").bind(user.id).run();return json({success:true,message:"Your account has been deleted."},200,request,{"Set-Cookie":clearSessionCookie()})}catch(error){console.error("Delete account error",error);return json({success:false,message:"Unable to delete your account."},500,request)}}
async function readJson(request){try{const data=await request.json();return data&&typeof data==="object"&&!Array.isArray(data)?data:null}catch{return null}}
async function hashPassword(password){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),{name:"PBKDF2"},false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:PBKDF2_ITERATIONS,hash:"SHA-256"},key,256);return["pbkdf2_sha256",PBKDF2_ITERATIONS,bytesToBase64Url(salt),bytesToBase64Url(new Uint8Array(bits))].join("$")}
async function verifyPassword(password,stored){try{const parts=String(stored).split("$");if(parts.length!==4||parts[0]!=="pbkdf2_sha256")return false;const iterations=Number(parts[1]);if(!Number.isInteger(iterations)||iterations<10000||iterations>1000000)return false;const salt=base64UrlToBytes(parts[2]),expected=base64UrlToBytes(parts[3]),key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),{name:"PBKDF2"},false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations,hash:"SHA-256"},key,expected.length*8);return timingSafeEqual(new Uint8Array(bits),expected)}catch{return false}}
async function sha256(value){return bytesToBase64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))))}
function timingSafeEqual(a,b){if(!(a instanceof Uint8Array)||!(b instanceof Uint8Array)||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0}
function bytesToBase64Url(bytes){let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function base64UrlToBytes(value){try{const n=String(value).replace(/-/g,"+").replace(/_/g,"/"),p=n.length%4,binary=atob(p?n+"=".repeat(4-p):n),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}catch{return new Uint8Array()}}
function getSessionToken(request){const token=parseCookies(request.headers.get("Cookie")||"").nexauren_session;return token&&/^[A-Za-z0-9_-]{40,100}$/.test(token)?token:null}
function parseCookies(header){const result={};for(const part of String(header).split(";")){const i=part.indexOf("=");if(i<0)continue;const name=part.slice(0,i).trim(),value=part.slice(i+1).trim();if(name){try{result[name]=decodeURIComponent(value)}catch{result[name]=value}}}return result}
function buildSessionCookie(token){return`nexauren_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${7*86400}`}
function clearSessionCookie(){return"nexauren_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT"}
function isValidEmail(email){return typeof email==="string"&&email.length>=3&&email.length<=MAX_EMAIL_LENGTH&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)}
function unauthorized(request){return json({success:false,authenticated:false,message:"Authentication required."},401,request)}
function methodNotAllowed(allowed){return new Response(JSON.stringify({success:false,message:"Method not allowed."}),{status:405,headers:{"Content-Type":"application/json; charset=utf-8",Allow:`${allowed}, OPTIONS`,"Cache-Control":"no-store"}})}
function json(data,status=200,request=null,extra={}){const headers=new Headers({"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store, no-cache, must-revalidate",Pragma:"no-cache","X-Content-Type-Options":"nosniff"}),origin=request?.headers.get("Origin");if(origin)try{if(new URL(origin).origin===new URL(request.url).origin){headers.set("Access-Control-Allow-Origin",origin);headers.set("Access-Control-Allow-Credentials","true");headers.set("Vary","Origin")}}catch{}for(const[key,value]of Object.entries(extra))headers.set(key,value);return new Response(JSON.stringify(data),{status,headers})}
function handleOptions(request){const headers=new Headers({"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Cache-Control":"no-store"}),origin=request.headers.get("Origin");if(origin)try{if(new URL(origin).origin===new URL(request.url).origin){headers.set("Access-Control-Allow-Origin",origin);headers.set("Access-Control-Allow-Credentials","true");headers.set("Vary","Origin")}}catch{}return new Response(null,{status:204,headers})}
function withSecurity(response){const headers=new Headers(response.headers);headers.set("X-Content-Type-Options","nosniff");headers.set("X-Frame-Options","DENY");headers.set("Referrer-Policy","strict-origin-when-cross-origin");headers.set("Permissions-Policy","camera=(), microphone=(), geolocation=(), payment=()");return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function rateKey(request){return new Request(`https://nexauren-login-rate-limit/${encodeURIComponent(request.headers.get("CF-Connecting-IP")||"unknown")}`)}
async function checkLoginLimit(request){try{const response=await caches.default.match(rateKey(request));if(!response)return{allowed:true,retryAfter:0};const data=await response.json();if(!data||data.expiresAt<=Date.now())return{allowed:true,retryAfter:0};if(data.count>=LOGIN_LIMIT)return{allowed:false,retryAfter:Math.max(1,Math.ceil((data.expiresAt-Date.now())/1000))};return{allowed:true,retryAfter:0}}catch{return{allowed:true,retryAfter:0}}}
async function recordLoginFailure(request){try{const key=rateKey(request),oldResponse=await caches.default.match(key),old=oldResponse?await oldResponse.json():null,now=Date.now(),record=old&&old.expiresAt>now?{count:old.count+1,expiresAt:old.expiresAt}:{count:1,expiresAt:now+LOGIN_WINDOW_MS};await caches.default.put(key,new Response(JSON.stringify(record),{headers:{"Cache-Control":`max-age=${LOGIN_WINDOW_MS/1000}`,"Content-Type":"application/json"}}))}catch{}}
async function clearLoginFailures(request){try{await caches.default.delete(rateKey(request))}catch{}}
