import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm';
(()=>{'use strict';
env.allowLocalModels=false;env.useBrowserCache=true;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const input=$('#image-input'),drop=$('#dropzone'),browse=$('#browse'),change=$('#change'),removeBtn=$('#remove-button'),again=$('#again'),download=$('#download'),preview=$('#preview'),resultCanvas=$('#result-canvas'),composite=$('#composite'),filename=$('#filename'),status=$('#status'),error=$('#error'),modelStatus=$('#model-status'),modal=$('#follow-modal'),confirm=$('#confirm-download');
let source=null,cutout=null,original=null,background='transparent',bgColor='#635bff',bgColor2='#00cfff',bgImage=null,blur=14,pipe=null;
const screens=['select','remove','edit','download'];
function show(name){screens.forEach(n=>{const el=$(`[data-screen="${n}"]`);if(el){el.hidden=n!==name;el.classList.toggle('active',n===name)}});$$('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)<=screens.indexOf(name)+1));if(name==='edit')renderComposite()}
function fail(msg){error.textContent=msg;error.hidden=false}function clearError(){error.hidden=true;error.textContent=''}
function loadFile(file){clearError();if(!file||!file.type.startsWith('image/'))return fail('Please choose a JPG, PNG or WebP image.');if(file.size>20*1024*1024)return fail('Please choose an image smaller than 20 MB.');const r=new FileReader();r.onload=()=>{source=r.result;preview.src=source;filename.textContent=file.name;status.textContent='Ready';original=new Image();original.onload=()=>show('remove');original.src=source};r.readAsDataURL(file)}
browse.addEventListener('click',e=>{e.preventDefault();input.click()});drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('dragging')});drop.addEventListener('dragleave',()=>drop.classList.remove('dragging'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragging');loadFile(e.dataTransfer.files[0])});input.addEventListener('change',()=>loadFile(input.files[0]));change.addEventListener('click',()=>show('select'));$('#back-remove').addEventListener('click',()=>show('remove'));again.addEventListener('click',()=>show('edit'));
async function getPipe(){if(pipe)return pipe;modelStatus.textContent='Loading AI model…';try{pipe=await pipeline('background-removal','briaai/RMBG-1.4',{device:'webgpu',dtype:'fp32'});modelStatus.textContent='AI model ready — WebGPU';return pipe}catch(webgpuError){console.warn('WebGPU unavailable, falling back to WASM',webgpuError);try{pipe=await pipeline('background-removal','briaai/RMBG-1.4',{device:'wasm',dtype:'fp32'});modelStatus.textContent='AI model ready — WASM';return pipe}catch(e){console.error(e);pipe=null;throw e}}}
async function removeBackground(){if(!source)return;clearError();removeBtn.disabled=true;status.textContent='Starting AI…';try{const segmenter=await getPipe();status.textContent='Removing background…';const outputs=await segmenter(source,{subtask:'foreground-extraction'});const image=Array.isArray(outputs)?outputs[0]:outputs;if(!image?.data||!image.width||!image.height)throw new Error('Background-removal pipeline returned no image');
const w=image.width,h=image.height,channels=image.channels||4,data=image.data;const c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=w;c.height=h;let rgba;if(channels===4){rgba=data instanceof Uint8ClampedArray?data:new Uint8ClampedArray(data)}else{rgba=new Uint8ClampedArray(w*h*4);for(let i=0;i<w*h;i++){const v=data[i];rgba[i*4]=255;rgba[i*4+1]=255;rgba[i*4+2]=255;rgba[i*4+3]=v<=1?Math.round(v*255):v}}ctx.putImageData(new ImageData(rgba,w,h),0,0);cutout=c;status.textContent='Background removed';show('edit')}catch(e){console.error(e);fail('The AI model could not finish this image. Try a smaller image or reload the page.');status.textContent='Error'}finally{removeBtn.disabled=false}}
removeBtn.addEventListener('click',removeBackground);
$$('.choice').forEach(b=>b.addEventListener('click',()=>{$$('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');background=b.dataset.bg;$('#color-one').style.display=background==='color'||background==='gradient'?'flex':'none';$('#color-two').style.display=background==='gradient'?'flex':'none';$('#background-file-label').style.display=background==='image'?'flex':'none';$('#blur-control').style.display=background==='blur'?'flex':'none';renderComposite()}));
$('#bg-color').addEventListener('input',e=>{bgColor=e.target.value;renderComposite()});$('#bg-color-two').addEventListener('input',e=>{bgColor2=e.target.value;renderComposite()});$('#blur-range').addEventListener('input',e=>{blur=+e.target.value;$('#blur-value').textContent=blur+'px';renderComposite()});$('#background-input').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{bgImage=new Image();bgImage.onload=renderComposite;bgImage.src=r.result};r.readAsDataURL(f)});
function fit(ctx,img,w,h){const s=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*s,dh=img.naturalHeight*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh)}
function drawBackground(ctx,w,h){if(background==='transparent')return;if(background==='color'){ctx.fillStyle=bgColor;ctx.fillRect(0,0,w,h)}else if(background==='gradient'){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,bgColor);g.addColorStop(1,bgColor2);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}else if(background==='image'&&bgImage)fit(ctx,bgImage,w,h);else if(background==='blur'){ctx.save();ctx.filter=`blur(${blur}px)`;fit(ctx,original,w,h);ctx.restore()}}
function renderComposite(){if(!cutout)return;const w=cutout.width,h=cutout.height;composite.width=w;composite.height=h;const ctx=composite.getContext('2d');ctx.clearRect(0,0,w,h);drawBackground(ctx,w,h);ctx.drawImage(cutout,0,0);$('#edit-status').textContent=background==='transparent'?'Transparent':background==='color'?'Solid color':background==='gradient'?'Gradient':background==='image'?'Custom image':'Blur original'}
$('#to-download').addEventListener('click',()=>{const ctx=resultCanvas.getContext('2d');resultCanvas.width=composite.width;resultCanvas.height=composite.height;ctx.clearRect(0,0,resultCanvas.width,resultCanvas.height);ctx.drawImage(composite,0,0);show('download')});
function close(){modal.hidden=true;modal.setAttribute('aria-hidden','true')}download.addEventListener('click',()=>{modal.hidden=false;modal.setAttribute('aria-hidden','false')});$('#close-modal').addEventListener('click',close);$('#modal-x').addEventListener('click',close);confirm.addEventListener('click',()=>{resultCanvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexauren-background-removed.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);close()},'image/png')});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()});
$('#color-one').style.display='none';$('#color-two').style.display='none';$('#background-file-label').style.display='none';$('#blur-control').style.display='none';show('select')})();