(() => {
'use strict';
const input=document.querySelector('#pdf-input'),list=document.querySelector('#file-list'),count=document.querySelector('#file-count'),merge=document.querySelector('#merge'),clear=document.querySelector('#clear-files'),error=document.querySelector('#error'),result=document.querySelector('#result'),download=document.querySelector('#download'),startOver=document.querySelector('#start-over');
let files=[],mergedBlob=null;
const fmt=n=>{if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`};
const msg=t=>{error.textContent=t;error.hidden=!t};
const render=()=>{count.textContent=`${files.length} ${files.length===1?'file':'files'}`;merge.disabled=files.length<2;list.innerHTML=files.map((f,i)=>`<div class="file-item" draggable="true" data-i="${i}"><span class="drag-handle">☷</span><span class="file-index">${i+1}</span><span class="file-name"><strong>${f.name.replace(/[&<>"']/g,'')}</strong><small class="file-size">${fmt(f.size)}</small></span><span class="file-actions"><button class="icon-button" data-up="${i}" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-down="${i}" ${i===files.length-1?'disabled':''}>↓</button><button class="icon-button" data-remove="${i}">×</button></span></div>`).join('')};
input.addEventListener('change',()=>{const added=[...input.files].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'));if(!added.length)return msg('Please select valid PDF files.');files.push(...added);msg('');input.value='';render()});
list.addEventListener('click',e=>{const up=e.target.dataset.up,down=e.target.dataset.down,remove=e.target.dataset.remove;if(remove!==undefined)files.splice(+remove,1);else if(up!==undefined)[files[+up-1],files[+up]]=[files[+up],files[+up-1]];else if(down!==undefined)[files[+down+1],files[+down]]=[files[+down],files[+down+1]];render()});
list.addEventListener('dragstart',e=>{const item=e.target.closest('.file-item');if(item)e.dataTransfer.setData('text/plain',item.dataset.i)});list.addEventListener('dragover',e=>e.preventDefault());list.addEventListener('drop',e=>{e.preventDefault();const item=e.target.closest('.file-item');if(!item)return;const from=+e.dataTransfer.getData('text/plain'),to=+item.dataset.i;if(from===to)return;const [f]=files.splice(from,1);files.splice(to,0,f);render()});
clear.addEventListener('click',()=>{files=[];msg('');render();result.hidden=true});
merge.addEventListener('click',async()=>{msg('');merge.disabled=true;try{const {PDFDocument}=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');const out=await PDFDocument.create();for(const file of files){const doc=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});const pages=await out.copyPages(doc,doc.getPageIndices());pages.forEach(p=>out.addPage(p))}const bytes=await out.save();mergedBlob=new Blob([bytes],{type:'application/pdf'});document.querySelector('#result-name').textContent='merged.pdf';document.querySelector('#result-info').textContent=`${out.getPageCount()} pages · ${fmt(bytes.length)}`;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){console.error(e);msg('Could not merge these PDFs. Make sure they are valid and not protected by a password.')}finally{merge.disabled=files.length<2}});
download.addEventListener('click',()=>{if(!mergedBlob)return;const a=document.createElement('a');a.href=URL.createObjectURL(mergedBlob);a.download='merged.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});startOver.addEventListener('click',()=>{mergedBlob=null;result.hidden=true;window.scrollTo({top:0,behavior:'smooth'})});
render();
})();
