(() => {
  const extra = [
    {cat:'Authors',icon:'✒',name:'Novel',desc:'Chapter-based fiction template with title page, chapters, scenes and notes.',html:'<h1>Novel Title</h1><p><em>By Author Name</em></p><h2>Chapter One</h2><p>Begin the story...</p><h3>Scene One</h3><p>Write the scene here.</p><h2>Chapter Two</h2><p>Continue the story...</p>'},
    {cat:'Authors',icon:'✎',name:'Nonfiction Book',desc:'Long-form structure for guides, memoirs, biographies and educational books.',html:'<h1>Book Title</h1><p><em>By Author Name</em></p><h2>Introduction</h2><p>Introduce the subject and promise of the book.</p><h2>Part One</h2><h3>Chapter One</h3><p>Write the chapter here.</p><h2>Conclusion</h2><p>Summarize the main ideas.</p>'},
    {cat:'Authors',icon:'❖',name:'Poetry Collection',desc:'Minimal page structure for poems, collections and literary work.',html:'<h1>Poetry Collection</h1><p><em>By Author Name</em></p><h2>Poem One</h2><p>Write your poem here.<br><br>Use line breaks freely.</p><h2>Poem Two</h2><p>Continue your collection.</p>'},
    {cat:'Publishing',icon:'◫',name:'Book Proposal',desc:'Professional proposal for publishers, agents or independent publishing projects.',html:'<h1>Book Proposal</h1><h2>Overview</h2><p>Describe the book and its audience.</p><h2>Author</h2><p>Introduce the author and credentials.</p><h2>Market & Audience</h2><p>Describe readers and comparable titles.</p><h2>Chapter Outline</h2><p>Summarize each chapter.</p>'},
    {cat:'Career',icon:'↗',name:'Cover Letter',desc:'Focused job application letter tailored to a role and company.',html:'<h1>Cover Letter</h1><p>Date: __________</p><p>Dear Hiring Manager,</p><p>I am writing to apply for the position of...</p><h2>Why I Am a Fit</h2><p>Connect your experience to the role.</p><p>Sincerely,<br>Your Name</p>'},
    {cat:'Business',icon:'◆',name:'Marketing Plan',desc:'Goals, audience, positioning, channels, campaigns, budget and metrics.',html:'<h1>Marketing Plan</h1><h2>Goals</h2><p>Define measurable goals.</p><h2>Target Audience</h2><p>Describe your ideal customers.</p><h2>Positioning</h2><p>Explain your value proposition.</p><h2>Channels & Campaigns</h2><p>Plan your marketing activities.</p><h2>Budget & Metrics</h2><p>Set budget and KPIs.</p>'},
    {cat:'Business',icon:'◈',name:'Business Pitch',desc:'Clear pitch structure for founders, products, services and new ventures.',html:'<h1>Business Pitch</h1><h2>The Problem</h2><p>What problem exists?</p><h2>The Solution</h2><p>What are you building?</p><h2>Market</h2><p>Who needs it?</p><h2>Business Model</h2><p>How does it create value?</p><h2>Next Step</h2><p>What do you want from the reader?</p>'},
    {cat:'Business',icon:'▣',name:'Business Memo',desc:'Fast internal communication for decisions, updates and recommendations.',html:'<h1>MEMORANDUM</h1><p><strong>To:</strong> __________<br><strong>From:</strong> __________<br><strong>Date:</strong> __________<br><strong>Subject:</strong> __________</p><h2>Purpose</h2><p>State the purpose clearly.</p><h2>Details</h2><p>Provide the relevant information.</p><h2>Recommendation</h2><p>State the recommended action.</p>'},
    {cat:'Work',icon:'✓',name:'Project Brief',desc:'One-page project definition covering goals, scope, audience and deliverables.',html:'<h1>Project Brief</h1><h2>Project Goal</h2><p>Define the desired outcome.</p><h2>Audience</h2><p>Who is this for?</p><h2>Scope</h2><p>What is included and excluded?</p><h2>Deliverables</h2><ul><li>Deliverable one</li><li>Deliverable two</li></ul><h2>Timeline</h2><p>List key milestones.</p>'},
    {cat:'Work',icon:'▥',name:'Project Status Report',desc:'Recurring status report for progress, risks, blockers and next actions.',html:'<h1>Project Status Report</h1><p><strong>Project:</strong> ______ · <strong>Date:</strong> ______</p><h2>Overall Status</h2><p>Summarize current status.</p><h2>Completed</h2><ul><li>Completed item</li></ul><h2>In Progress</h2><ul><li>Current item</li></ul><h2>Risks & Blockers</h2><p>Describe risks.</p><h2>Next Actions</h2><p>List upcoming work.</p>'},
    {cat:'Publishing',icon:'✦',name:'Press Release',desc:'Publication-ready structure for announcements, launches and company news.',html:'<h1>FOR IMMEDIATE RELEASE</h1><h2>Headline</h2><p><strong>City, Date</strong> — Write the announcement lead here.</p><h2>Details</h2><p>Explain the news, context and significance.</p><h2>Quote</h2><blockquote>“Add an official quote here.”</blockquote><h2>About</h2><p>Short organization or author biography.</p><p>Contact: Name · Email · Website</p>'},
    {cat:'Publishing',icon:'◌',name:'Blog Article',desc:'Flexible editorial structure for articles, tutorials, opinion and web publishing.',html:'<h1>Article Title</h1><p><em>By Author · Date</em></p><h2>Introduction</h2><p>Open with the key idea.</p><h2>Main Section</h2><p>Develop the argument with examples.</p><h2>Practical Takeaways</h2><ul><li>Takeaway one</li><li>Takeaway two</li></ul><h2>Conclusion</h2><p>Close with a useful final thought.</p>'},
    {cat:'Academic',icon:'∑',name:'Thesis / Dissertation',desc:'Extended academic structure for research, chapters, methodology and references.',html:'<h1>Thesis Title</h1><p><strong>Author Name</strong><br>Institution · Degree · Date</p><h2>Abstract</h2><p>Research summary.</p><h2>Introduction</h2><p>Research problem and objectives.</p><h2>Literature Review</h2><p>Review relevant work.</p><h2>Methodology</h2><p>Explain the research method.</p><h2>Results</h2><p>Present findings.</p><h2>Discussion</h2><p>Interpret findings.</p><h2>Conclusion</h2><p>Conclusions and future research.</p>'},
    {cat:'Academic',icon:'⌘',name:'Research Proposal',desc:'Academic proposal for a research question, method, timeline and expected contribution.',html:'<h1>Research Proposal</h1><h2>Research Question</h2><p>State the central question.</p><h2>Background</h2><p>Explain the context.</p><h2>Objectives</h2><ul><li>Objective one</li><li>Objective two</li></ul><h2>Method</h2><p>Describe the approach.</p><h2>Timeline</h2><p>List milestones.</p><h2>References</h2><p>Add sources.</p>'},
    {cat:'Academic',icon:'⚑',name:'Lesson Plan',desc:'Structured planning page for teachers, trainers and educators.',html:'<h1>Lesson Plan</h1><p><strong>Topic:</strong> ______ · <strong>Duration:</strong> ______</p><h2>Learning Objectives</h2><ul><li>Students will...</li><li>Students will...</li></ul><h2>Materials</h2><p>List materials.</p><h2>Lesson Steps</h2><ol><li>Introduction</li><li>Activity</li><li>Practice</li><li>Review</li></ol><h2>Assessment</h2><p>Explain how learning will be assessed.</p>'},
    {cat:'Letters',icon:'♥',name:'Personal Letter',desc:'Warm, flexible format for personal correspondence and meaningful messages.',html:'<h1>A Letter to You</h1><p>Date: __________</p><p>Dear __________,</p><p>Write your message here.</p><p>With best wishes,<br>Your Name</p>'},
    {cat:'Career',icon:'★',name:'Personal Statement',desc:'Application-ready structure for university, scholarships and professional programs.',html:'<h1>Personal Statement</h1><h2>Who I Am</h2><p>Introduce your background and motivation.</p><h2>My Experience</h2><p>Explain experiences that shaped you.</p><h2>My Goals</h2><p>Describe your future goals.</p><h2>Why This Opportunity</h2><p>Connect your goals to the program.</p>'},
    {cat:'Work',icon:'☑',name:'Action Plan',desc:'Turn goals into tasks with owners, deadlines, priorities and measurable outcomes.',html:'<h1>Action Plan</h1><p><strong>Goal:</strong> __________________</p><table class="dc-table"><tbody><tr><td>Task</td><td>Owner</td><td>Due</td><td>Status</td></tr><tr><td>Task one</td><td>Name</td><td>Date</td><td>Open</td></tr></tbody></table><h2>Success Measure</h2><p>Define how success will be measured.</p>'}
  ];
  if(!Array.isArray(window.templates)) return;
  extra.forEach((t,i)=>t.id=`extra-${i+1}`);
  window.templates.push(...extra);
  if(typeof window.renderFilters==='function') window.renderFilters();
  if(typeof window.render==='function') window.render();
})();