(() => {
'use strict';
const table=document.querySelector('#sheet'),thead=table.querySelector('thead'),tbody=table.querySelector('tbody'),status=document.querySelector('#status');
let rows=20,cols=8,activeSheet=0,history=[],future=[];
const key='nexauren-spreadsheet-v2';
let sheets=loadProject()?.sheets||[{name:'Sheet 1',data:[]}];
function loadProject(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function snapshot(){return JSON.stringify({sheets,activeSheet,rows,cols})}
function save(){localStorage.setItem(key,snapshot());status.textContent='Saved locally'}
function remember(){history.push(snapshot());if(history.length>50)history.shift();future=[]}
function colName(n){let s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s}
function cell(r,c){return tbody.rows[r]?.cells[c+1]}
function getData(){return [...tbody.rows].map(r=>[...r.cells].slice(1).map(c=>c.textContent))}
function build(){const data=sheets[activeSheet].data||[];thead.innerHTML='<tr><th>#</th>'+Array.from({length:cols},(_,i)=>`<th data-col="${i}">${colName(i)}</th>`).join('')+'</tr>';tbody.innerHTML='';for(let r=0;r<rows;r++){const tr=document.createElement('tr');const n=document.createElement('td');n.textContent=r+1;tr.append(n);for(let c=0;c<cols;c++){const td=document.createElement('td');td.contentEditable='true';td.spellcheck=false;td.dataset.r=r;td.dataset.c=c;td.textContent=data?.[r]?.[c]??'';td.addEventListener('focus',()=>td.classList.add('selected'));td.addEventListener('blur',()=>td.classList.remove('selected'));td.addEventListener('input',()=>{sheets[activeSheet].data=getData();save()});tr.append(td)}tbody.append(tr)}}
function evalFormula(value){if(!value.startsWith('='))return value;let f=value.slice(1).toUpperCase();const ref=x=>{const m=x.match(/^([A-Z]+)(\d+)$/);if(!m)return Number(x)||0;let c=0;for(const ch of m[1])c=c*26+ch.charCodeAt(0)-64;c--;return Number(cell(+m[2]-1,c)?.textContent)||0};const range=(a,b)=>{const ma=a.match(/^([A-Z]+)(\d+)$/),mb=b.match(/^([A-Z]+)(\d+)$/);if(!ma||!mb)return[];let c1=refIndex(ma[1]),c2=refIndex(mb[1]),r1=+ma[2]-1,r2=+mb[2]-1,v=[];for(let r=r1;r<=r2;r++)for(let c=c1;c<=c2;c++)v.push(Number(cell(r,c)?.textContent)||0);return v};const refIndex=s=>{let n=0;for(const ch of s)n=n*26+ch.charCodeAt(0)-64;return n-1};f=f.replace(/([A-Z]+\d+):([A-Z]+\d+)/g,(_,a,b)=>JSON.stringify(range(a,b)));f=f.replace(/([A-Z]+\d+)/g,(_,x)=>ref(x));try{if(/^SUM\(/.test(f))return eval(f.replace(/^SUM\(/,'[').replace(/\)$/ ,']')).reduce((a,b)=>a+b,0);if(/^AVERAGE\(/.test(f)){const a=eval(f.replace(/^AVERAGE\(/,'[').replace(/\)$/ ,']'));return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}if(/^MIN\(/.test(f))return Math.min(...eval(f.replace(/^MIN\(/,'[').replace(/\)$/ ,']')));if(/^MAX\(/.test(f))return Math.max(...eval(f.replace(/^MAX\(/,'[').replace(/\)$/ ,']')));if(/^COUNT\(/.test(f))return eval(f.replace(/^COUNT\(/,'[').replace(/\)$/ ,']')).filter(Number.isFinite).length;if(/^IF\(/.test(f)){const a=f.slice(3,-1).split(',');return eval(a[0])?a[1]:a[2]}return Function(`return ${f}`)()}catch{return '#ERROR!'}}
function recalc(){[...tbody.querySelectorAll('td[contenteditable=true]')].forEach(td=>{if(td.textContent.trim().startsWith('=')){td.title=String(evalFormula(td.textContent.trim()))}})}
function restore(s){try{const p=JSON.parse(s);sheets=p.sheets;activeSheet=p.activeSheet;rows=p.rows;cols=p.cols;build();save()}catch{}}
function csvDownload(){const data=getData();const csv=[Array.from({length:cols},(_,i)=>colName(i)).join(','),...data.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${sheets[activeSheet].name}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function addSheet(){remember();sheets.push({name:`Sheet ${sheets.length+1}`,data:[]});activeSheet=sheets.length-1;build();save()}
function exportProject(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([snapshot()],{type:'application/json'}));a.download='nexauren-spreadsheet.json';a.click()}
function importProject(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>restore(r.result);r.readAsText(f)};i.click()}
document.querySelector('#newBtn').onclick=()=>{remember();sheets=[{name:'Sheet 1',data:[]}];activeSheet=0;rows=20;cols=8;build();save()};document.querySelector('#clearBtn').onclick=()=>{remember();sheets[activeSheet].data=[];build();save()};document.querySelector('#addRowBtn').onclick=()=>{remember();rows++;build();save()};document.querySelector('#addColBtn').onclick=()=>{remember();cols++;build();save()};document.querySelector('#downloadBtn').onclick=csvDownload;
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(history.length){future.push(snapshot());restore(history.pop())}}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();if(future.length){history.push(snapshot());restore(future.pop())}}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();const q=prompt('Search spreadsheet');if(q)[...tbody.querySelectorAll('td[contenteditable=true]')].forEach(c=>{c.classList.toggle('search-hit',c.textContent.toLowerCase().includes(q.toLowerCase()))})}});
window.nexaSpreadsheet={addSheet,exportProject,importProject,renameSheet:(name)=>{if(name){sheets[activeSheet].name=name;save()}},setBold:()=>document.execCommand('bold'),setItalic:()=>document.execCommand('italic'),setUnderline:()=>document.execCommand('underline'),recalculate:recalc};
build();recalc();
})();
