(() => {
'use strict';
const $=id=>document.getElementById(id),table=$('sheet'),thead=table?.querySelector('thead'),tbody=table?.querySelector('tbody');
if(!table||!thead||!tbody)return;
const STORE='nexauren-spreadsheet-v4';
let rows=20,cols=8,activeSheet=0,history=[],future=[],selected=null,filterText='';
let sheets=[];
try{const p=JSON.parse(localStorage.getItem(STORE)||'null');sheets=p?.sheets||[{name:'Sheet 1',data:[]}];rows=p?.rows||20;cols=p?.cols||8;activeSheet=Math.min(p?.activeSheet||0,sheets.length-1)}catch{sheets=[{name:'Sheet 1',data:[]}]}
const current=()=>sheets[activeSheet];
const colName=n=>{let s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s};
function data(){const d=current().data||(current().data=[]);while(d.length<rows)d.push([]);d.forEach(r=>{while(r.length<cols)r.push('')});return d.slice(0,rows).map(r=>r.slice(0,cols))}
function snapshot(){current().data=data();return JSON.stringify({sheets,rows,cols,activeSheet})}
function save(){localStorage.setItem(STORE,snapshot());if($('status'))$('status').textContent='Saved locally'}
function remember(){history.push(snapshot());if(history.length>50)history.shift();future=[]}
function restore(s){try{const p=JSON.parse(s);sheets=p.sheets;rows=p.rows;cols=p.cols;activeSheet=Math.min(p.activeSheet||0,sheets.length-1);render();save()}catch{}}
function cell(r,c){return tbody.rows[r]?.cells[c+1]}
function parseRef(s){const m=String(s).trim().toUpperCase().match(/^([A-Z]+)(\d+)$/);if(!m)return null;let c=0;for(const ch of m[1])c=c*26+ch.charCodeAt(0)-64;return{r:+m[2]-1,c:c-1}}
function val(r,c,seen=new Set()){const v=current().data?.[r]?.[c]??'';if(typeof v!=='string'||!v.startsWith('=')){const n=Number(String(v).replace('%',''));return Number.isFinite(n)?(String(v).includes('%')?n/100:n):0}const id=r+':'+c;if(seen.has(id))return NaN;seen.add(id);return formula(v.slice(1),seen)}
function vals(s,seen){return s.split(',').flatMap(p=>{p=p.trim();const m=p.match(/^([A-Z]+\d+):([A-Z]+\d+)$/);if(m){const a=parseRef(m[1]),b=parseRef(m[2]),o=[];for(let r=Math.min(a.r,b.r);r<=Math.max(a.r,b.r);r++)for(let c=Math.min(a.c,b.c);c<=Math.max(a.c,b.c);c++)o.push(val(r,c,new Set(seen)));return o}const ref=parseRef(p);return ref?[val(ref.r,ref.c,new Set(seen))]:[Number(p)]})}
function formula(e,seen=new Set()){e=e.trim();const m=e.match(/^([A-Z]+)\((.*)\)$/i);if(m){const n=m[1].toUpperCase();if(n==='IF'){const a=m[2].split(',');return formula(a[0],seen)?(a[1]||''):(a[2]||'')}const a=vals(m[2],seen).filter(Number.isFinite);if(n==='SUM')return a.reduce((x,y)=>x+y,0);if(n==='AVERAGE')return a.length?a.reduce((x,y)=>x+y,0)/a.length:0;if(n==='MIN')return a.length?Math.min(...a):0;if(n==='MAX')return a.length?Math.max(...a):0;if(n==='COUNT')return a.length}const r=e.replace(/([A-Z]+\d+)/gi,x=>{const p=parseRef(x);return p?String(val(p.r,p.c,seen)):'0'});if(!/^[0-9+\-*/().%\s]+$/.test(r))return'#ERROR!';try{return Function('return ('+r+')')()}catch{return'#ERROR!'}}
function renderTabs(){const t=$('tabs');if(!t)return;t.innerHTML='';sheets.forEach((s,i)=>{const b=document.createElement('button');b.textContent=s.name;b.className=i===activeSheet?'active':'';b.onclick=()=>{current().data=data();activeSheet=i;render();save()};b.ondblclick=()=>{const n=prompt('Rename sheet',s.name);if(n?.trim()){remember();s.name=n.trim();renderTabs();save()}};t.appendChild(b)});const a=document.createElement('button');a.textContent='+ Sheet';a.onclick=()=>{remember();current().data=data();sheets.push({name:'Sheet '+(sheets.length+1),data:[]});activeSheet=sheets.length-1;render();save()};t.appendChild(a)}
function render(){const d=data();thead.innerHTML='<tr><th>#</th>'+Array.from({length:cols},(_,c)=>'<th>'+colName(c)+'</th>').join('')+'</tr>';tbody.innerHTML='';for(let r=0;r<rows;r++){const tr=document.createElement('tr'),n=document.createElement('td');n.textContent=r+1;tr.append(n);for(let c=0;c<cols;c++){const td=document.createElement('td');td.contentEditable='true';td.dataset.r=r;td.dataset.c=c;td.textContent=d[r][c]??'';td.onclick=()=>{selected=td;updateFormula()};td.oninput=()=>{current().data[r][c]=td.textContent;save()};td.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();cell(r+1,c)?.focus()}};tr.append(td)}tbody.append(tr)}renderTabs();applyFilter();updateFormula()}
function updateFormula(){if(!selected)return;if($('cellName'))$('cellName').textContent=colName(+selected.dataset.c)+(+selected.dataset.r+1);if($('formulaInput'))$('formulaInput').value=current().data?.[+selected.dataset.r]?.[+selected.dataset.c]??''}
function applyFilter(){const q=filterText.toLowerCase();[...tbody.rows].forEach(r=>r.style.display=!q||[...r.cells].slice(1).some(c=>c.textContent.toLowerCase().includes(q))?'':'none')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCSV(){download(current().name+'.csv',data().map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function importCSV(file){const fr=new FileReader();fr.onload=()=>{remember();const lines=String(fr.result).split(/\r?\n/).filter(Boolean);const d=lines.map(line=>{const o=[];let x='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){x+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){o.push(x);x=''}else x+=ch}o.push(x);return o});cols=Math.max(1,...d.map(r=>r.length));rows=Math.max(20,d.length);current().data=d;render();save()};fr.readAsText(file)}
function removeRow(){if(!selected||rows<=1)return;remember();current().data.splice(+selected.dataset.r,1);rows--;render();save()}
function removeCol(){if(!selected||cols<=1)return;remember();current().data.forEach(r=>r.splice(+selected.dataset.c,1));cols--;render();save()}
$('newBtn')?.addEventListener('click',()=>{remember();sheets=[{name:'Sheet 1',data:[]}];rows=20;cols=8;activeSheet=0;render();save()});$('undoBtn')?.addEventListener('click',()=>history.length&&(future.push(snapshot()),restore(history.pop())));$('redoBtn')?.addEventListener('click',()=>future.length&&(history.push(snapshot()),restore(future.pop())));$('addRowBtn')?.addEventListener('click',()=>{remember();rows++;data();render();save()});$('addColBtn')?.addEventListener('click',()=>{remember();cols++;data();render();save()});$('delRowBtn')?.addEventListener('click',removeRow);$('delColBtn')?.addEventListener('click',removeCol);$('exportCsvBtn')?.addEventListener('click',exportCSV);$('importCsvBtn')?.addEventListener('click',()=>$('csvInput')?.click());$('csvInput')?.addEventListener('change',e=>e.target.files[0]&&importCSV(e.target.files[0]));$('saveProjectBtn')?.addEventListener('click',()=>download('nexauren-spreadsheet.nexa',snapshot(),'application/json'));$('loadProjectBtn')?.addEventListener('click',()=>$('projectInput')?.click());$('projectInput')?.addEventListener('change',e=>{if(e.target.files[0]){const f=new FileReader();f.onload=()=>restore(f.result);f.readAsText(e.target.files[0])}});$('resetBtn')?.addEventListener('click',()=>{if(confirm('Reset this spreadsheet?')){remember();localStorage.removeItem(STORE);sheets=[{name:'Sheet 1',data:[]}];rows=20;cols=8;activeSheet=0;render();save()}});$('search')?.addEventListener('input',e=>{filterText=e.target.value;applyFilter()});$('filterBtn')?.addEventListener('click',applyFilter);$('sortBtn')?.addEventListener('click',()=>{if(!selected)return;remember();const c=+selected.dataset.c;current().data=data().sort((a,b)=>String(a[c]??'').localeCompare(String(b[c]??''),undefined,{numeric:true}));render();save()});$('formulaInput')?.addEventListener('change',()=>{if(!selected)return;remember();current().data[+selected.dataset.r][+selected.dataset.c]=$('formulaInput').value;render();save()});
document.querySelectorAll('[data-format]').forEach(b=>b.addEventListener('click',()=>{if(selected){selected.focus();document.execCommand(b.dataset.format);current().data[+selected.dataset.r][+selected.dataset.c]=selected.innerHTML;save()}}));$('align')?.addEventListener('change',e=>selected&&(selected.style.textAlign=e.target.value));$('bgColor')?.addEventListener('input',e=>selected&&(selected.style.background=e.target.value));$('borderBtn')?.addEventListener('click',()=>selected&&(selected.style.border='1px solid #888'));$('numberFormat')?.addEventListener('change',e=>{if(!selected)return;const n=Number(selected.textContent.replace(/[^0-9.-]/g,''));if(!Number.isFinite(n))return;if(e.target.value==='currency')selected.textContent=n.toLocaleString(undefined,{style:'currency',currency:'USD'});if(e.target.value==='percent')selected.textContent=(n*100).toFixed(2)+'%';current().data[+selected.dataset.r][+selected.dataset.c]=selected.textContent;save()});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undoBtn')?.click()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();$('redoBtn')?.click()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();$('search')?.focus()}});window.addEventListener('beforeunload',save);render();save();
})();
