(() => {
  if (window.__NEXA_AI_WIDGET__) return;
  window.__NEXA_AI_WIDGET__ = true;
  const root = document.createElement('div');
  root.innerHTML = `
    <button class="nexa-launcher" aria-label="Open Nexa AI" aria-expanded="false"><span class="nexa-orb">✦</span><span>Nexa AI</span></button>
    <div class="nexa-panel" hidden aria-hidden="true">
      <div class="nexa-head"><div><strong>Nexa AI</strong><small id="nexa-plan">AI assistant</small></div><div class="nexa-head-actions"><button type="button" data-action="new" title="New chat">＋</button><button type="button" data-action="close" title="Close">×</button></div></div>
      <div class="nexa-toolbar"><button type="button" class="nexa-toggle" data-toggle="web">🌐 Web</button><button type="button" class="nexa-toggle" data-toggle="analysis">✦ Analysis</button><span id="nexa-usage">Loading limits…</span></div>
      <div class="nexa-messages" id="nexa-messages"><div class="nexa-empty"><div class="nexa-empty-orb">✦</div><h3>How can I help?</h3><p>Ask me to explain, write, research, solve, create, or find a Nexauren tool.</p></div></div>
      <div class="nexa-suggestions"><button type="button">Find an image tool</button><button type="button">Create an image of a futuristic African city</button><button type="button">Help me write</button></div>
      <form class="nexa-form"><textarea id="nexa-input" rows="1" maxlength="12000" placeholder="Message Nexa AI…"></textarea><button type="submit" aria-label="Send">➤</button></form>
      <div class="nexa-foot"><span>Powered by Nexauren AI</span><a href="/billing/">Plans & credits</a></div>
    </div>`;
  document.body.appendChild(root);
  const launcher=root.querySelector('.nexa-launcher'), panel=root.querySelector('.nexa-panel'), messages=root.querySelector('#nexa-messages'), input=root.querySelector('#nexa-input'), form=root.querySelector('.nexa-form'), usage=root.querySelector('#nexa-usage'), plan=root.querySelector('#nexa-plan');
  let conversationId=null, web=false, analysis=false, busy=false, authenticated=false;
  const esc=s=>String(s||'').replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]));
  const md=s=>esc(s).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>');
  function setOpen(open){panel.hidden=!open;panel.setAttribute('aria-hidden',String(!open));launcher.classList.toggle('is-open',open);launcher.setAttribute('aria-expanded',String(open));if(open)input.focus();}
  async function open(){
    try{
      const r=await fetch('/api/auth/me',{credentials:'include',cache:'no-store'}); const d=await r.json().catch(()=>({}));
      authenticated=!!d?.authenticated;
    }catch{authenticated=false;}
    setOpen(true);
    if(authenticated) loadLimits();
    else { plan.textContent='Sign in required'; usage.textContent=''; add('assistant','Please sign in to your Nexauren account before using Nexa AI.'); }
  }
  function close(){setOpen(false);}
  function add(role,text,loading=false){const el=document.createElement('div');el.className='nexa-msg '+role+(loading?' loading':'');el.innerHTML=loading?'<span></span><span></span><span></span>':md(text);messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el;}
  function addImageAction(action){
    if(!action?.success || !action.result?.image){ if(action?.error) add('assistant','I could not complete the image action: '+action.error); return; }
    const result=action.result, box=document.createElement('div'); box.className='nexa-agent-result';
    const img=document.createElement('img'); img.src=result.image; img.alt=result.prompt||'Nexa AI generated image'; img.loading='lazy';
    const caption=document.createElement('div'); caption.className='nexa-agent-caption'; caption.textContent='Image generated by Nexa AI';
    const link=document.createElement('a'); link.href=result.image; link.download=result.filename||'nexauren-image.jpg'; link.textContent='Download image'; link.className='nexa-agent-download';
    box.appendChild(img); box.appendChild(caption); box.appendChild(link); messages.appendChild(box); messages.scrollTop=messages.scrollHeight;
  }
  function clear(){messages.innerHTML='<div class="nexa-empty"><div class="nexa-empty-orb">✦</div><h3>New conversation</h3><p>Ask Nexa AI anything you need.</p></div>';conversationId=null;}
  async function loadLimits(){try{const r=await fetch('/api/nexa-ai',{credentials:'include',cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Login required');authenticated=true;plan.textContent=(d.plan||'free').toUpperCase();usage.textContent=`${d.used?.messages||0}/${d.limits?.messages||0} messages`;web=(d.plan!=='free'&&web);document.querySelectorAll('[data-toggle]').forEach(b=>b.disabled=(b.dataset.toggle==='web'&&d.plan==='free')||(b.dataset.toggle==='analysis'&&d.plan==='free'));}catch(e){authenticated=false;plan.textContent='Sign in required';usage.textContent='';}}
  async function send(){if(busy)return;const text=input.value.trim();if(!text)return;if(!authenticated){add('assistant','Please sign in to your Nexauren account before using Nexa AI.');return;}busy=true;input.value='';add('user',text);const loading=add('assistant','',true);try{const r=await fetch('/api/nexa-ai/chat',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,conversation_id:conversationId,web,analysis,tools:true,agent:true})});const d=await r.json();loading.remove();if(!r.ok){add('assistant',r.status===401?'Please sign in to use Nexa AI.':(d.error||'Something went wrong.'));if(r.status===401||d.code==='feature_plan_required')loadLimits();return;}conversationId=d.conversation_id;add('assistant',d.answer);if(d.agent_action)addImageAction(d.agent_action);if(d.web_sources?.length){const box=document.createElement('div');box.className='nexa-sources';box.innerHTML='<strong>Sources</strong>'+d.web_sources.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)}</a>`).join('');messages.appendChild(box);}if(d.tools?.length){const box=document.createElement('div');box.className='nexa-tools-found';box.innerHTML='<strong>Nexauren tools</strong>'+d.tools.map(x=>`<a href="/tools/${esc(x.slug)}/">${esc(x.name)}</a>`).join('');messages.appendChild(box);}loadLimits();}catch(e){loading.remove();add('assistant','I could not reach Nexa AI right now. Please try again.');}finally{busy=false;input.focus();}}
  launcher.onclick=open;root.querySelector('[data-action="close"]').onclick=close;root.querySelector('[data-action="new"]').onclick=clear;root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{if(b.disabled)return;if(b.dataset.toggle==='web')web=!web;else analysis=!analysis;b.classList.toggle('active',b.dataset.toggle==='web'?web:analysis);});root.querySelectorAll('.nexa-suggestions button').forEach(b=>b.onclick=()=>{input.value=b.textContent;input.focus();});form.onsubmit=e=>{e.preventDefault();send();};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}};
  setOpen(false);
})();
