(() => {
  if (window.__NEXA_AI_WIDGET__) return;
  window.__NEXA_AI_WIDGET__ = true;
  const root=document.createElement('div');
  root.innerHTML=`
  <button class="nexa-launcher" aria-label="Open Nexa AI" aria-expanded="false"><span class="nexa-orb">✦</span><span>Nexa AI</span></button>
  <div class="nexa-panel" hidden aria-hidden="true">
    <aside class="nexa-menu" aria-label="Nexa menu">
      <div class="nexa-menu-head"><strong>Nexa AI</strong><button type="button" data-action="menu-close">×</button></div>
      <button type="button" class="nexa-new-chat" data-action="new">＋ New conversation</button>
      <div class="nexa-account-card" id="nexa-account-card"><strong>Account</strong><span>Loading account…</span></div>
      <div class="nexa-menu-links"><a href="/account/">👤 My account</a><a href="/billing/#credits">💳 Buy credits</a><a href="/billing/#plans">⭐ Update plan</a><a href="/tools/">🧰 Nexauren tools</a></div>
      <label class="nexa-history-search"><span>⌕</span><input id="nexa-history-search" type="search" placeholder="Search conversations…" autocomplete="off"></label>
      <div class="nexa-history-label">Conversation history</div><div class="nexa-history" id="nexa-history"><div class="nexa-history-empty">No conversations yet.</div></div>
    </aside><div class="nexa-backdrop" data-action="menu-close"></div>
    <div class="nexa-main">
      <div class="nexa-head"><div class="nexa-title-wrap"><button type="button" class="nexa-menu-button" data-action="menu-open" aria-label="Open Nexa menu">☰</button><div><strong>Nexa AI</strong><small id="nexa-plan">AI assistant</small></div></div><div class="nexa-head-actions"><button type="button" data-action="new">＋</button><button type="button" data-action="close">×</button></div></div>
      <div class="nexa-toolbar"><button type="button" class="nexa-toggle" data-toggle="web">🌐 Web</button><button type="button" class="nexa-toggle" data-toggle="analysis">✦ Analysis</button><span id="nexa-usage">Loading limits…</span></div>
      <div class="nexa-conversation-label" id="nexa-conversation-label">New conversation</div>
      <div class="nexa-messages" id="nexa-messages"><div class="nexa-empty"><div class="nexa-empty-orb">✦</div><h3>How can I help?</h3><p>I can operate existing Nexauren tools, use your account context and help you complete tasks.</p></div></div>
      <div class="nexa-suggestions"><button type="button">Compress this image</button><button type="button">Resize this image</button><button type="button">Show my credits</button></div>
      <form class="nexa-form"><input id="nexa-file" type="file" hidden><button type="button" class="nexa-attach">＋</button><textarea id="nexa-input" rows="1" maxlength="12000" placeholder="Message Nexa AI…"></textarea><button type="submit">➤</button></form>
      <div class="nexa-attachment" id="nexa-attachment" hidden></div><div class="nexa-foot"><span>Powered by Nexauren AI</span><a href="/billing/">Plans & credits</a></div>
    </div></div>`;
  document.body.appendChild(root);
  const q=s=>root.querySelector(s),launcher=q('.nexa-launcher'),panel=q('.nexa-panel'),menu=q('.nexa-menu'),backdrop=q('.nexa-backdrop'),messages=q('#nexa-messages'),input=q('#nexa-input'),form=q('.nexa-form'),usage=q('#nexa-usage'),plan=q('#nexa-plan'),fileInput=q('#nexa-file'),attach=q('.nexa-attach'),attachment=q('#nexa-attachment'),history=q('#nexa-history'),historySearch=q('#nexa-history-search'),conversationLabel=q('#nexa-conversation-label'),accountCard=q('#nexa-account-card');
  let conversationId=null,web=false,analysis=false,busy=false,authenticated=false,attachedFile=null,conversations=[];
  const esc=s=>String(s??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]));
  const md=s=>esc(s).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>');
  function setOpen(v){panel.hidden=!v;panel.setAttribute('aria-hidden',String(!v));launcher.setAttribute('aria-expanded',String(v));launcher.classList.toggle('is-open',v);if(!v)setMenu(false);else input.focus();}
  function setMenu(v){menu.classList.toggle('is-open',v);backdrop.classList.toggle('is-open',v);panel.classList.toggle('menu-open',v);if(v){loadConversations();loadAccount();}}
  async function open(){try{const r=await fetch('/api/auth/me',{credentials:'include',cache:'no-store'}),d=await r.json().catch(()=>({}));authenticated=!!d?.authenticated;}catch{authenticated=false;}setOpen(true);if(authenticated){loadLimits();loadConversations();loadAccount();}else{plan.textContent='Sign in required';usage.textContent='';add('assistant','Please sign in to your Nexauren account before using Nexa AI.');}}
  function close(){setOpen(false);}
  function add(role,text,loading=false){const el=document.createElement('div');el.className='nexa-msg '+role+(loading?' loading':'');el.innerHTML=loading?'<span></span><span></span><span></span>':md(text);messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el;}
  function addImageAction(a){if(!a?.success){if(a?.error)add('assistant','I could not complete the image action: '+a.error);return;}const r=a.result,b=document.createElement('div');b.className='nexa-agent-result';const i=document.createElement('img');i.src=r.image;i.alt=r.prompt||'Generated image';const l=document.createElement('a');l.href=r.image;l.download=r.filename||'nexauren-image.jpg';l.textContent='Download image';l.className='nexa-agent-download';b.append(i,l);messages.appendChild(b);messages.scrollTop=messages.scrollHeight;}
  function addToolResult(tool,r){const b=document.createElement('div');b.className='nexa-agent-result';const t=document.createElement('strong');t.textContent=r.filename||`${tool.name} result`;const m=document.createElement('div');m.className='nexa-agent-caption';m.textContent=`Processed by ${tool.name}`;const l=document.createElement('a');l.href=r.url;l.download=r.filename||'nexauren-result';l.textContent='Download result';l.className='nexa-agent-download';b.append(t,m,l);if(r.type?.startsWith('image/')){const i=document.createElement('img');i.src=r.url;i.alt=r.filename||'Processed result';b.insertBefore(i,t);}messages.appendChild(b);messages.scrollTop=messages.scrollHeight;}
  function clear(){messages.innerHTML='<div class="nexa-empty"><div class="nexa-empty-orb">✦</div><h3>New conversation</h3><p>Ask Nexa AI anything you need.</p></div>';conversationId=null;conversationLabel.textContent='New conversation';selectFile(null);setMenu(false);renderHistory();}
  function selectFile(f){attachedFile=f||null;if(!f){attachment.hidden=true;attachment.textContent='';fileInput.value='';return;}attachment.hidden=false;attachment.innerHTML=`<span>📎 ${esc(f.name)} · ${(f.size/1024/1024).toFixed(2)} MB</span><button type="button">×</button>`;attachment.querySelector('button').onclick=()=>selectFile(null);}
  function formatDate(ts){const d=new Date(Number(ts||0)*1000);if(!Number.isFinite(d.getTime()))return '';const now=new Date();return d.toDateString()===now.toDateString()?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString([],{day:'2-digit',month:'short'});}
  function renderHistory(filter=''){const term=String(filter).trim().toLowerCase(),list=conversations.filter(c=>!term||String(c.title||'').toLowerCase().includes(term));if(!list.length){history.innerHTML=`<div class="nexa-history-empty">${term?'No matching conversations.':'No conversations yet.'}</div>`;return;}history.innerHTML='';list.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='nexa-history-item'+(c.id===conversationId?' active':'');const s=document.createElement('span');s.textContent=c.title||'New conversation';const d=document.createElement('small');d.textContent=formatDate(c.updated_at);b.append(s,d);b.onclick=()=>loadConversation(c.id);history.appendChild(b);});}
  async function loadConversations(){if(!authenticated)return;try{const r=await fetch('/api/nexa-ai/conversations',{credentials:'include',cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw 0;conversations=Array.isArray(d.conversations)?d.conversations:[];renderHistory(historySearch.value);}catch{history.innerHTML='<div class="nexa-history-empty">History unavailable.</div>';}}
  async function loadConversation(id){if(!id||busy)return;try{const r=await fetch('/api/nexa-ai/history?id='+encodeURIComponent(id),{credentials:'include',cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw 0;conversationId=d.conversation?.id||id;conversationLabel.textContent=d.conversation?.title||'Conversation';messages.innerHTML='';(d.messages||[]).forEach(m=>add(m.role==='user'?'user':'assistant',m.content));setMenu(false);renderHistory(historySearch.value);input.focus();}catch{add('assistant','I could not load that conversation. Please try again.');}}
  async function loadAccount(){if(!authenticated)return;try{const r=await fetch('/api/nexa-ai/account',{credentials:'include',cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw 0;const a=d.account||{};accountCard.innerHTML=`<strong>${esc(a.plan_name||d.plan||'Free')}</strong><span>💳 ${Number(a.balance||0)} credits</span><span>${Number(a.credits_per_cycle||0)} credits / cycle</span><a href="/billing/">Manage billing →</a>`;}catch{accountCard.innerHTML='<strong>Account</strong><span>Unable to load account.</span>';}}
  function chooseRunButton(doc){return doc.querySelector('#run,#process,#execute,[data-action="run"],button[type="submit"]')||[...doc.querySelectorAll('button')].find(b=>/(compress|convert|resize|crop|merge|split|trim|process|generate|export|run|execute|save|create)/i.test(b.textContent||''));}
  async function executeExistingTool(a,file){const tool=a?.tool;if(!tool?.url)throw new Error('Nexauren tool route is unavailable.');const frame=document.createElement('iframe');frame.setAttribute('aria-hidden','true');frame.style.cssText='position:fixed;width:1px;height:1px;opacity:0;pointer-events:none;left:-20px;top:-20px;border:0';document.body.appendChild(frame);try{return await new Promise((resolve,reject)=>{let done=false,timer;const finish=x=>{if(done)return;done=true;clearTimeout(timer);resolve(x)};frame.onload=()=>{try{const doc=frame.contentDocument,w=frame.contentWindow;if(!doc||!w)throw new Error('Unable to open the Nexauren tool.');const nativeClick=w.HTMLAnchorElement.prototype.click;w.HTMLAnchorElement.prototype.click=function(){const href=this.href||'';const name=this.download||'nexauren-result';if(href&&/^blob:|^https?:/i.test(href))finish({url:href,filename:name,type:this.dataset?.type||''});return nativeClick.call(this)};if(file){const inputEl=doc.querySelector('input[type="file"]');if(!inputEl)throw new Error(`${tool.name} does not accept file uploads from Nexa yet.`);const dt=new DataTransfer();dt.items.add(file);inputEl.files=dt.files;inputEl.dispatchEvent(new Event('change',{bubbles:true}));}const textEl=doc.querySelector('textarea,input[type="text"]');if(!file&&textEl&&!textEl.value){textEl.value=a.message||'';textEl.dispatchEvent(new Event('input',{bubbles:true}));}const run=chooseRunButton(doc);if(!run)throw new Error(`Nexa could not find the action control for ${tool.name}.`);run.click();timer=setTimeout(()=>reject(new Error(`The ${tool.name} action did not produce a downloadable result.`)),90000);}catch(e){reject(e);}};frame.src=tool.url;});}finally{setTimeout(()=>frame.remove(),1000);}}
  async function handleToolAction(a){if(!a?.success||a.type!=='tool_execution')return;const tool=a.tool;if(a.requires_upload&&!attachedFile){add('assistant',`I found **${tool.name}**. Attach the file you want me to process and send the request again.`);return;}const status=add('assistant',`Using **${tool.name}** now…`);try{const result=await executeExistingTool(a,attachedFile);status.remove();add('assistant',`Done. I used the existing **${tool.name}** tool and brought the result here.`);addToolResult(tool,result);selectFile(null);}catch(e){status.remove();add('assistant',`I found **${tool.name}**, but its action could not be completed: ${e.message||'Unknown error'}`);}}
  async function loadLimits(){try{const r=await fetch('/api/nexa-ai',{credentials:'include',cache:'no-store'}),d=await r.json();if(!r.ok)throw 0;authenticated=true;plan.textContent=(d.plan||'free').toUpperCase();usage.textContent=`${d.used?.messages||0}/${d.limits?.messages||0} messages`;root.querySelectorAll('[data-toggle]').forEach(b=>b.disabled=(b.dataset.toggle==='web'&&d.plan==='free')||(b.dataset.toggle==='analysis'&&d.plan==='free'));}catch{authenticated=false;plan.textContent='Sign in required';usage.textContent='';}}
  function addAccountAction(a){if(!a?.url)return;const b=document.createElement('div');b.className='nexa-account-action';const t=document.createElement('strong');t.textContent=a.label||'Open Nexauren';const l=document.createElement('a');l.href=a.url;l.textContent='Open in Nexauren →';b.append(t,l);messages.appendChild(b);messages.scrollTop=messages.scrollHeight;}
  async function send(){if(busy)return;const text=input.value.trim();if(!text)return;if(!authenticated){add('assistant','Please sign in to your Nexauren account before using Nexa AI.');return;}busy=true;input.value='';add('user',attachedFile?`${text} 📎 ${attachedFile.name}`:text);const loading=add('assistant','',true);try{const r=await fetch('/api/nexa-ai/chat',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,conversation_id:conversationId,web,analysis,tools:true,agent:true})}),d=await r.json();loading.remove();if(!r.ok){add('assistant',r.status===401?'Please sign in to use Nexa AI.':(d.error||'Something went wrong.'));if(r.status===401)loadLimits();return;}conversationId=d.conversation_id;conversationLabel.textContent=d.title||'Conversation';add('assistant',d.answer);if(d.account_action)addAccountAction(d.account_action);if(d.agent_action?.type==='image_generation')addImageAction(d.agent_action);if(d.agent_action?.type==='tool_execution')await handleToolAction(d.agent_action);if(d.web_sources?.length){const b=document.createElement('div');b.className='nexa-sources';b.innerHTML='<strong>Sources</strong>'+d.web_sources.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title)}</a>`).join('');messages.appendChild(b);}await loadLimits();await loadConversations();await loadAccount();}catch{loading.remove();add('assistant','I could not reach Nexa AI right now. Please try again.');}finally{busy=false;input.focus();}}
  launcher.onclick=open;q('[data-action="close"]').onclick=close;q('[data-action="menu-open"]').onclick=()=>setMenu(true);root.querySelectorAll('[data-action="menu-close"]').forEach(b=>b.onclick=()=>setMenu(false));root.querySelectorAll('[data-action="new"]').forEach(b=>b.onclick=clear);root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{if(b.disabled)return;if(b.dataset.toggle==='web')web=!web;else analysis=!analysis;b.classList.toggle('active',b.dataset.toggle==='web'?web:analysis);});root.querySelectorAll('.nexa-suggestions button').forEach(b=>b.onclick=()=>{input.value=b.textContent;input.focus();});attach.onclick=()=>fileInput.click();fileInput.onchange=()=>selectFile(fileInput.files?.[0]||null);historySearch.oninput=()=>renderHistory(historySearch.value);form.onsubmit=e=>{e.preventDefault();send();};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}};setOpen(false);
})();
