const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[];
async function api(url,options={}){const r=await fetch(url,{credentials:'include',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function money(minor,currency='USD'){return Number(minor)===0?'Free':new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(minor||0)/100)}
async function loadCategories(){const d=await api('/api/store/categories');$('category').innerHTML='<option value="">Select category</option>'+d.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}
async function loadProducts(){const d=await api('/api/store/admin/products?ts='+Date.now());products=Array.isArray(d.products)?d.products:[];$('count').textContent=`${products.length} product${products.length===1?'':'s'} in the Marketplace database`;$('products').innerHTML=products.length?products.map(p=>`<tr><td><strong>${esc(p.icon||'📦')} ${esc(p.name)}</strong><small style="display:block">${esc(p.slug)}</small></td><td>${esc(p.category)}</td><td>${money(p.price_minor,p.currency)}</td><td>${esc(p.format)}</td><td>${Number(p.enabled)?'🟢 Published':'⚪ Hidden'}</td><td><button class="refresh" type="button" data-edit="${esc(p.id)}">Edit</button> <button class="refresh" type="button" data-delete="${esc(p.id)}">Delete</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No real products yet. Create the first one above.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete))}
function reset(){ $('product-id').value='';$('product-form').reset();$('price').value='0';$('rating').value='0';$('format').value='DIGITAL';$('icon').value='📦';$('sort-order').value='0';$('enabled').checked=true;$('featured').checked=false;$('form-title').textContent='Add product';$('save').textContent='Create product';$('status').className='result';$('status').textContent=''}
function edit(id){const p=products.find(x=>x.id===id);if(!p)return;$('product-id').value=p.id;$('name').value=p.name||'';$('slug').value=p.slug||'';$('category').value=p.category_id||'';$('format').value=p.format||'DIGITAL';$('price').value=(Number(p.price_minor||0)/100).toFixed(2);$('rating').value=Number(p.rating||0);$('icon').value=p.icon||'📦';$('tag').value=p.tag||'';$('sort-order').value=Number(p.sort_order||0);$('featured').checked=Number(p.featured)===1;$('enabled').checked=Number(p.enabled)===1;$('description').value=p.description||'';$('metadata').value=p.metadata_json||'';$('form-title').textContent='Edit product';$('save').textContent='Save changes';window.scrollTo({top:0,behavior:'smooth'})}
async function saveProduct(e){e.preventDefault();const id=$('product-id').value.trim();const metadata=$('metadata').value.trim();if(metadata){try{JSON.parse(metadata)}catch{ $('status').className='result error';$('status').textContent='Metadata JSON is invalid.';return}}const payload={name:$('name').value.trim(),slug:$('slug').value.trim(),category_id:$('category').value,format:$('format').value.trim(),price_minor:Math.round(Number($('price').value||0)*100),currency:'USD',rating:Number($('rating').value||0),icon:$('icon').value.trim()||'📦',tag:$('tag').value.trim(),sort_order:Number($('sort-order').value||0),featured:$('featured').checked,enabled:$('enabled').checked,description:$('description').value.trim(),metadata_json:metadata||'{}'};$('save').disabled=true;$('status').className='result';$('status').textContent=id?'Saving changes…':'Creating product…';try{await api(id?`/api/store/admin/products/${encodeURIComponent(id)}`:'/api/store/admin/products',{method:id?'PUT':'POST',body:JSON.stringify(payload)});$('status').className='result success';$('status').textContent=id?'Product updated successfully.':'Product created successfully.';reset();await loadProducts()}catch(err){$('status').className='result error';$('status').textContent=err.message||'Unable to save product.'}finally{$('save').disabled=false}}
async function removeProduct(id){if(!confirm('Delete this Store product permanently?'))return;try{await api(`/api/store/admin/products/${encodeURIComponent(id)}`,{method:'DELETE'});await loadProducts()}catch(err){alert(err.message||'Unable to delete product.')}}
$('product-form').addEventListener('submit',saveProduct);$('cancel').addEventListener('click',reset);(async()=>{try{await loadCategories();await loadProducts()}catch(err){$('status').className='result error';$('status').textContent=err.message||'Unable to load Store administration.'}})();