const state={products:[],categories:[],q:'',category:'',price:'',format:'',rating:'',sort:'relevance',cart:JSON.parse(localStorage.getItem('nx_store_cart')||'[]'),wish:JSON.parse(localStorage.getItem('nx_store_wish')||'[]')};
const $=s=>document.querySelector(s);
const API='/api/store/';
function money(v,currency='USD'){return Number(v)===0?'Free':new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(v)||0)}
function save(){localStorage.setItem('nx_store_cart',JSON.stringify(state.cart));localStorage.setItem('nx_store_wish',JSON.stringify(state.wish));updateCounts()}
function updateCounts(){$('#cartCount').textContent=state.cart.length;$('#wishlistCount').textContent=state.wish.length}
function renderCategories(){const g=$('#categoryGrid');g.innerHTML=state.categories.map(c=>`<a class="category-card" href="#store" data-category="${c.id}"><span class="category-icon">${c.icon||'📦'}</span><strong>${c.name}</strong><span>${c.description||''}</span></a>`).join('');g.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{state.category=a.dataset.category;$('#categoryFilter').value=state.category;loadProducts()})}
function categoryName(id){return state.categories.find(c=>c.id===id)?.name||id}
function card(x){const wished=state.wish.includes(x.id);return `<article class="product-card"><div class="product-art">${x.icon||'📦'}</div><div class="product-body"><div class="product-meta"><span>${x.tag||categoryName(x.categoryId)}</span><span>★ ${Number(x.rating||0).toFixed(1)}</span></div><h3>${x.name}</h3><p>${x.desc||''}</p><div class="product-foot"><span class="price ${x.price===0?'free':''}">${money(x.price,x.currency)}</span><div class="mini-actions"><button data-product="${x.id}" aria-label="View ${x.name}">View</button><button data-wish="${x.id}" aria-label="Wishlist">${wished?'♥':'♡'}</button><button data-add="${x.id}" aria-label="Add to cart">+</button></div></div></div></article>`}
function render(products=state.products){const p=products;$('#resultSummary').textContent=state.q?`${p.length} result${p.length===1?'':'s'} for “${state.q}”`:`${p.length} products available`;$('#productGrid').innerHTML=p.map(card).join('');$('#emptyState').hidden=p.length>0;$('#activeFilters').innerHTML=[state.q?`Search: ${state.q}`:'',state.category?categoryName(state.category):'',state.price?({free:'Free',under5:'Under $5','5to15':'$5–$15',over15:'Over $15'}[state.price]||state.price):'',state.format,state.rating?`${state.rating}★+`:'' ].filter(Boolean).map(x=>`<span class="chip">${x}</span>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(b.dataset.wish));document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product))}
async function loadProducts(){
  $('#resultSummary').textContent='Loading products…';
  const q=new URLSearchParams({limit:'48',sort:state.sort});
  if(state.q)q.set('q',state.q);if(state.category)q.set('category',state.category);if(state.price)q.set('price',state.price);if(state.format)q.set('format',state.format);if(state.rating)q.set('rating',state.rating);
  try{const r=await fetch(API+'products?'+q.toString(),{credentials:'include',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Catalog request failed (${r.status})`);const d=await r.json();state.products=Array.isArray(d.products)?d.products:[];render()}catch(err){console.error('Store catalog error',err);state.products=[];$('#resultSummary').textContent='Unable to load the Store catalog.';render([]);toast('Could not load products')}}
async function loadCatalog(){
  try{const r=await fetch(API+'categories',{credentials:'include',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Categories request failed (${r.status})`);const d=await r.json();state.categories=Array.isArray(d.categories)?d.categories:[];const select=$('#categoryFilter');select.innerHTML='<option value="">All categories</option>'+state.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');renderCategories();await loadProducts()}catch(err){console.error('Store categories error',err);$('#resultSummary').textContent='Unable to connect to the Store database.';toast('Store database is not available')}}
function addCart(id){if(!state.products.some(x=>x.id===id)&&!state.cart.includes(id))return;if(!state.cart.includes(id))state.cart.push(id);save();toast('Added to cart');openDrawer('cartDrawer');renderCart()}
function toggleWish(id){const i=state.wish.indexOf(id);if(i>=0){state.wish.splice(i,1);toast('Removed from wishlist')}else{state.wish.push(id);toast('Saved to wishlist')}save();render()}
function findProduct(id){return state.products.find(x=>x.id===id)}
function renderCart(){const b=$('#cartBody');const items=state.cart.map(findProduct).filter(Boolean);b.innerHTML=items.length?items.map(x=>`<div class="drawer-item"><div class="art">${x.icon||'📦'}</div><div><strong>${x.name}</strong><span>${money(x.price,x.currency)}</span><br><button data-remove="${x.id}">Remove</button></div></div>`).join(''):'<div class="empty-state"><strong>Your cart is empty.</strong><span>Add products you want to purchase.</span></div>';const total=items.reduce((s,x)=>s+Number(x.price||0),0);$('#cartTotal').textContent=money(total,items[0]?.currency||'USD');b.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(id=>id!==b.dataset.remove);save();renderCart()})}
function renderWish(){const b=$('#wishlistBody');const items=state.wish.map(findProduct).filter(Boolean);b.innerHTML=items.length?items.map(x=>`<div class="drawer-item"><div class="art">${x.icon||'📦'}</div><div><strong>${x.name}</strong><span>${money(x.price,x.currency)}</span><br><button data-wremove="${x.id}">Remove</button></div></div>`).join(''):'<div class="empty-state"><strong>Your wishlist is empty.</strong><span>Save products to find them later.</span></div>';b.querySelectorAll('[data-wremove]').forEach(b=>b.onclick=()=>{state.wish=state.wish.filter(id=>id!==b.dataset.wremove);save();renderWish();render()})}
function openDrawer(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false');$('#drawerBackdrop').classList.add('open')}
function closeDrawers(){document.querySelectorAll('.drawer').forEach(x=>x.classList.remove('open'));$('#drawerBackdrop').classList.remove('open')}
function showProduct(id){const x=findProduct(id);if(!x)return;alert(`${x.name}\n\n${x.desc||''}\n\n${money(x.price,x.currency)}\n★ ${Number(x.rating||0).toFixed(1)}\n\nSecure checkout will be connected to verified Store payments.`)}
let toastTimer;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1800)}
function reset(){state.q=state.category=state.price=state.format=state.rating='';$('#heroSearch').value='';$('#categoryFilter').value='';$('#priceFilter').value='';$('#formatFilter').value='';$('#ratingFilter').value='';loadProducts()}
function init(){
  ['categoryFilter','priceFilter','formatFilter','ratingFilter','sortFilter'].forEach(id=>$('#'+id).onchange=e=>{const map={categoryFilter:'category',priceFilter:'price',formatFilter:'format',ratingFilter:'rating',sortFilter:'sort'};state[map[id]]=e.target.value;loadProducts()});
  $('#heroSearchBtn').onclick=()=>{state.q=$('#heroSearch').value.trim();location.hash='store';loadProducts()};$('#heroSearch').onkeydown=e=>{if(e.key==='Enter')$('#heroSearchBtn').click()};$('#clearFilters').onclick=reset;$('#emptyClear').onclick=reset;$('#cartBtn').onclick=()=>{renderCart();openDrawer('cartDrawer')};$('#wishlistBtn').onclick=()=>{renderWish();openDrawer('wishlistDrawer')};$('#drawerBackdrop').onclick=closeDrawers;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDrawers);$('#checkoutBtn').onclick=()=>toast('Checkout will use verified Nexauren Store payments.');$('#mobileMenu').onclick=()=>$('#mobileNav').classList.toggle('open');document.querySelectorAll('[data-sort]').forEach(a=>a.onclick=()=>{state.sort=a.dataset.sort;$('#sortFilter').value=state.sort;loadProducts()});document.querySelectorAll('[data-price]').forEach(a=>a.onclick=()=>{state.price=a.dataset.price;$('#priceFilter').value=state.price;loadProducts()});document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{state.category=a.dataset.category;$('#categoryFilter').value=state.category;loadProducts()});updateCounts();loadCatalog()
}
document.addEventListener('DOMContentLoaded',init);
