const state={products:[],categories:[],q:'',category:'',price:'',format:'',rating:'',sort:'relevance',cart:[],wish:[]};
const $=s=>document.querySelector(s);const API='/api/store/';
function money(v,currency='USD'){return Number(v)===0?'Free':new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(v)||0)}
function loginRedirect(){location.href='/login/?next='+encodeURIComponent(location.pathname+location.search+location.hash)}
function updateCounts(){$('#cartCount').textContent=state.cart.length;$('#wishlistCount').textContent=state.wish.length}
function normalizeCartItem(x){return {id:x.product_id||x.id,name:x.name,slug:x.slug,price:Number(x.price_minor||0)/100,currency:x.currency||'USD',quantity:Number(x.quantity||1),icon:x.icon||'📦'}}
function normalizeWishItem(x){return {...x,id:x.id||x.product_id,price:Number(x.price??(Number(x.price_minor||0)/100)||0)}}
function renderCategories(){const g=$('#categoryGrid');g.innerHTML=state.categories.map(c=>`<a class="category-card" href="/nexauren-store/category/?slug=${encodeURIComponent(c.id)}"><span class="category-icon">${c.icon||'📦'}</span><strong>${c.name}</strong><span>${c.description||''}</span></a>`).join('')}
function categoryName(id){return state.categories.find(c=>c.id===id)?.name||id}
function card(x){const wished=state.wish.some(w=>w.id===x.id);return `<article class="product-card"><div class="product-art">${x.icon||'📦'}</div><div class="product-body"><div class="product-meta"><span>${x.tag||categoryName(x.categoryId)}</span><span>★ ${Number(x.rating||0).toFixed(1)}</span></div><h3>${x.name}</h3><p>${x.shortDescription||x.description||x.desc||''}</p><div class="product-foot"><span class="price ${Number(x.price)===0?'free':''}">${money(x.price,x.currency)}</span><div class="mini-actions"><button data-product="${x.id}" aria-label="View ${x.name}">View</button><button data-buy="${x.id}" aria-label="Buy ${x.name}">${Number(x.price)===0?'Get':'Buy'}</button><button data-wish="${x.id}" aria-label="Wishlist">${wished?'♥':'♡'}</button><button data-add="${x.id}" aria-label="Add to cart">+</button></div></div></div></article>`}
function render(products=state.products){$('#resultSummary').textContent=state.q?`${products.length} result${products.length===1?'':'s'} for “${state.q}”`:`${products.length} products available`;$('#productGrid').innerHTML=products.map(card).join('');$('#emptyState').hidden=products.length>0;$('#activeFilters').innerHTML=[state.q?`Search: ${state.q}`:'',state.category?categoryName(state.category):'',state.price?({free:'Free',under5:'Under $5','5to15':'$5–$15',over15:'Over $15'}[state.price]||state.price):'',state.format,state.rating?`${state.rating}★+`:'' ].filter(Boolean).map(x=>`<span class="chip">${x}</span>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buyNow(b.dataset.buy));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(b.dataset.wish));document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product))}
async function loadProducts(){ $('#resultSummary').textContent='Loading products…';const q=new URLSearchParams({limit:'48',sort:state.sort});if(state.q)q.set('q',state.q);if(state.category)q.set('category',state.category);if(state.price)q.set('price',state.price);if(state.format)q.set('format',state.format);if(state.rating)q.set('rating',state.rating);try{const r=await fetch(API+'products?'+q.toString(),{credentials:'include',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Catalog request failed (${r.status})`);const d=await r.json();state.products=Array.isArray(d.products)?d.products:[];render()}catch(err){console.error('Store catalog error',err);state.products=[];$('#resultSummary').textContent='Unable to load the Store catalog.';render([]);toast('Could not load products')}}
async function loadCatalog(){try{const r=await fetch(API+'categories',{credentials:'include',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Categories request failed (${r.status})`);const d=await r.json();state.categories=Array.isArray(d.categories)?d.categories:[];const select=$('#categoryFilter');select.innerHTML='<option value="">All categories</option>'+state.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');renderCategories();await loadProducts();await loadAccountState()}catch(err){console.error('Store categories error',err);$('#resultSummary').textContent='Unable to connect to the Store database.';toast('Store database is not available')}}
async function loadAccountState(){state.cart=[];state.wish=[];updateCounts();const [cartResult,wishResult]=await Promise.allSettled([fetch(API+'cart',{credentials:'include',headers:{Accept:'application/json'}}),fetch(API+'wishlist',{credentials:'include',headers:{Accept:'application/json'}})]);if(cartResult.status==='fulfilled'&&cartResult.value.ok){const d=await cartResult.value.json();state.cart=(Array.isArray(d.cart?.items)?d.cart.items:[]).map(normalizeCartItem)}if(wishResult.status==='fulfilled'&&wishResult.value.ok){const d=await wishResult.value.json();state.wish=(Array.isArray(d.products)?d.products:[]).map(normalizeWishItem)}updateCounts()}
async function addCart(id){try{const r=await fetch(API+'cart',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({product_id:id,quantity:1})});const d=await r.json().catch(()=>({}));if(r.status===401){toast('Please sign in to use your cart.');loginRedirect();return}if(!r.ok)throw new Error(d.error||'Unable to add product to cart.');state.cart=(d.cart?.items||[]).map(normalizeCartItem);updateCounts();toast('Added to cart');openDrawer('cartDrawer');renderCart()}catch(err){console.error('Store cart add error',err);toast(err.message||'Could not update your cart.')}}
async function toggleWish(id){const remove=state.wish.some(x=>x.id===id);try{const r=await fetch(API+'wishlist',{method:remove?'DELETE':'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({product_id:id})});const d=await r.json().catch(()=>({}));if(r.status===401){toast('Please sign in to use your wishlist.');loginRedirect();return}if(!r.ok)throw new Error(d.error||'Unable to update wishlist.');state.wish=(d.products||[]).map(normalizeWishItem);updateCounts();toast(remove?'Removed from wishlist':'Saved to wishlist');render();renderWish()}catch(err){console.error('Store wishlist error',err);toast(err.message||'Could not update your wishlist.')}}
function findProduct(id){return state.products.find(x=>x.id===id)}function cartProduct(item){return findProduct(item.id)||item}
function renderCart(){const b=$('#cartBody');const items=state.cart;b.innerHTML=items.length?items.map(item=>{const x=cartProduct(item);return `<div class="drawer-item"><div class="art">${x.icon||'📦'}</div><div><strong>${x.name}</strong><span>${money(x.price,x.currency)}</span><br><button data-remove="${item.id}">Remove</button></div></div>`}).join(''):'<div class="empty-state"><strong>Your cart is empty.</strong><span>Add products you want to purchase.</span></div>';const total=items.reduce((s,item)=>s+Number(item.price||0)*Number(item.quantity||1),0);$('#cartTotal').textContent=money(total,items[0]?.currency||'USD');b.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>removeCart(btn.dataset.remove))}
async function removeCart(id){try{const r=await fetch(API+'cart',{method:'DELETE',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({product_id:id})});const d=await r.json().catch(()=>({}));if(r.status===401){loginRedirect();return}if(!r.ok)throw new Error(d.error||'Unable to remove product.');state.cart=(d.cart?.items||[]).map(normalizeCartItem);updateCounts();renderCart();render()}catch(err){console.error('Store cart remove error',err);toast(err.message||'Could not update your cart.')}}
function renderWish(){const b=$('#wishlistBody');const items=state.wish;b.innerHTML=items.length?items.map(x=>`<div class="drawer-item"><div class="art">${x.icon||'📦'}</div><div><strong>${x.name}</strong><span>${money(x.price,x.currency)}</span><br><button data-wremove="${x.id}">Remove</button></div></div>`).join(''):'<div class="empty-state"><strong>Your wishlist is empty.</strong><span>Save products to find them later.</span></div>';b.querySelectorAll('[data-wremove]').forEach(btn=>btn.onclick=()=>toggleWish(btn.dataset.wremove))}
function openDrawer(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false');$('#drawerBackdrop').classList.add('open')}function closeDrawers(){document.querySelectorAll('.drawer').forEach(x=>x.classList.remove('open'));$('#drawerBackdrop').classList.remove('open')}
function showProduct(id){const x=findProduct(id);if(!x)return;location.href='/nexauren-store/product/?slug='+encodeURIComponent(x.slug||id)}async function buyNow(id){const product=findProduct(id);if(!product)return;await startCheckout(product.id)}
async function startCheckout(productId){try{toast('Preparing secure checkout…');const r=await fetch(API+'checkout',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({product_id:productId})});const data=await r.json().catch(()=>({}));if(r.status===401){toast('Please sign in to purchase.');loginRedirect();return}if(!r.ok)throw new Error(data.error||'Unable to start checkout.');if(data.free){await loadAccountState();toast('Product added to your library.');return}const url=data.checkout?.approval_url||data.checkout?.url;if(!url)throw new Error('PayPal approval link was not returned.');location.href=url}catch(err){console.error('Store checkout error',err);toast(err.message||'Checkout could not be started.')}}
async function handlePaymentReturn(){const u=new URL(location.href);const reference=u.searchParams.get('reference');const payment=u.searchParams.get('store_payment');if(payment!=='success'||!reference)return;try{toast('Verifying your payment…');const r=await fetch(API+'payment?reference='+encodeURIComponent(reference),{credentials:'include',headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(r.status===401){loginRedirect();return}if(!r.ok)throw new Error(d.error||'Payment verification failed.');await loadAccountState();toast(d.success?'Payment confirmed. Your product is now in your library.':'Payment verified.');u.searchParams.delete('reference');u.searchParams.delete('store_payment');history.replaceState({},'',u.pathname+u.search+u.hash)}catch(err){console.error('Store payment return error',err);toast(err.message||'Payment verification failed.')}}
let toastTimer;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3200)}
function reset(){state.q=state.category=state.price=state.format=state.rating='';$('#heroSearch').value='';$('#categoryFilter').value='';$('#priceFilter').value='';$('#formatFilter').value='';$('#ratingFilter').value='';loadProducts()}
function init(){['categoryFilter','priceFilter','formatFilter','ratingFilter','sortFilter'].forEach(id=>$('#'+id).onchange=e=>{const map={categoryFilter:'category',priceFilter:'price',formatFilter:'format',ratingFilter:'rating',sortFilter:'sort'};state[map[id]]=e.target.value;loadProducts()});$('#heroSearchBtn').onclick=()=>{state.q=$('#heroSearch').value.trim();location.hash='store';loadProducts()};$('#heroSearch').onkeydown=e=>{if(e.key==='Enter')$('#heroSearchBtn').click()};$('#clearFilters').onclick=reset;$('#emptyClear').onclick=reset;$('#cartBtn').onclick=()=>{renderCart();openDrawer('cartDrawer')};$('#wishlistBtn').onclick=()=>{renderWish();openDrawer('wishlistDrawer')};$('#drawerBackdrop').onclick=closeDrawers;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDrawers);$('#checkoutBtn').onclick=()=>{if(state.cart.length)startCheckout(state.cart[0].id);else toast('Your cart is empty.')};$('#mobileMenu').onclick=()=>$('#mobileNav').classList.toggle('open');updateCounts();loadCatalog().then(handlePaymentReturn).catch(handlePaymentReturn)}
document.addEventListener('DOMContentLoaded',init);
