const PRODUCTS=[
{id:'cv',name:'Modern CV Template',category:'Documents',format:'DOCX',price:4.99,rating:4.9,icon:'📄',tag:'Featured',desc:'Clean, professional CV template for modern applications.',date:6},
{id:'invoice',name:'Invoice & Quote Pack',category:'Business Kits',format:'DOCX',price:6.99,rating:4.8,icon:'🧾',tag:'New',desc:'Ready-to-edit invoice, quote and receipt templates.',date:10},
{id:'budget',name:'Personal Budget Dashboard',category:'Spreadsheets',format:'XLSX',price:3.99,rating:4.7,icon:'📊',tag:'Popular',desc:'Track income, expenses, goals and monthly progress.',date:8},
{id:'content',name:'30-Day Content Calendar',category:'Social Media',format:'Canva',price:7.99,rating:4.9,icon:'📱',tag:'Featured',desc:'Plan a month of consistent social content with ease.',date:12},
{id:'prompts',name:'Creator AI Prompt Pack',category:'AI Prompts',format:'TXT',price:2.99,rating:4.6,icon:'🤖',tag:'New',desc:'Practical prompts for writing, marketing and content creation.',date:14},
{id:'landing',name:'SaaS Landing Page Kit',category:'Website Assets',format:'HTML',price:12.99,rating:4.9,icon:'🖥️',tag:'Premium',desc:'Responsive landing page sections ready for your next project.',date:16},
{id:'icons',name:'Minimal UI Icon Set',category:'Design Assets',format:'PNG/SVG',price:8.99,rating:4.8,icon:'🎨',tag:'Popular',desc:'A versatile collection of clean interface icons.',date:4},
{id:'study',name:'Study Planner Starter',category:'Education',format:'PDF',price:0,rating:4.8,icon:'📚',tag:'Free',desc:'Simple printable planner for study sessions and revision.',date:20},
{id:'email',name:'Professional Email Pack',category:'Email Templates',format:'TXT',price:4.49,rating:4.7,icon:'✉️',tag:'New',desc:'Reusable welcome, support, launch and promotional emails.',date:18},
{id:'freelance',name:'Freelancer Starter Bundle',category:'Bundles',format:'DOCX',price:19.99,rating:4.9,icon:'📦',tag:'Bundle',desc:'A practical collection for proposals, invoices and planning.',date:22},
{id:'planner',name:'Complete Productivity Planner',category:'Planners',format:'PDF',price:9.99,rating:4.8,icon:'📅',tag:'Featured',desc:'Daily, weekly, monthly and goal planning in one pack.',date:7},
{id:'code',name:'Responsive Components Pack',category:'Code',format:'JS',price:14.99,rating:4.9,icon:'👨‍💻',tag:'Premium',desc:'Reusable navigation, cards, modals and UI components.',date:11}
];
const CATEGORIES=[['📄','Documents','CVs, forms & files'],['📱','Social Media','Content & campaigns'],['💼','Business Kits','Ready-to-use business'],['📊','Spreadsheets','Track & manage'],['📅','Planners','Plan your work'],['📚','Education','Study & teaching'],['🤖','AI Prompts','Prompt collections'],['🎨','Design Assets','Graphics & icons'],['🖥️','Website Assets','Web-ready UI'],['👨‍💻','Code','Code products'],['✉️','Email Templates','Professional emails'],['📦','Bundles','Complete collections']];
const state={q:'',category:'',price:'',format:'',rating:'',sort:'relevance',cart:JSON.parse(localStorage.getItem('nx_store_cart')||'[]'),wish:JSON.parse(localStorage.getItem('nx_store_wish')||'[]')};
const $=s=>document.querySelector(s);
function money(v){return v===0?'Free':'$'+v.toFixed(2)}
function save(){localStorage.setItem('nx_store_cart',JSON.stringify(state.cart));localStorage.setItem('nx_store_wish',JSON.stringify(state.wish));updateCounts()}
function updateCounts(){$('#cartCount').textContent=state.cart.length;$('#wishlistCount').textContent=state.wish.length}
function renderCategories(){const g=$('#categoryGrid');g.innerHTML=CATEGORIES.map(([i,n,d])=>`<a class="category-card" href="#store" data-category="${n}"><span class="category-icon">${i}</span><strong>${n}</strong><span>${d}</span></a>`).join('');g.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{state.category=a.dataset.category;$('#categoryFilter').value=state.category;render()})}
function filtered(){let p=PRODUCTS.filter(x=>(!state.q||`${x.name} ${x.category} ${x.format} ${x.desc}`.toLowerCase().includes(state.q.toLowerCase()))&&(!state.category||x.category===state.category)&&(!state.format||x.format===state.format)&&(!state.rating||x.rating>=Number(state.rating))&&(!state.price||(state.price==='free'&&x.price===0)||(state.price==='under5'&&x.price>0&&x.price<5)||(state.price==='5to15'&&x.price>=5&&x.price<=15)||(state.price==='over15'&&x.price>15)));if(state.sort==='newest')p.sort((a,b)=>b.date-a.date);if(state.sort==='rating')p.sort((a,b)=>b.rating-a.rating);if(state.sort==='price-low')p.sort((a,b)=>a.price-b.price);if(state.sort==='price-high')p.sort((a,b)=>b.price-a.price);return p}
function render(){const p=filtered();$('#resultSummary').textContent=state.q?`${p.length} result${p.length===1?'':'s'} for “${state.q}”`:`${p.length} products available`;$('#productGrid').innerHTML=p.map(card).join('');$('#emptyState').hidden=p.length>0;$('#activeFilters').innerHTML=[state.q?`Search: ${state.q}`:'',state.category,state.price?({free:'Free',under5:'Under $5', '5to15':'$5–$15',over15:'Over $15'}[state.price]):'',state.format,state.rating?`${state.rating}★+`:'' ].filter(Boolean).map(x=>`<span class="chip">${x}</span>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(b.dataset.wish));document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product));}
function card(id){const x=PRODUCTS.find(v=>v.id===id.id)||id;const wished=state.wish.includes(x.id);return `<article class="product-card"><div class="product-art">${x.icon}</div><div class="product-body"><div class="product-meta"><span>${x.tag}</span><span>★ ${x.rating}</span></div><h3>${x.name}</h3><p>${x.desc}</p><div class="product-foot"><span class="price ${x.price===0?'free':''}">${money(x.price)}</span><div class="mini-actions"><button data-product="${x.id}" aria-label="View ${x.name}">View</button><button data-wish="${x.id}" aria-label="Wishlist">${wished?'♥':'♡'}</button><button data-add="${x.id}" aria-label="Add to cart">+</button></div></div></div></article>`}
function addCart(id){if(!state.cart.includes(id))state.cart.push(id);save();toast('Added to cart');openDrawer('cartDrawer');renderCart()}
function toggleWish(id){const i=state.wish.indexOf(id);if(i>=0){state.wish.splice(i,1);toast('Removed from wishlist')}else{state.wish.push(id);toast('Saved to wishlist')}save();render()}
function renderCart(){const b=$('#cartBody');const items=state.cart.map(id=>PRODUCTS.find(x=>x.id===id)).filter(Boolean);b.innerHTML=items.length?items.map(x=>`<div class="drawer-item"><div class="art">${x.icon}</div><div><strong>${x.name}</strong><span>${money(x.price)}</span><br><button data-remove="${x.id}">Remove</button></div></div>`).join(''):'<div class="empty-state"><strong>Your cart is empty.</strong><span>Add products you want to purchase.</span></div>';const total=items.reduce((s,x)=>s+x.price,0);$('#cartTotal').textContent=money(total);b.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart=state.cart.filter(id=>id!==b.dataset.remove);save();renderCart()})}
function renderWish(){const b=$('#wishlistBody');const items=state.wish.map(id=>PRODUCTS.find(x=>x.id===id)).filter(Boolean);b.innerHTML=items.length?items.map(x=>`<div class="drawer-item"><div class="art">${x.icon}</div><div><strong>${x.name}</strong><span>${money(x.price)}</span><br><button data-wremove="${x.id}">Remove</button></div></div>`).join(''):'<div class="empty-state"><strong>Your wishlist is empty.</strong><span>Save products to find them later.</span></div>';b.querySelectorAll('[data-wremove]').forEach(b=>b.onclick=()=>{state.wish=state.wish.filter(id=>id!==b.dataset.wremove);save();renderWish();render()})}
function openDrawer(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false');$('#drawerBackdrop').classList.add('open')}
function closeDrawers(){document.querySelectorAll('.drawer').forEach(x=>x.classList.remove('open'));$('#drawerBackdrop').classList.remove('open')}
function showProduct(id){const x=PRODUCTS.find(v=>v.id===id);if(!x)return;alert(`${x.name}\n\n${x.desc}\n\n${money(x.price)}\n★ ${x.rating}\n\nProduct detail and secure checkout will be connected when Store commerce is launched.`)}
let toastTimer;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1800)}
function reset(){state.q=state.category=state.price=state.format=state.rating='';$('#heroSearch').value='';$('#categoryFilter').value='';$('#priceFilter').value='';$('#formatFilter').value='';$('#ratingFilter').value='';render()}
function init(){renderCategories();CATEGORIES.forEach(([,n])=>$('#categoryFilter').insertAdjacentHTML('beforeend',`<option>${n}</option>`));['categoryFilter','priceFilter','formatFilter','ratingFilter','sortFilter'].forEach(id=>$('#'+id).onchange=e=>{const map={categoryFilter:'category',priceFilter:'price',formatFilter:'format',ratingFilter:'rating',sortFilter:'sort'};state[map[id]]=e.target.value;render()});$('#heroSearchBtn').onclick=()=>{state.q=$('#heroSearch').value.trim();location.hash='store';render()};$('#heroSearch').onkeydown=e=>{if(e.key==='Enter')$('#heroSearchBtn').click()};$('#clearFilters').onclick=reset;$('#emptyClear').onclick=reset;$('#cartBtn').onclick=()=>{renderCart();openDrawer('cartDrawer')};$('#wishlistBtn').onclick=()=>{renderWish();openDrawer('wishlistDrawer')};$('#drawerBackdrop').onclick=closeDrawers;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDrawers);$('#checkoutBtn').onclick=()=>toast('Checkout will be connected to Nexauren payments at launch.');$('#mobileMenu').onclick=()=>$('#mobileNav').classList.toggle('open');document.querySelectorAll('[data-sort]').forEach(a=>a.onclick=()=>{state.sort=a.dataset.sort;$('#sortFilter').value=state.sort;render()});document.querySelectorAll('[data-price]').forEach(a=>a.onclick=()=>{state.price=a.dataset.price;$('#priceFilter').value=state.price;render()});document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{state.category=a.dataset.category;$('#categoryFilter').value=state.category;render()});updateCounts();render()}
document.addEventListener('DOMContentLoaded',init);