(() => {
  const $ = id => document.getElementById(id);
  const fileInput = $('audioFile'), fileName = $('fileName'), fileMeta = $('fileMeta'), processBtn = $('processBtn'), status = $('status'), result = $('result'), resultAudio = $('resultAudio');
  const start = $('start'), end = $('end'), startOut = $('startOut'), endOut = $('endOut'), startMarker = $('startMarker'), endMarker = $('endMarker'), selection = $('selection'), previewBtn = $('previewBtn'), selectionDuration = $('selectionDuration');
  let file=null,audioBuffer=null,recorder=null,chunks=[],previewAudio=null;
  const fmt=s=>{s=Math.max(0,Number(s)||0);return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`};
  const updateSelection=()=>{if(!start||!end)return;let s=Number(start.value),e=Number(end.value);if(s>e){[s,e]=[e,s];start.value=s;end.value=e}const d=audioBuffer?.duration||0,ss=d*s/100,ee=d*e/100;startOut.textContent=fmt(ss);endOut.textContent=fmt(ee);startMarker.textContent=fmt(ss);endMarker.textContent=fmt(ee);selection.style.left=`${s}%`;selection.style.width=`${Math.max(0,e-s)}%`;selectionDuration.textContent=d?`${fmt(ee-ss)} selected`:'Select a clip to preview';if(previewBtn)previewBtn.disabled=!audioBuffer||e<=s};
  const decode=f=>f.arrayBuffer().then(b=>new AudioContext().decodeAudioData(b));
  const setFile=async f=>{if(!f)return;file=f;fileName.textContent=f.name;fileMeta.textContent=`${(f.size/1024/1024).toFixed(2)} MB · ${f.type||'audio file'}`;result.classList.remove('show');start.value=0;end.value=100;try{audioBuffer=await decode(f);$('wave').style.display='block';drawWave(audioBuffer);processBtn.disabled=false;status.textContent=`${fmt(audioBuffer.duration)} audio loaded.`;updateSelection()}catch{audioBuffer=null;processBtn.disabled=false;status.textContent='File loaded. Browser processing support depends on the audio format.'}};
  $('chooseBtn')?.addEventListener('click',()=>fileInput.click());fileInput?.addEventListener('change',e=>setFile(e.target.files[0]));[start,end].forEach(x=>x?.addEventListener('input',updateSelection));
  const drop=$('drop');['dragenter','dragover'].forEach(e=>drop?.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop?.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop?.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
  $('resetBtn')?.addEventListener('click',()=>{file=null;audioBuffer=null;fileInput.value='';fileName.textContent='No file selected';fileMeta.textContent='—';processBtn.disabled=true;previewBtn.disabled=true;result.classList.remove('show');$('wave').style.display='none';status.textContent='Choose an audio file to begin.';start.value=0;end.value=100;updateSelection();if(previewAudio)previewAudio.pause()});
  previewBtn?.addEventListener('click',()=>{if(!audioBuffer)return;const s=audioBuffer.duration*Number(start.value)/100,e=audioBuffer.duration*Number(end.value)/100;if(previewAudio)previewAudio.pause();previewAudio=new Audio(URL.createObjectURL(wavBlob(audioBuffer,s,e)));previewAudio.onended=()=>{previewBtn.textContent='▶ Preview selection';status.textContent='Preview finished.'};previewAudio.play();previewBtn.textContent='■ Playing selection';status.textContent=`Previewing ${fmt(e-s)} selection.`});
  $('recordBtn')?.addEventListener('click',async()=>{if(recorder?.state==='recording'){recorder.stop();$('recordBtn').textContent='Record from microphone';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setFile(new File(chunks,'nexauren-recording.webm',{type:'audio/webm'}))};recorder.start();$('recordBtn').textContent='Stop recording';status.textContent='Recording…'}catch{status.textContent='Microphone access was not available.'}});
  const drawWave=b=>{const c=$('waveCanvas');if(!c)return;const ctx=c.getContext('2d'),r=devicePixelRatio||1;c.width=c.clientWidth*r;c.height=c.clientHeight*r;ctx.clearRect(0,0,c.width,c.height);const d=b.getChannelData(0),step=Math.max(1,Math.ceil(d.length/c.width));ctx.strokeStyle='#8b67ff';ctx.lineWidth=Math.max(1,r);ctx.beginPath();for(let x=0;x<c.width;x++){let min=1,max=-1;for(let j=0;j<step;j++){const v=d[x*step+j]||0;min=Math.min(min,v);max=Math.max(max,v)}ctx.moveTo(x,c.height/2+min*c.height*.38);ctx.lineTo(x,c.height/2+max*c.height*.38)}ctx.stroke()};
  const wavBlob=(buffer,s=0,e=buffer.duration)=>{const rate=buffer.sampleRate,from=Math.floor(s*rate),to=Math.floor(e*rate),len=Math.max(0,to-from),ch=buffer.numberOfChannels,buf=new ArrayBuffer(44+len*ch*2),v=new DataView(buf),w=(o,t)=>{for(let i=0;i<t.length;i++)v.setUint8(o+i,t.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+len*ch*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*ch*2,true);let p=44;for(let i=0;i<len;i++)for(let c=0;c<ch;c++){let x=Math.max(-1,Math.min(1,buffer.getChannelData(c)[from+i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([buf],{type:'audio/wav'})};
  processBtn?.addEventListener('click',async()=>{if(!audioBuffer){status.textContent='Please choose an audio file first.';return}const processing=$('processing');processing.classList.add('show');processBtn.disabled=true;previewBtn.disabled=true;await new Promise(r=>setTimeout(r,2400));let blob=wavBlob(audioBuffer,0,audioBuffer.duration);if(window.NexaurenAudioTransform)blob=await window.NexaurenAudioTransform(audioBuffer);const url=URL.createObjectURL(blob);resultAudio.src=url;$('downloadBtn').onclick=()=>{const a=document.createElement('a');a.href=url;a.download='nexauren-audio-clip.wav';a.click()};result.classList.add('show');processing.classList.remove('show');processBtn.disabled=false;previewBtn.disabled=false;status.textContent='Your audio clip is ready.'});
  window.NexaurenAudioWorkspace={getBuffer:()=>audioBuffer,wavBlob};updateSelection();
})();
