const $=id=>document.getElementById(id);let editingId=null,blogTools=[];
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
async function api(url,opt={}){const r=await fetch(url,{credentials:'include',...opt}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||`Request failed (${r.status})`);return d}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function slugify(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180)}
function fmtDate(v){return v?new Date(v*1000).toLocaleDateString('pt-PT',{day:'2-digit',month:'long',year:'numeric'}):'—'}
async function loadCategories(){const d=await api('/api/blog/categories');$('category').innerHTML='<option value="">Sem categoria</option>'+(d.categories||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}
async function loadTools(){const r=await fetch('/data/tools.json',{cache:'no-store'});if(!r.ok)throw Error('Não foi possível carregar as ferramentas.');const d=await r.json();blogTools=(Array.isArray(d?.tools)?d.tools:[]).filter(t=>t?.id&&String(t.status||'active')==='active');$('tool').innerHTML='<option value="">Sem ferramenta</option>'+blogTools.map(t=>`<option value="${esc(t.id)}">${esc(t.name||t.id)}</option>`).join('')}
async function loadPosts(){const d=await api('/api/admin/blog/posts?limit=100'),p=d.posts||[];$('posts').innerHTML=p.length?p.map(x=>`<tr><td><strong>${esc(x.title)}</strong><br><small>${esc(x.slug)}</small></td><td>${esc(x.category_name||'—')}</td><td><span class="status ${x.status==='published'?'published':'draft'}">${x.status==='published'?'Publicado':'Rascunho'}</span></td><td>${fmtDate(x.published_at)}</td><td><button class="btn" data-edit="${esc(x.id)}">Editar</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum artigo criado.</td></tr>';document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editPost(b.dataset.edit)))}
async function loadGallery(){const d=await api('/api/admin/blog/images');$('gallery').innerHTML=(d.images||[]).length?(d.images||[]).map(x=>`<button type="button" data-image="${esc(x.url)}"><img src="${esc(x.url)}" alt=""><small>Usar imagem</small></button>`).join(''):'<p class="panel-subtitle">Nenhuma imagem usada ainda.</p>';$('gallery').classList.remove('hidden');document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>useImage(b.dataset.image)))}
function useImage(url){$('cover_image').value=url;$('imagePreview').src=url;$('imagePreview').style.display='block';if(!$('og_image').value)$('og_image').value=url;toast('Imagem selecionada.')}
async function uploadImage(file){if(!file)return;const fd=new FormData();fd.append('image',file);const d=await api('/api/admin/blog/upload',{method:'POST',body:fd});useImage(d.image.url);toast('Imagem carregada com sucesso.')}
function applyToolDefaults(){const tool=blogTools.find(t=>String(t.id)===$('tool').value);if(!tool)return;if(!$('cta_title').value.trim())$('cta_title').value=`Pronto para experimentar o ${tool.name}?`;if(!$('cta_description').value.trim())$('cta_description').value=tool.description||'';if(!$('cta_label').value.trim())$('cta_label').value='Experimentar ferramenta'}
$('imagePicker').addEventListener('change',async e=>{try{await uploadImage(e.target.files[0])}catch(x){toast(x.message)}finally{e.target.value=''}});$('showGallery').addEventListener('click',async()=>{try{await loadGallery()}catch(e){toast(e.message)}});$('tool').addEventListener('change',applyToolDefaults);
async function editPost(id){try{showEditor((await api(`/api/admin/blog/posts/${encodeURIComponent(id)}`)).post)}catch(e){toast(e.message)}}
function showEditor(p=null){editingId=p?.id||null;$('panelTitle').textContent=editingId?'Editar artigo':'Novo artigo';$('list').classList.add('hidden');$('editor').classList.remove('hidden');$('title').value=p?.title||'';$('slug').value=p?.slug||'';$('excerpt').value=p?.excerpt||'';$('content').value=p?.content||'';$('cover_image').value=p?.cover_image||'';$('og_image').value=p?.og_image||'';$('seo_title').value=p?.seo_title||'';$('meta_description').value=p?.meta_description||'';$('author').value=p?.author||'Nexauren';$('status').value=p?.status||'draft';$('featured').value=p?.featured?'1':'0';$('category').value=p?.category_id||'';$('tool').value=p?.tool_id||'';$('cta_title').value=p?.cta_title||'';$('cta_description').value=p?.cta_description||'';$('cta_label').value=p?.cta_label||'Experimentar ferramenta';if(p?.cover_image){$('imagePreview').src=p.cover_image;$('imagePreview').style.display='block'}$('deletePost').classList.toggle('hidden',!editingId)}
$('title').addEventListener('input',()=>{if(!editingId)$('slug').value=slugify($('title').value)});$('newPost').addEventListener('click',()=>showEditor());$('cancel').addEventListener('click',()=>{editingId=null;$('editor').classList.add('hidden');$('list').classList.remove('hidden');$('panelTitle').textContent='Artigos'});
$('deletePost').addEventListener('click',async()=>{if(!editingId)return;if(!confirm('Eliminar este artigo permanentemente? Esta ação não pode ser desfeita.'))return;try{await api(`/api/admin/blog/posts/${encodeURIComponent(editingId)}`,{method:'DELETE'});toast('Artigo eliminado.');$('cancel').click();await loadPosts()}catch(e){toast(e.message)}});
$('postForm').addEventListener('submit',async e=>{e.preventDefault();const cover=$('cover_image').value.trim(),body={title:$('title').value.trim(),slug:$('slug').value.trim(),excerpt:$('excerpt').value.trim(),content:$('content').value,cover_image:cover,og_image:$('og_image').value.trim()||cover,seo_title:$('seo_title').value.trim(),meta_description:$('meta_description').value.trim(),author:$('author').value.trim()||'Nexauren',category_id:$('category').value||null,status:$('status').value,featured:Number($('featured').value),tool_id:$('tool').value||'',cta_title:$('cta_title').value.trim(),cta_description:$('cta_description').value.trim(),cta_label:$('cta_label').value.trim()||'Experimentar ferramenta'};try{await api(editingId?`/api/admin/blog/posts/${encodeURIComponent(editingId)}`:'/api/admin/blog/posts',{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('Artigo salvo com sucesso.');$('cancel').click();await loadPosts()}catch(x){toast(x.message)}});
(async()=>{try{await Promise.all([loadCategories(),loadTools()]);await loadPosts()}catch(e){$('posts').innerHTML=`<tr><td colspan="5" class="empty">${esc(e.message)}</td></tr>`}})();