(()=>{
'use strict';
if(location.pathname!=='/studios/audio/instrument-editor/')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={tracks:[],selected:new Set(),markers:[],master:{gain:1},tempo:120,playing:false,startAt:0,playOrigin:0,zoom:1,history:[],future:[],notes:[],drums:Array.from({length:8},()=>Array(16).fill(false)),automation:[{x:.1,y:.7},{x:.35,y:.45},{x:.6,y:.3},{x:.9,y:.6}]};
let ctx=null,master=null,sourceNodes=new Map(),raf=0;
const snapshot=()=>({tracks:state.tracks.map(t=>({...t,buffer:undefined})),markers:state.markers,tempo:state.tempo,zoom:state.zoom,notes:state.notes,drums:state.drums,automation:state.automation});
const saveHistory=()=>{state.history.push(JSON.stringify(snapshot()));if(state.history.length>30)state.history.shift();state.future=[]};
const ensureAudio=()=>{if(ctx)return ctx;ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.connect(ctx.destination);return ctx};
const fmt=s=>{s=Math.max(0,s);return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`};
const status=m=>{let e=$('.status');if(!e){e=document.createElement('div');e.className='status';document.body.appendChild(e)}e.textContent=m;clearTimeout(status.t);status.t=setTimeout(()=>e.textContent='Ready',1800)};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function drawWave(c,b){if(!c||!b)return;const r=c.getBoundingClientRect(),w=Math.max(100,Math.floor(r.width*devicePixelRatio)),h=Math.max(40,Math.floor(r.height*devicePixelRatio));c.width=w;c.height=h;const x=c.getContext('2d'),data=b.getChannelData(0),step=Math.max(1,Math.floor(data.length/w));x.clearRect(0,0,w,h);x.beginPath();for(let i=0;i<w;i++){let mn=1,mx=-1;for(let j=0;j<step;j++){const v=data[i*step+j]||0;mn=Math.min(mn,v);mx=Math.max(mx,v)}x.moveTo(i,(1+mn)*h/2);x.lineTo(i,(1+mx)*h/2)}x.strokeStyle='#8b6cff';x.globalAlpha=.65;x.stroke()}
function selectTrack(id,add=false){if(!add)state.selected.clear();state.selected.add(id);renderTracks();updateInspector()}
function current(){return state.tracks.find(t=>state.selected.has(t.id))||state.tracks[0]}
function renderRuler(){const r=$('#ruler');if(!r)return;r.innerHTML='';for(let i=0;i<=40;i+=2){const s=document.createElement('span');s.textContent=fmt(i);s.style.left=`${i*60*state.zoom}px`;r.appendChild(s)}state.markers.forEach(m=>{const d=document.createElement('div');d.className='marker';d.style.left=`${m.time*60*state.zoom}px`;d.innerHTML=`<span>${esc(m.name)}</span>`;r.appendChild(d)})}
function renderPlayhead(){const h=$('#head');if(h)h.style.left=`${state.playOrigin*60*state.zoom}px`}
function makeClipInteractive(el,t){let drag=false,sx=0,so=0;el.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag=true;sx=e.clientX;so=t.offset||0;el.setPointerCapture(e.pointerId);selectTrack(t.id,e.shiftKey)});el.addEventListener('pointermove',e=>{if(!drag)return;t.offset=Math.max(0,so+(e.clientX-sx)/(60*state.zoom));el.style.left=`${t.offset*60*state.zoom}px`});el.addEventListener('pointerup',()=>{drag=false;saveProject()});el.addEventListener('dblclick',()=>{selectTrack(t.id);status('Clip selected — edit below')})}
function renderTracks(){const list=$('#tracklist'),lanes=$('#lanes');if(!list||!lanes)return;list.innerHTML='';$$('.lane',lanes).forEach(e=>e.remove());state.tracks.forEach(t=>{const row=document.createElement('div');row.className='track'+(state.selected.has(t.id)?' active':'');row.innerHTML=`<div class="trackname"><span class="dot"></span>${esc(t.name)}</div><div class="trackmeta">${t.kind||'Audio'} · ${fmt(t.duration||0)}</div><div class="trackbuttons"><button class="mini ${t.mute?'on':''}" data-a="mute">M</button><button class="mini ${t.solo?'on':''}" data-a="solo">S</button><button class="mini" data-a="dup">Dup</button><button class="mini" data-a="del">×</button></div>`;row.addEventListener('click',e=>{if(e.target.closest('button'))return;selectTrack(t.id,e.shiftKey)});row.querySelectorAll('[data-a]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();saveHistory();const a=b.dataset.a;if(a==='mute')t.mute=!t.mute;if(a==='solo')t.solo=!t.solo;if(a==='dup'){state.tracks.push({...t,id:crypto.randomUUID(),name:t.name+' Copy',offset:(t.offset||0)+.5});}if(a==='del'){state.tracks=state.tracks.filter(x=>x.id!==t.id);state.selected.delete(t.id)}renderTracks();saveProject()}));list.appendChild(row);const lane=document.createElement('div');lane.className='lane';lane.style.minWidth=`${1100*state.zoom}px`;const clip=document.createElement('div');clip.className='clip'+(state.selected.has(t.id)?' selected':'');clip.style.left=`${(t.offset||0)*60*state.zoom}px`;clip.style.width=`${Math.max(45,(t.duration||1)*60*state.zoom)}px`;clip.innerHTML=`<canvas></canvas><b>${esc(t.name)}</b><small>${fmt(t.duration||0)}</small>`;lane.appendChild(clip);lanes.appendChild(lane);drawWave(clip.querySelector('canvas'),t.buffer);makeClipInteractive(clip,t)});renderRuler();renderPlayhead()}
function updateInspector(){const n=$('#selectedName');if(n)n.textContent=current()?.name||'Master'}
async function importFiles(files){for(const file of files){try{const c=ensureAudio(),buf=await c.decodeAudioData(await file.arrayBuffer());const t={id:crypto.randomUUID(),name:file.name,kind:'Audio',buffer:buf,duration:buf.duration,offset:0,gain:1,pan:0,mute:false,solo:false,filter:20000,speed:1,pitch:0,bus:'music',send:0,fadeIn:0,fadeOut:0};state.tracks.push(t);state.selected.clear();state.selected.add(t.id)}catch{status('Could not decode '+file.name)}}renderTracks();updateInspector();saveProject();status('Audio imported locally')}
function stopAll(){sourceNodes.forEach(s=>{try{s.stop()}catch{}});sourceNodes.clear();state.playing=false;cancelAnimationFrame(raf)}
function play(){const c=ensureAudio();if(c.state==='suspended')c.resume();stopAll();const solo=state.tracks.some(t=>t.solo);state.startAt=c.currentTime;state.playOrigin=0;state.tracks.forEach(t=>{if(!t.buffer||t.mute||(solo&&!t.solo))return;const s=c.createBufferSource(),g=c.createGain(),p=c.createStereoPanner(),f=c.createBiquadFilter();s.buffer=t.buffer;s.playbackRate.value=t.speed||1;s.detune.value=t.pitch||0;g.gain.value=t.gain??1;p.pan.value=t.pan||0;f.type='lowpass';f.frequency.value=t.filter||20000;s.connect(f).connect(g).connect(p).connect(master);s.start(c.currentTime+Math.max(0,t.offset||0));sourceNodes.set(t.id,s)});state.playing=true;tick();status('Playing')}
function tick(){if(!state.playing)return;state.playOrigin=ctx.currentTime-state.startAt;renderPlayhead();const c=$('#clock');if(c)c.textContent=fmt(state.playOrigin);raf=requestAnimationFrame(tick)}
function stop(){stopAll();state.playOrigin=0;renderPlayhead();status('Stopped')}
function wav(b){const ch=b.numberOfChannels,len=b.length*ch,buf=new ArrayBuffer(44+len*2),v=new DataView(buf),w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+len*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*2,true);let p=44;for(let i=0;i<b.length;i++)for(let c=0;c<ch;c++){let q=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(p,q<0?q*32768:q*32767,true);p+=2}return new Blob([buf],{type:'audio/wav'})}
async function exportMix(){if(!state.tracks.length)return status('Add audio first');const max=state.tracks.reduce((m,t)=>Math.max(m,(t.offset||0)+(t.duration||0)/(t.speed||1)),0)+1,rate=44100,o=new OfflineAudioContext(2,Math.ceil(max*rate),rate),mg=o.createGain();mg.connect(o.destination);const solo=state.tracks.some(t=>t.solo);for(const t of state.tracks){if(!t.buffer||t.mute||(solo&&!t.solo))continue;const s=o.createBufferSource(),g=o.createGain(),p=o.createStereoPanner(),f=o.createBiquadFilter();s.buffer=t.buffer;s.playbackRate.value=t.speed||1;s.detune.value=t.pitch||0;g.gain.value=t.gain??1;p.pan.value=t.pan||0;f.type='lowpass';f.frequency.value=t.filter||20000;s.connect(f).connect(g).connect(p).connect(mg);const at=Math.max(0,t.offset||0),end=at+t.duration/(t.speed||1);if(t.fadeIn)g.gain.setValueAtTime(0,at),g.gain.linearRampToValueAtTime(t.gain||1,at+t.fadeIn);if(t.fadeOut)g.gain.setValueAtTime(t.gain||1,Math.max(at,end-t.fadeOut)),g.gain.linearRampToValueAtTime(0,end);s.start(at)}status('Rendering WAV…');const b=await o.startRendering(),blob=wav(b),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexauren-daw-mix.wav';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);status('WAV exported')}
function addMarker(){state.markers.push({time:state.playOrigin||0,name:'Marker '+(state.markers.length+1)});renderRuler();saveProject();status('Marker added')}
function setupDrums(){const g=$('#drumgrid');if(!g)return;g.innerHTML='';const names=['Kick','Snare','Hat','Clap','Tom','Perc','Open Hat','FX'];g.appendChild(document.createElement('div'));for(let i=0;i<16;i++){const h=document.createElement('div');h.className='padlabel';h.textContent=i+1;g.appendChild(h)}names.forEach((n,r)=>{const l=document.createElement('div');l.className='padlabel';l.textContent=n;g.appendChild(l);for(let c=0;c<16;c++){const p=document.createElement('button');p.className='pad'+(state.drums[r][c]?' on':'');p.addEventListener('click',()=>{state.drums[r][c]=!state.drums[r][c];p.classList.toggle('on');triggerSynth(r,state.drums[r][c]);saveProject()});g.appendChild(p)}})}
function triggerSynth(r,on){if(!on)return;const c=ensureAudio(),o=c.createOscillator(),g=c.createGain();o.type=r===2||r===6?'square':'sine';o.frequency.value=[55,110,440,180,160,220,600,880][r];g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.15,c.currentTime+.005);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.12);o.connect(g).connect(master);o.start();o.stop(c.currentTime+.13)}
function setupPiano(){const r=$('#roll'),k=$('#keys');if(!r||!k)return;k.innerHTML='';for(let i=0;i<24;i++){const d=document.createElement('div');d.className='key';d.textContent=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'][i%12];k.appendChild(d)}r.addEventListener('dblclick',e=>{const b=r.getBoundingClientRect(),n={id:crypto.randomUUID(),x:e.clientX-b.left+r.scrollLeft,y:e.clientY-b.top+r.scrollTop,w:60};state.notes.push(n);renderNotes();triggerNote(69-Math.floor(n.y/18))});renderNotes()}
function renderNotes(){const r=$('#roll');if(!r)return;$$('.note',r).forEach(e=>e.remove());state.notes.forEach(n=>{const d=document.createElement('div');d.className='note';d.style.left=n.x+'px';d.style.top=n.y+'px';d.style.width=n.w+'px';d.addEventListener('pointerdown',e=>{const sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;d.setPointerCapture(e.pointerId);const mv=x=>{n.x=Math.max(0,ox+x.clientX-sx);n.y=Math.max(0,oy+x.clientY-sy);d.style.left=n.x+'px';d.style.top=n.y+'px'};d.addEventListener('pointermove',mv);d.addEventListener('pointerup',()=>d.removeEventListener('pointermove',mv),{once:true})});d.addEventListener('dblclick',()=>{state.notes=state.notes.filter(x=>x.id!==n.id);renderNotes()});r.appendChild(d)})}
function triggerNote(m){const c=ensureAudio(),o=c.createOscillator(),g=c.createGain();o.type='sawtooth';o.frequency.value=440*Math.pow(2,(m-69)/12);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.5);o.connect(g).connect(master);o.start();o.stop(c.currentTime+.52)}
function setupAutomation(){const a=$('#auto');if(!a)return;a.addEventListener('pointerdown',e=>{const r=a.getBoundingClientRect();state.automation.push({x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height});renderAutomation()});renderAutomation()}
function renderAutomation(){const a=$('#auto');if(!a)return;$$('.auto-point',a).forEach(x=>x.remove());state.automation.forEach(p=>{const d=document.createElement('i');d.className='auto-point';d.style.left=p.x*100+'%';d.style.top=p.y*100+'%';d.addEventListener('pointerdown',e=>{e.stopPropagation();d.setPointerCapture(e.pointerId);const r=a.getBoundingClientRect(),mv=x=>{p.x=Math.max(0,Math.min(1,(x.clientX-r.left)/r.width));p.y=Math.max(0,Math.min(1,(x.clientY-r.top)/r.height));d.style.left=p.x*100+'%';d.style.top=p.y*100+'%'};d.addEventListener('pointermove',mv);d.addEventListener('pointerup',()=>d.removeEventListener('pointermove',mv),{once:true})});a.appendChild(d)})}
function setupMIDI(){if(!navigator.requestMIDIAccess)return;navigator.requestMIDIAccess().then(a=>{for(const i of a.inputs.values())i.onmidimessage=e=>{const[st,n,v]=e.data;if((st&240)===144&&v)triggerNote(n)}}).catch(()=>{})}
function saveProject(){try{localStorage.setItem('nexauren_daw_project',JSON.stringify(snapshot()))}catch{}}
function restore(){try{const d=JSON.parse(localStorage.getItem('nexauren_daw_project')||'null');if(d){state.markers=d.markers||[];state.tempo=d.tempo||120;state.zoom=d.zoom||1;state.notes=d.notes||[];state.drums=d.drums||state.drums;state.automation=d.automation||state.automation}}catch{}}
function bind(){setupDrums();setupPiano();setupAutomation();setupMIDI();$('#play')?.addEventListener('click',play);$('#stop')?.addEventListener('click',stop);$('#export')?.addEventListener('click',exportMix);$('#marker')?.addEventListener('click',addMarker);$('#add')?.addEventListener('click',()=>$('#files')?.click());$('#open')?.addEventListener('click',()=>$('#files')?.click());$('#files')?.addEventListener('change',e=>importFiles(e.target.files));$('#save')?.addEventListener('click',()=>{saveProject();status('Project saved on this device')});$('#new')?.addEventListener('click',()=>{if(confirm('Clear this project?')){stop();state.tracks=[];state.notes=[];state.markers=[];renderTracks();renderNotes();renderRuler();saveProject()}});$('#bpm')?.addEventListener('change',e=>state.tempo=Math.max(40,Math.min(240,+e.target.value||120)));document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.code==='Space'){e.preventDefault();state.playing?stop():play()}if(e.key.toLowerCase()==='n')addMarker();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject();status('Saved')}if(e.key==='Delete'&&current())removeSelected()});const sc=$('#scroll');sc?.addEventListener('scroll',()=>{$('#ruler').scrollLeft=sc.scrollLeft});const drop=$('.ie-drop');if(drop){['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>importFiles(e.dataTransfer.files))}}
function removeSelected(){const ids=new Set(state.selected);state.tracks=state.tracks.filter(t=>!ids.has(t.id));state.selected.clear();renderTracks();saveProject();status('Selected tracks deleted')}
function init(){restore();bind();renderTracks();renderNotes();renderRuler();status('Nexauren DAW ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.NexaurenDAW={state,importFiles,play,stop,exportMix};
})();
