(()=>{'use strict';
const $=s=>document.querySelector(s);
const fileInput=$('#sample-file'),drop=$('#dropzone'),fileCard=$('#file-card'),fileName=$('#file-name'),fileMeta=$('#file-meta'),generateBtn=$('#generate'),count=$('#count'),countValue=$('#count-value'),countHelp=$('#count-help'),effectsEl=$('#effects'),results=$('#results'),list=$('#sample-list'),progress=$('#progress'),progressFill=$('#progress-fill'),progressLabel=$('#progress-label'),progressCount=$('#progress-count');
let PLAN='free';
const LIMITS={free:{daily:10,max:10,effects:'basic'},starter:{daily:25,max:50,effects:'starter'},pro:{daily:Infinity,max:500,effects:'pro'},premium:{daily:Infinity,max:500,effects:'premium'}};
const EFFECTS=[
 ['gain','Gain','basic'],['eq','Tone EQ','basic'],['lowpass','Low Pass','basic'],['highpass','High Pass','basic'],['reverb','Reverb','basic'],['delay','Delay','basic'],
 ['compressor','Compression','starter'],['saturation','Saturation','starter'],['distortion','Distortion','starter'],['chorus','Chorus','starter'],['flanger','Flanger','starter'],['phaser','Phaser','starter'],['bitcrusher','Bitcrush','starter'],['stereo','Stereo Width','starter'],
 ['transient','Transient Punch','pro'],['stretch','Time Variation','pro'],['granular','Texture','pro'],['chain','Effect Chains','premium']
];
let sourceFile=null,sourceBuffer=null,outputs=[],audioContext=null;
const todayKey=()=>`nexauren_sample_maker_${new Date().toISOString().slice(0,10)}`;
const usage=()=>Number(localStorage.getItem(todayKey())||0);
const bumpUsage=()=>localStorage.setItem(todayKey(),String(usage()+1));
const tierRank={basic:0,starter:1,pro:2,premium:3};
function allowed(effect){return tierRank[effect]<=tierRank[LIMITS[PLAN].effects]}
function renderEffects(){effectsEl.innerHTML=EFFECTS.map(([id,label,tier],i)=>{const ok=allowed(tier);return `<label class="sm-effect ${ok?'':'is-locked'}"><input type="checkbox" value="${id}" ${ok&&i<Math.min(5,EFFECTS.length)?'checked':''} ${ok?'':'disabled'}><span>${label}</span></label>`}).join('')}
function updatePlan(){const l=LIMITS[PLAN];$('#plan-label').textContent=`${PLAN[0].toUpperCase()+PLAN.slice(1)} plan`;$('#usage-label').textContent=Number.isFinite(l.daily)?`${Math.max(0,l.daily-usage())} generations left today`:'Unlimited generations';count.max=l.max;count.value=Math.min(Number(count.value),l.max);countValue.textContent=count.value;countHelp.textContent=`${PLAN[0].toUpperCase()+PLAN.slice(1)}: up to ${l.max} samples per generation`;$('[data-upgrade]')?.remove();$('#upgrade-copy').textContent=PLAN==='free'?'Starter unlocks more effects and up to 50 samples per generation.':'Unlock a bigger sound palette and more advanced controls.'}
window.NEXAUREN_SAMPLE_MAKER_APPLY_PLAN=(plan)=>{plan=String(plan||'free').toLowerCase();PLAN=LIMITS[plan]?plan:'free';renderEffects();updatePlan()};
function formatTime(sec){sec=Math.max(0,sec||0);return `${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,'0')}`}
function setFile(file){if(!file||!file.type.startsWith('audio/')){alert('Please choose a supported audio file.');return}sourceFile=file;fileName.textContent=file.name;fileMeta.textContent=`${file.type.replace('audio/','').toUpperCase()} • loading…`;fileCard.hidden=false;drop.hidden=true;generateBtn.disabled=true;const fr=new FileReader();fr.onload=async()=>{try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();sourceBuffer=await audioContext.decodeAudioData(fr.result.slice(0));fileMeta.textContent=`${file.type.replace('audio/','').toUpperCase()} • ${formatTime(sourceBuffer.duration)} • ${sourceBuffer.numberOfChannels} ch`;generateBtn.disabled=false;$('#ready-title').textContent='Ready to make your pack';$('#ready-copy').textContent=`${sourceFile.name} • ${count.value} variations`;}catch(e){sourceBuffer=null;alert('This audio format could not be decoded by your browser. Try WAV or MP3.');}};fr.readAsArrayBuffer(file)}
fileInput.addEventListener('change',e=>setFile(e.target.files[0]));['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('is-drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('is-drag')}));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));$('#remove-file').onclick=()=>{sourceFile=null;sourceBuffer=null;fileInput.value='';fileCard.hidden=true;drop.hidden=false;generateBtn.disabled=true;results.hidden=true};
count.addEventListener('input',()=>{countValue.textContent=count.value;$('#ready-copy').textContent=sourceFile?`${sourceFile.name} • ${count.value} variations`:'Upload a sample and choose your sound family.'});
const names={kick:['Deep','Punchy','Dark','Heavy','Sub','Warm','Hard','Tight','Analog','Crushed'],snare:['Crisp','Punchy','Dry','Wide','Sharp','Dark','Bright','Tight','Body','Crack'],clap:['Tight','Wide','Dry','Bright','Dark','Roomy','Sharp','Soft','Layered','Crisp'],hihat:['Crisp','Bright','Dark','Open','Tight','Metallic','Airy','Dry','Shimmer','Short'],percussion:['Organic','Tight','Warm','Dry','Wide','Dark','Bright','Punchy','Roomy','Sharp'],tom:['Deep','Round','Punchy','Warm','Dark','Wide','Tight','Heavy','Short','Resonant'],808:['Deep','Sub','Heavy','Distorted','Warm','Long','Tight','Dark','Punchy','Glide'],bass:['Deep','Warm','Punchy','Round','Dark','Bright','Wide','Tight','Analog','Heavy'],vocal:['Airy','Warm','Dark','Wide','Clean','Dreamy','Deep','Bright','LoFi','Space'],fx:['Dark','Rising','Impact','Glitch','Wide','Deep','Bright','Reverse','Atmospheric','Digital'],piano:['Warm','Soft','Bright','Dark','Wide','Roomy','Tape','Clean','Dreamy','Dry'],synth:['Wide','Bright','Dark','Warm','Analog','Digital','Dreamy','Sharp','Soft','Heavy'],other:['Clean','Dark','Bright','Warm','Wide','Tight','Soft','Hard','Deep','Processed']};
function hashSeed(n){let x=Math.sin(n*999.91)*43758.5453;return x-Math.floor(x)}
function chooseEffects(){return [...effectsEl.querySelectorAll('input:checked')].map(x=>x.value)}
function safeName(i){const type=$('#sample-type').value, chars=names[type]||names.other;const a=chars[i%chars.length], b=['Clean','Punch','Texture','Room','Tone','Drive','Space','Edge'][Math.floor(i/chars.length)%8];const ext='wav';return `${type==='hihat'?'HiHat':type[0].toUpperCase()+type.slice(1)}_${a}_${b}_${String(i+1).padStart(2,'0')}.${ext}`}
function makeImpulse(ctx,duration,decay,seed){const len=Math.floor(ctx.sampleRate*duration),b=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)*(0.65+seed*.25)}return b}
function connectEffect(ctx,source,effects,seed){let node=source;const chain=[];const mk=(n)=>{node.connect(n);node=n;chain.push(n)};
if(effects.includes('lowpass')){const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=1800+seed*8000;f.Q.value=.35+seed*1.2;mk(f)}
if(effects.includes('highpass')){const f=ctx.createBiquadFilter();f.type='highpass';f.frequency.value=35+seed*220;f.Q.value=.25;mk(f)}
if(effects.includes('eq')){const f=ctx.createBiquadFilter();f.type='peaking';f.frequency.value=500+seed*4500;f.Q.value=.8;f.gain.value=(seed-.5)*10;mk(f)}
if(effects.includes('compressor')){const c=ctx.createDynamicsCompressor();c.threshold.value=-28+seed*12;c.ratio.value=2+seed*7;c.attack.value=.002;c.release.value=.06+seed*.15;mk(c)}
if(effects.includes('saturation')||effects.includes('distortion')){const w=ctx.createWaveShaper();const amount=effects.includes('distortion')?2+seed*10:.8+seed*2;const curve=new Float32Array(1024);for(let i=0;i<curve.length;i++){const x=i*2/curve.length-1;curve[i]=Math.tanh(x*amount)}w.curve=curve;w.oversample='2x';mk(w)}
if(effects.includes('bitcrusher')){const w=ctx.createWaveShaper();const steps=8+Math.floor(seed*24),curve=new Float32Array(1024);for(let i=0;i<curve.length;i++){const x=i*2/curve.length-1;curve[i]=Math.round(x*steps)/steps}w.curve=curve;mk(w)}
if(effects.includes('chorus')||effects.includes('flanger')||effects.includes('phaser')){const d=ctx.createDelay(.05);d.delayTime.value=effects.includes('flanger')?.003+seed*.012:.012+seed*.025;const g=ctx.createGain();g.gain.value=.12+seed*.13;node.connect(d);d.connect(g);g.connect(node)}
if(effects.includes('delay')){const d=ctx.createDelay(1);d.delayTime.value=.07+seed*.25;const g=ctx.createGain();g.gain.value=.12+seed*.12;node.connect(d);d.connect(g);g.connect(node)}
if(effects.includes('reverb')){const con=ctx.createConvolver();con.buffer=makeImpulse(ctx,.35+seed*.7,1.6+seed*2,seed);const g=ctx.createGain();g.gain.value=.12+seed*.16;node.connect(con);con.connect(g);g.connect(ctx.destination)}
return node}
async function renderOne(i,total){const seed=hashSeed(i+1),sr=sourceBuffer.sampleRate;const pitchRange=Number($('#pitch').value)||0;const semitone=(seed-.5)*2*pitchRange;const rate=Math.pow(2,semitone/12);const duration=Math.max(.08,sourceBuffer.duration/rate);const tail=1.1;const ctx=new OfflineAudioContext(2,Math.ceil((duration+tail)*sr),sr);const src=ctx.createBufferSource();src.buffer=sourceBuffer;src.playbackRate.value=rate;const effects=chooseEffects();let node=src;const input=ctx.createGain();input.gain.value=.88+seed*.22;src.connect(input);node=connectEffect(ctx,input,effects,seed);if(node!==input)node.connect(ctx.destination);else input.connect(ctx.destination);const width=Number($('#width').value)/100;const panner=ctx.createStereoPanner();panner.pan.value=(seed-.5)*2*width;input.disconnect();input.connect(panner);node=connectEffect(ctx,panner,effects,seed);node.connect(ctx.destination);const punch=Number($('#punch').value)/100;const comp=ctx.createDynamicsCompressor();comp.threshold.value=-22-punch*12;comp.ratio.value=1.4+punch*5;comp.attack.value=.002;comp.release.value=.08;node.disconnect();node.connect(comp);comp.connect(ctx.destination);src.start(0);const rendered=await ctx.startRendering();return {buffer:rendered,name:safeName(i),effects,seed}}
function wavBlob(buffer){const channels=buffer.numberOfChannels,sr=buffer.sampleRate,len=buffer.length;const bytes=44+len*channels*2;const ab=new ArrayBuffer(bytes),v=new DataView(ab);let p=0;const ws=(s)=>{for(let i=0;i<s.length;i++)v.setUint8(p++,s.charCodeAt(i))};const w32=n=>{v.setUint32(p,n,true);p+=4};const w16=n=>{v.setUint16(p,n,true);p+=2};ws('RIFF');w32(bytes-8);ws('WAVE');ws('fmt ');w32(16);w16(1);w16(channels);w32(sr);w32(sr*channels*2);w16(channels*2);w16(16);ws('data');w32(len*channels*2);for(let i=0;i<len;i++)for(let c=0;c<channels;c++){let x=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(p,x<0?x*0x8000:x*0x7fff,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function playSample(item,button){if(item.audio){if(item.audio.paused)item.audio.play();else item.audio.pause();return}item.audio=new Audio(URL.createObjectURL(item.blob));item.audio.onplay=()=>button.textContent='Ⅱ';item.audio.onpause=()=>button.textContent='▶';item.audio.onended=()=>button.textContent='▶';item.audio.play()}
function renderResults(){list.innerHTML=outputs.map((o,i)=>`<article class="sm-sample"><div class="sm-sample-info"><button class="sm-play" data-play="${i}" type="button">▶</button><div><div class="sm-sample-name">${o.name}</div><div class="sm-sample-meta">${o.effects.length?o.effects.join(' • '):'Clean variation'}</div></div></div><div class="sm-sample-actions"><button class="sm-mini" data-download="${i}" type="button">Download</button></div></article>`).join('');list.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playSample(outputs[Number(b.dataset.play)],b));list.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(outputs[Number(b.dataset.download)].blob,outputs[Number(b.dataset.download)].name));}
$('#select-effects').onclick=()=>{effectsEl.querySelectorAll('input:not(:disabled)').forEach(x=>x.checked=true)};
$('#generate').onclick=async()=>{if(!sourceBuffer)return;const plan=LIMITS[PLAN];if(Number.isFinite(plan.daily)&&usage()>=plan.daily){alert('You have reached your daily Sample Maker generation limit.');return}const n=Math.min(Number(count.value),plan.max);outputs=[];progress.hidden=false;results.hidden=true;generateBtn.disabled=true;const effects=chooseEffects();if(!effects.length){alert('Select at least one effect or use a clean variation.');generateBtn.disabled=false;progress.hidden=true;return}for(let i=0;i<n;i++){progressLabel.textContent=`Creating variation ${i+1}…`;progressCount.textContent=`${i+1} / ${n}`;progressFill.style.width=`${((i+1)/n)*100}%`;try{const o=await renderOne(i,n);o.blob=wavBlob(o.buffer);delete o.buffer;outputs.push(o);renderResults()}catch(e){console.error(e);}}
bumpUsage();updatePlan();results.hidden=!outputs.length;$('#results-summary').textContent=`${outputs.length} variations generated from ${sourceFile.name}.`;progressLabel.textContent='Pack complete';generateBtn.disabled=false;$('#ready-title').textContent='Pack ready';$('#ready-copy').textContent=`Generate again for a new set of variations.`;};
$('#download-all').onclick=async()=>{if(!outputs.length)return;const files=outputs.map(o=>({name:o.name,blob:o.blob}));if('CompressionStream' in window){const enc=new TextEncoder();const crc32=(data)=>{let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1))}return(c^0xffffffff)>>>0};const local=[];let offset=0;for(const f of files){const data=new Uint8Array(await f.blob.arrayBuffer()),name=enc.encode(f.name);const h=new Uint8Array(30+name.length),d=new DataView(h.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(8,0,true);d.setUint16(10,0,true);d.setUint32(14,crc32(data),true);d.setUint32(18,data.length,true);d.setUint32(22,data.length,true);d.setUint16(26,name.length,true);h.set(name,30);local.push(h,data);offset+=h.length+data.length}const central=[];offset=0;for(const f of files){const data=new Uint8Array(await f.blob.arrayBuffer()),name=enc.encode(f.name),h=new Uint8Array(46+name.length),d=new DataView(h.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(10,0,true);d.setUint32(20,crc32(data),true);d.setUint32(24,data.length,true);d.setUint32(28,data.length,true);d.setUint16(32,name.length,true);d.setUint32(42,offset,true);h.set(name,46);central.push(h);offset+=30+name.length+data.length}const end=new Uint8Array(22),ed=new DataView(end.buffer);ed.setUint32(0,0x06054b50,true);ed.setUint16(8,files.length,true);ed.setUint16(10,files.length,true);ed.setUint32(12,central.reduce((a,x)=>a+x.length,0),true);ed.setUint32(16,local.reduce((a,x)=>a+x.length,0),true);download(new Blob([...local,...central,end],{type:'application/zip'}),'sample-maker-pack.zip')}else download(outputs[0].blob,outputs[0].name)};
renderEffects();updatePlan();
})();
