(()=>{'use strict';
const $=s=>document.querySelector(s);
const fileInput=$('#sample-file'),drop=$('#dropzone'),fileCard=$('#file-card'),fileName=$('#file-name'),fileMeta=$('#file-meta'),generateBtn=$('#generate'),count=$('#count'),countValue=$('#count-value'),countHelp=$('#count-help'),effectsEl=$('#effects'),results=$('#results'),list=$('#sample-list'),progress=$('#progress'),progressFill=$('#progress-fill'),progressLabel=$('#progress-label'),progressCount=$('#progress-count');
const LIMITS=Object.freeze({free:{daily:10,max:10,tier:0},starter:{daily:25,max:50,tier:1},pro:{daily:Infinity,max:500,tier:2},premium:{daily:Infinity,max:500,tier:3}});
const EFFECTS=[
 ['gain','Gain','Basic'],['eq','Tone EQ','Basic'],['lowpass','Low Pass','Basic'],['highpass','High Pass','Basic'],['reverb','Reverb','Basic'],['delay','Delay','Basic'],
 ['compressor','Compression','Starter'],['saturation','Saturation','Starter'],['distortion','Distortion','Starter'],['chorus','Chorus','Starter'],['flanger','Flanger','Starter'],['phaser','Phaser','Starter'],['bitcrusher','Bitcrush','Starter'],['stereo','Stereo Width','Starter'],
 ['transient','Transient Punch','Pro'],['stretch','Time Variation','Pro'],['granular','Texture / Granular','Pro'],['chain','Effect Chain','Premium']
];
const tierRank={Basic:0,Starter:1,Pro:2,Premium:3};
let PLAN='free',serverRemaining=null,sourceFile=null,sourceBuffer=null,outputs=[],audioContext=null,busy=false;
const names={kick:['Deep','Punchy','Dark','Heavy','Sub','Warm','Hard','Tight','Analog','Crushed'],snare:['Crisp','Punchy','Dry','Wide','Sharp','Dark','Bright','Tight','Body','Crack'],clap:['Tight','Wide','Dry','Bright','Dark','Roomy','Sharp','Soft','Layered','Crisp'],hihat:['Crisp','Bright','Dark','Open','Tight','Metallic','Airy','Dry','Shimmer','Short'],percussion:['Organic','Tight','Warm','Dry','Wide','Dark','Bright','Punchy','Roomy','Sharp'],tom:['Deep','Round','Punchy','Warm','Dark','Wide','Tight','Heavy','Short','Resonant'],808:['Deep','Sub','Heavy','Distorted','Warm','Long','Tight','Dark','Punchy','Glide'],bass:['Deep','Warm','Punchy','Round','Dark','Bright','Wide','Tight','Analog','Heavy'],vocal:['Airy','Warm','Dark','Wide','Clean','Dreamy','Deep','Bright','LoFi','Space'],fx:['Dark','Rising','Impact','Glitch','Wide','Deep','Bright','Reverse','Atmospheric','Digital'],piano:['Warm','Soft','Bright','Dark','Wide','Roomy','Tape','Clean','Dreamy','Dry'],synth:['Wide','Bright','Dark','Warm','Analog','Digital','Dreamy','Sharp','Soft','Heavy'],other:['Clean','Dark','Bright','Warm','Wide','Tight','Soft','Hard','Deep','Processed']};
function normalizePlan(value){const raw=String(value||'free').toLowerCase();if(raw.includes('premium'))return'premium';if(raw.includes('pro'))return'pro';if(raw.includes('starter'))return'starter';return'free'}
function planLabel(){return PLAN[0].toUpperCase()+PLAN.slice(1)}
function setUsage(value){serverRemaining=value==null?null:Math.max(0,Number(value)||0);const el=$('#usage-label');if(el)el.textContent=serverRemaining==null?(Number.isFinite(LIMITS[PLAN].daily)?`${LIMITS[PLAN].daily} generations per day`:'Unlimited generations'):`${serverRemaining} generations left today`}
function applyPlan(plan){PLAN=normalizePlan(plan);const l=LIMITS[PLAN];document.documentElement.dataset.sampleMakerPlan=PLAN;const title=$('#plan-label');if(title)title.textContent=`${planLabel()} plan`;if(count){count.max=String(l.max);count.value=String(Math.min(Math.max(1,Number(count.value)||1),l.max));if(countValue)countValue.textContent=count.value;if(countHelp)countHelp.textContent=`${planLabel()}: up to ${l.max} samples per generation`;}const note=$('#control-note');if(note)note.textContent=PLAN==='premium'?'All controls unlocked':PLAN==='pro'?'Advanced controls unlocked':PLAN==='starter'?'Expanded controls available':'Basic controls available';const copy=$('#upgrade-copy');if(copy)copy.textContent=PLAN==='free'?'Starter unlocks expanded effects and up to 50 samples per generation.':'Unlock the next level of sound design and larger packs.';renderEffects();setUsage(serverRemaining)}
window.NEXAUREN_SAMPLE_MAKER_APPLY_PLAN=applyPlan;
window.NEXAUREN_SAMPLE_MAKER_SET_USAGE=setUsage;
function formatTime(sec){sec=Math.max(0,sec||0);return`${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,'0')}`}
function setFile(file){if(!file||!file.type.startsWith('audio/')){alert('Please choose a supported audio file.');return}if(file.size>80*1024*1024){alert('Please choose an audio file smaller than 80 MB.');return}sourceFile=file;fileName.textContent=file.name;fileMeta.textContent=`${(file.type.split('/')[1]||'audio').toUpperCase()} • loading…`;fileCard.hidden=false;drop.hidden=true;generateBtn.disabled=true;const fr=new FileReader();fr.onload=async()=>{try{audioContext||=(new(window.AudioContext||window.webkitAudioContext)());sourceBuffer=await audioContext.decodeAudioData(fr.result.slice(0));if(!sourceBuffer.duration||!Number.isFinite(sourceBuffer.duration)){throw new Error('Invalid audio duration')}fileMeta.textContent=`${(file.type.split('/')[1]||'audio').toUpperCase()} • ${formatTime(sourceBuffer.duration)} • ${sourceBuffer.numberOfChannels} ch`;generateBtn.disabled=false;$('#ready-title').textContent='Ready to make your pack';$('#ready-copy').textContent=`${sourceFile.name} • ${count.value} variations`}catch(e){console.error(e);sourceBuffer=null;generateBtn.disabled=true;alert('This audio could not be decoded by your browser. Try WAV, MP3 or OGG')}};fr.onerror=()=>{sourceBuffer=null;generateBtn.disabled=true;alert('The audio file could not be read. Please try again.')};fr.readAsArrayBuffer(file)}
fileInput.addEventListener('change',e=>setFile(e.target.files[0]));['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('is-drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('is-drag')}));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
$('#remove-file').onclick=()=>{sourceFile=null;sourceBuffer=null;fileInput.value='';fileCard.hidden=true;drop.hidden=false;generateBtn.disabled=true;results.hidden=true;outputs=[];list.replaceChildren()};
count.addEventListener('input',()=>{countValue.textContent=count.value;$('#ready-copy').textContent=sourceFile?`${sourceFile.name} • ${count.value} variations`:'Upload a sample and choose your sound family.'});
function syncControlLabels(){const character=Number($('#character').value),punch=Number($('#punch').value),width=Number($('#width').value),pitch=Number($('#pitch').value);$('#character-value').textContent=character<34?'Dark':character>66?'Bright':'Balanced';$('#punch-value').textContent=`${punch}%` ;$('#width-value').textContent=`${width}%`;$('#pitch-value').textContent=`±${pitch} st`}
['character','punch','width','pitch'].forEach(id=>$('#'+id).addEventListener('input',syncControlLabels));
function hashSeed(n){const x=Math.sin(n*999.91)*43758.5453;return x-Math.floor(x)}
function chooseEffects(){return[...effectsEl.querySelectorAll('input:checked')].map(x=>x.value)}
function renderEffects(){const tier=LIMITS[PLAN].tier;effectsEl.innerHTML=EFFECTS.map(([id,label,required],i)=>{const ok=tier>=tierRank[required];return`<label class="sm-effect ${ok?'':'is-locked'}"><input type="checkbox" value="${id}" ${ok&&i<Math.min(5,EFFECTS.length)?'checked':''} ${ok?'':'disabled'} aria-label="${label}"><span>${label}</span>${ok?'':`<small>${required}</small>`}</label>`}).join('')}
function safeName(i){const type=$('#sample-type').value,chars=names[type]||names.other,a=chars[i%chars.length],b=['Clean','Punch','Texture','Room','Tone','Drive','Space','Edge'][Math.floor(i/chars.length)%8];return`${type==='hihat'?'HiHat':type[0].toUpperCase()+type.slice(1)}_${a}_${b}_${String(i+1).padStart(2,'0')}.wav`}
function makeImpulse(ctx,duration,decay,seed){const len=Math.max(1,Math.floor(ctx.sampleRate*duration)),b=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)*(0.65+seed*.25)}return b}
function waveCurve(amount){const curve=new Float32Array(2048);for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*amount)}return curve}
function addModulatedDelay(ctx,node,seed,type){const delay=ctx.createDelay(.08),mix=ctx.createGain(),lfo=ctx.createOscillator(),depth=ctx.createGain();let base=.012,range=.006,rate=.35+seed*.45;if(type==='flanger'){base=.0025+seed*.006;range=.002+seed*.004;rate=.15+seed*.25}if(type==='phaser'){base=.004+seed*.01;range=.004+seed*.008;rate=.2+seed*.35}delay.delayTime.value=base;depth.gain.value=range;lfo.frequency.value=rate;lfo.connect(depth);depth.connect(delay.delayTime);lfo.start(0);mix.gain.value=.18+seed*.18;node.connect(delay);delay.connect(mix);return{wet:mix,osc:lfo}}
function buildChain(ctx,input,effects,seed){let node=input;const tails=[];const mk=n=>{node.connect(n);node=n};
if(effects.includes('gain')){const g=ctx.createGain();g.gain.value=.78+seed*.48;mk(g)}
if(effects.includes('lowpass')){const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=1700+seed*9000;f.Q.value=.35+seed*1.1;mk(f)}
if(effects.includes('highpass')){const f=ctx.createBiquadFilter();f.type='highpass';f.frequency.value=35+seed*210;f.Q.value=.25+seed*.35;mk(f)}
if(effects.includes('eq')){const f=ctx.createBiquadFilter();f.type='peaking';f.frequency.value=450+seed*5000;f.Q.value=.7+seed*.9;f.gain.value=(seed-.5)*12;mk(f)}
if(effects.includes('compressor')){const c=ctx.createDynamicsCompressor();c.threshold.value=-30+seed*10;c.knee.value=10+seed*20;c.ratio.value=2+seed*7;c.attack.value=.002;c.release.value=.06+seed*.16;mk(c)}
if(effects.includes('saturation')){const w=ctx.createWaveShaper();w.curve=waveCurve(1.1+seed*2.3);w.oversample='4x';mk(w)}
if(effects.includes('distortion')){const w=ctx.createWaveShaper();w.curve=waveCurve(3+seed*12);w.oversample='4x';mk(w)}
if(effects.includes('bitcrusher')){const w=ctx.createWaveShaper(),steps=6+Math.floor(seed*22),curve=new Float32Array(2048);for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.round(x*steps)/steps}w.curve=curve;mk(w)}
if(effects.includes('chorus')||effects.includes('flanger')||effects.includes('phaser')){const type=effects.includes('phaser')?'phaser':effects.includes('flanger')?'flanger':'chorus',m=addModulatedDelay(ctx,node,seed,type),dry=ctx.createGain(),wet=ctx.createGain(),sum=ctx.createGain();dry.gain.value=.78;wet.gain.value=.28+seed*.12;node.connect(dry);m.wet.connect(wet);dry.connect(sum);wet.connect(sum);node=sum;tails.push(m.osc)}
if(effects.includes('delay')){const d=ctx.createDelay(1),fb=ctx.createGain(),wet=ctx.createGain(),sum=ctx.createGain(),dry=ctx.createGain();d.delayTime.value=.09+seed*.28;fb.gain.value=.14+seed*.16;wet.gain.value=.16+seed*.14;dry.gain.value=.82;node.connect(d);d.connect(fb);fb.connect(d);d.connect(wet);node.connect(dry);dry.connect(sum);wet.connect(sum);node=sum}
if(effects.includes('reverb')){const con=ctx.createConvolver(),wet=ctx.createGain(),dry=ctx.createGain(),sum=ctx.createGain();con.buffer=makeImpulse(ctx,.45+seed*.8,1.5+seed*2.2,seed);wet.gain.value=.18+seed*.16;dry.gain.value=.86;node.connect(dry);node.connect(con);con.connect(wet);dry.connect(sum);wet.connect(sum);node=sum}
if(effects.includes('transient')){const c=ctx.createDynamicsCompressor();c.threshold.value=-18-seed*12;c.ratio.value=1.2+seed*2.5;c.attack.value=.0005;c.release.value=.035;c.knee.value=4;mk(c)}
if(effects.includes('stretch')){const d=ctx.createDelay(.12),lfo=ctx.createOscillator(),depth=ctx.createGain(),wet=ctx.createGain(),sum=ctx.createGain(),dry=ctx.createGain();d.delayTime.value=.025+seed*.02;depth.gain.value=.012+seed*.012;lfo.frequency.value=.08+seed*.12;lfo.connect(depth);depth.connect(d.delayTime);lfo.start(0);wet.gain.value=.22;dry.gain.value=.84;node.connect(d);d.connect(wet);node.connect(dry);dry.connect(sum);wet.connect(sum);node=sum;tails.push(lfo)}
if(effects.includes('granular')){const d=ctx.createDelay(.18),lfo=ctx.createOscillator(),depth=ctx.createGain(),wet=ctx.createGain(),sum=ctx.createGain(),dry=ctx.createGain();d.delayTime.value=.018+seed*.025;depth.gain.value=.014+seed*.02;lfo.frequency.value=4+seed*8;lfo.connect(depth);depth.connect(d.delayTime);lfo.start(0);wet.gain.value=.25+seed*.12;dry.gain.value=.78;node.connect(d);d.connect(wet);node.connect(dry);dry.connect(sum);wet.connect(sum);node=sum;tails.push(lfo)}
if(effects.includes('chain')){const w=ctx.createWaveShaper(),comp=ctx.createDynamicsCompressor(),con=ctx.createConvolver(),wet=ctx.createGain(),sum=ctx.createGain();w.curve=waveCurve(1.8+seed*3);w.oversample='4x';comp.threshold.value=-26;comp.ratio.value=4;comp.attack.value=.003;comp.release.value=.11;con.buffer=makeImpulse(ctx,.65+seed*.7,1.8,seed);wet.gain.value=.14+seed*.12;node.connect(w);w.connect(comp);comp.connect(con);con.connect(wet);node.connect(sum);wet.connect(sum);node=sum}
return{node,tails}}
async function renderOne(i){const seed=hashSeed(i+1),sr=sourceBuffer.sampleRate,pitchRange=Number($('#pitch').value)||0,semitone=(seed-.5)*2*pitchRange,rate=Math.pow(2,semitone/12),duration=Math.max(.08,sourceBuffer.duration/rate),tail=1.25,ctx=new OfflineAudioContext(2,Math.ceil((duration+tail)*sr),sr),src=ctx.createBufferSource(),input=ctx.createGain();src.buffer=sourceBuffer;src.playbackRate.value=rate;input.gain.value=.82+seed*.28;src.connect(input);const character=(Number($('#character').value)-50)/50,characterFilter=ctx.createBiquadFilter();characterFilter.type='highshelf';characterFilter.frequency.value=2600;characterFilter.gain.value=character*9;input.connect(characterFilter);const selected=chooseEffects(),built=buildChain(ctx,characterFilter,selected,seed),width=Number($('#width').value)/100,stereo=ctx.createStereoPanner();stereo.pan.value=(seed-.5)*2*width;built.node.connect(stereo);const punch=Number($('#punch').value)/100,comp=ctx.createDynamicsCompressor();comp.threshold.value=-20-punch*14;comp.ratio.value=1.3+punch*5;comp.attack.value=.0015;comp.release.value=.06;stereo.connect(comp);
if(selected.includes('stereo')){const splitter=ctx.createChannelSplitter(2),merger=ctx.createChannelMerger(2),delayL=ctx.createDelay(.03),delayR=ctx.createDelay(.03);delayL.delayTime.value=.004+seed*.006;delayR.delayTime.value=.008+seed*.008;comp.disconnect();comp.connect(splitter);splitter.connect(merger,0,0);splitter.connect(merger,1,1);splitter.connect(delayL,0);splitter.connect(delayR,1);delayL.connect(merger,0,1);delayR.connect(merger,0,0);merger.connect(ctx.destination)}else comp.connect(ctx.destination);
src.start(0);const rendered=await ctx.startRendering();built.tails.forEach(x=>{try{x.stop()}catch{}});return{buffer:rendered,name:safeName(i),effects:selected,seed}}
function wavBlob(buffer){const channels=Math.min(2,buffer.numberOfChannels),sr=buffer.sampleRate,len=buffer.length,bytes=44+len*channels*2,ab=new ArrayBuffer(bytes),v=new DataView(ab);let p=0;const ws=s=>{for(let i=0;i<s.length;i++)v.setUint8(p++,s.charCodeAt(i))},w32=n=>{v.setUint32(p,n,true);p+=4},w16=n=>{v.setUint16(p,n,true);p+=2};ws('RIFF');w32(bytes-8);ws('WAVE');ws('fmt ');w32(16);w16(1);w16(channels);w32(sr);w32(sr*channels*2);w16(channels*2);w16(16);ws('data');w32(len*channels*2);for(let i=0;i<len;i++)for(let c=0;c<channels;c++){const x=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(p,x<0?x*0x8000:x*0x7fff,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
function safeDownload(blob,name){if(!blob||!name)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.rel='noopener';a.style.display='none';document.body.appendChild(a);requestAnimationFrame(()=>{a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},1500)})}
function playSample(item,button){if(!item?.blob)return;if(item.audio){if(item.audio.paused)item.audio.play().catch(()=>{});else item.audio.pause();return}item.audioUrl=URL.createObjectURL(item.blob);item.audio=new Audio(item.audioUrl);item.audio.preload='metadata';item.audio.onplay=()=>button.textContent='Ⅱ';item.audio.onpause=()=>button.textContent='▶';item.audio.onended=()=>button.textContent='▶';item.audio.play().catch(()=>{})}
function renderResults(){list.innerHTML=outputs.map((o,i)=>`<article class="sm-sample"><div class="sm-sample-info"><button class="sm-play" data-play="${i}" type="button" aria-label="Preview ${o.name}">▶</button><div><div class="sm-sample-name">${o.name}</div><div class="sm-sample-meta">${o.effects.length?o.effects.map(e=>EFFECTS.find(x=>x[0]===e)?.[1]||e).join(' • '):'Clean variation'}</div></div></div><div class="sm-sample-actions"><button class="sm-mini" data-download="${i}" type="button">Download WAV</button></div></article>`).join('');list.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playSample(outputs[Number(b.dataset.play)],b));list.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>safeDownload(outputs[Number(b.dataset.download)].blob,outputs[Number(b.dataset.download)].name))}
$('#select-effects').onclick=()=>effectsEl.querySelectorAll('input:not(:disabled)').forEach(x=>x.checked=true);
async function generate(){if(busy||!sourceBuffer)return;const n=Math.min(Math.max(1,Number(count.value)||1),LIMITS[PLAN].max),effects=chooseEffects();busy=true;outputs=[];results.hidden=true;progress.hidden=false;generateBtn.disabled=true;if(!effects.length){busy=false;generateBtn.disabled=false;progress.hidden=true;alert('Select at least one available effect, or use Clean variation.');return}try{for(let i=0;i<n;i++){progressLabel.textContent=`Creating variation ${i+1}…`;progressCount.textContent=`${i+1} / ${n}`;progressFill.style.width=`${((i+1)/n)*100}%`;const o=await renderOne(i);o.blob=wavBlob(o.buffer);delete o.buffer;outputs.push(o);renderResults()}results.hidden=!outputs.length;$('#results-summary').textContent=`${outputs.length} production-ready variations generated from ${sourceFile.name}.`;progressLabel.textContent='Pack complete';progressFill.style.width='100%';$('#ready-title').textContent='Pack ready';$('#ready-copy').textContent='Preview individual sounds or export the complete pack.'}catch(e){console.error('Sample Maker render failed',e);alert('Sample rendering stopped unexpectedly. Any completed samples remain available.')}finally{busy=false;generateBtn.disabled=false}}
window.NEXAUREN_SAMPLE_MAKER_RUN=generate;
$('#generate').onclick=generate;
function crc32(data){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1))}return(c^0xffffffff)>>>0}
function dosDateTime(date=new Date()){const time=(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2),year=Math.max(1980,date.getFullYear());return{time,date:(date.getDate()&31)|((date.getMonth()+1)<<5)|((year-1980)<<9)}}
async function makeZip(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;const dt=dosDateTime();for(const file of files){const data=file.data instanceof Uint8Array?file.data:new Uint8Array(await file.data.arrayBuffer()),name=enc.encode(file.name),h=new Uint8Array(30+name.length),d=new DataView(h.buffer),crc=crc32(data);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x0800,true);d.setUint16(8,0,true);d.setUint16(10,0,true);d.setUint16(12,dt.time,true);d.setUint16(14,dt.date,true);d.setUint32(18,data.length,true);d.setUint32(22,data.length,true);d.setUint16(26,name.length,true);h.set(name,30);local.push(h,data);const c=new Uint8Array(46+name.length),cd=new DataView(c.buffer);cd.setUint32(0,0x02014b50,true);cd.setUint16(4,20,true);cd.setUint16(6,20,true);cd.setUint16(8,0x0800,true);cd.setUint16(10,0,true);cd.setUint16(12,0,true);cd.setUint16(14,dt.time,true);cd.setUint16(16,dt.date,true);cd.setUint32(20,data.length,true);cd.setUint32(24,data.length,true);cd.setUint16(28,name.length,true);cd.setUint32(38,0x81b40000,true);cd.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=h.length+data.length}const centralSize=central.reduce((n,x)=>n+x.length,0),localSize=local.reduce((n,x)=>n+x.length,0),end=new Uint8Array(22),ed=new DataView(end.buffer);ed.setUint32(0,0x06054b50,true);ed.setUint16(8,files.length,true);ed.setUint16(10,files.length,true);ed.setUint32(12,centralSize,true);ed.setUint32(16,localSize,true);return new Blob([...local,...central,end],{type:'application/zip'})}
async function downloadZip(){if(!outputs.length)return;const folder='Nexauren-Sample-Pack',readme=`NEXAUREN SAMPLE MAKER\n\nThis pack was created with Nexauren Sample Maker — a browser-based sound design studio built to turn one source into a production-ready family of original variations.\n\nWHAT IS INSIDE\n• ${outputs.length} WAV sample${outputs.length===1?'':'s'} generated from: ${sourceFile?.name||'source sample'}\n• Consistent, descriptive filenames for fast workflow organization\n• The exact effect palette used for each variation is recorded in the manifest\n\nSOUND DESIGN\nEvery variation is rendered locally with deterministic variation seeds and the selected Sample Maker processing chain. Plan-gated effects are applied only when your account is authorized for them.\n\nWORKFLOW\nDrop the WAV files directly into your DAW, sampler, drum rack, timeline or sound library. The files are standard PCM WAV audio.\n\nCREATED WITH NEXAUREN\nReturn to Sample Maker: https://nexaurenstory.com/tools/sample-maker/\nNexauren: https://nexaurenstory.com/\n\nGenerated: ${new Date().toISOString()}\n`,manifest=JSON.stringify({product:'Nexauren Sample Maker',version:2,source:sourceFile?.name||null,samples:outputs.map(o=>({file:o.name,effects:o.effects})),created_at:new Date().toISOString(),studio_url:'https://nexaurenstory.com/tools/sample-maker/'},null,2),files=[{name:`${folder}/README.md`,data:new TextEncoder().encode(readme)},{name:`${folder}/manifest.json`,data:new TextEncoder().encode(manifest)},...outputs.map(o=>({name:`${folder}/samples/${o.name}`,data:o.blob}))];try{safeDownload(await makeZip(files),`${folder}.zip`)}catch(e){console.error('Sample Maker ZIP export failed',e);alert('The ZIP could not be created. Individual WAV downloads are still available.')}}
$('#download-all').onclick=downloadZip;
window.addEventListener('pagehide',()=>outputs.forEach(o=>{if(o.audioUrl)URL.revokeObjectURL(o.audioUrl)}));
renderEffects();applyPlan('free');syncControlLabels();
})();