(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let file=null,sourceUrl='',audioBuffer=null,notes=[],midiBlob=null,midiUrl='';
const tool={id:'audio-to-midi',name:'Audio to MIDI',url:'/tools/audio/audio-to-midi/'};
const screens=$$('.screen'),dots=$$('[data-dot]');
const bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
const fmt=s=>Number.isFinite(s)?`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`:'—';
const noteName=n=>{const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return names[((n%12)+12)%12]+(Math.floor(n/12)-1)};
function step(n){screens.forEach((x,i)=>{x.hidden=i!==n;x.classList.toggle('active',i===n)});dots.forEach((x,i)=>x.classList.toggle('active',i<=n));scrollTo({top:0,behavior:'smooth'})}
function error(t){const e=$('#error');e.textContent=t;e.hidden=!t}
async function choose(f){error('');if(!f||!f.type.startsWith('audio/'))return error('Please choose a valid audio file.');if(f.size>30*1024*1024)return error('Please choose an audio file smaller than 30 MB.');file=f;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(f);$('#selected').hidden=false;$('#selected').textContent=`✓ ${f.name} • ${bytes(f.size)}`;$('#to-analyze').disabled=false;$('#name').textContent=f.name;$('#info').textContent=bytes(f.size);$('#player').src=sourceUrl;window.Nexauren?.trackTool?.('tool_start',tool,{title:'Audio selected'});step(1)}
$('#browse').onclick=e=>{e.stopPropagation();$('#file').click()};$('#file').onchange=e=>{choose(e.target.files[0]);e.target.value=''};$('#drop').onclick=e=>{if(!e.target.closest('button'))$('#file').click()};$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('drag')};$('#drop').ondragleave=()=>$('#drop').classList.remove('drag');$('#drop').ondrop=e=>{e.preventDefault();$('#drop').classList.remove('drag');choose(e.dataTransfer.files[0])};
$('#to-analyze').onclick=()=>step(1);$('#back-select').onclick=()=>step(0);$('#back-analyze').onclick=()=>step(1);$('#back-preview').onclick=()=>step(2);
$('#sensitivity').oninput=e=>$('#sensitivityValue').textContent=e.target.value+'%';
function freqToMidi(f){return Math.round(69+12*Math.log2(f/440))}
function detectPitch(data,sr,minHz,maxHz,threshold){let rms=0;for(let i=0;i<data.length;i++)rms+=data[i]*data[i];rms=Math.sqrt(rms/data.length);if(rms<threshold)return null;const minLag=Math.max(2,Math.floor(sr/maxHz)),maxLag=Math.min(data.length-2,Math.floor(sr/minHz));let bestLag=-1,best=-1;for(let lag=minLag;lag<=maxLag;lag++){let sum=0,energy=0;for(let i=0;i<data.length-lag;i++){sum+=data[i]*data[i+lag];energy+=data[i]*data[i]+data[i+lag]*data[i+lag]}const c=energy?2*sum/energy:0;if(c>best){best=c;bestLag=lag}}if(bestLag<0||best<0.45)return null;const f=sr/bestLag;if(f<minHz||f>maxHz)return null;return{midi:freqToMidi(f),confidence:best,rms}}
function analyze(){if(!file)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return error('This browser does not support audio analysis.');$('#analysisStatus').textContent='Loading audio…';$('#analyze').disabled=true;const ctx=new C(),reader=new FileReader();reader.onload=async()=>{try{audioBuffer=await ctx.decodeAudioData(reader.result.slice(0));if(audioBuffer.duration>120)throw new Error('Please use audio shorter than 2 minutes.');const len=audioBuffer.length,ch=audioBuffer.numberOfChannels,mono=new Float32Array(len);for(let c=0;c<ch;c++){const d=audioBuffer.getChannelData(c);for(let i=0;i<len;i++)mono[i]+=d[i]/ch}notes=detectNotes(mono,audioBuffer.sampleRate);if(!notes.length)throw new Error('No clear melody was detected. Try a cleaner recording or adjust sensitivity.');renderNotes();$('#analysisStatus').textContent=`Detected ${notes.length} notes`;window.Nexauren?.trackTool?.('tool_process',tool,{title:'Notes detected',count:notes.length});step(2)}catch(e){error(e.message||'Audio analysis failed.');$('#analysisStatus').textContent='Analysis failed'}finally{$('#analyze').disabled=false;ctx.close().catch(()=>{})}};reader.onerror=()=>{$('#analyze').disabled=false;$('#analysisStatus').textContent='Analysis failed';error('Could not read this audio file.')};reader.readAsArrayBuffer(file)}
function detectNotes(data,sr){const frame=2048,hop=512,sensitivity=+$('#sensitivity').value/100,minMidi=+$('#minNote').value,maxMidi=+$('#maxNote').value,minHz=440*Math.pow(2,(minMidi-69)/12),maxHz=440*Math.pow(2,(maxMidi-69)/12),threshold=Math.max(.008,.06*(1-sensitivity*.55));const raw=[];for(let pos=0;pos+frame<=data.length;pos+=hop){const p=detectPitch(data.subarray(pos,pos+frame),sr,minHz,maxHz,threshold);raw.push({t:pos/sr,p:p?.midi??null,c:p?.confidence??0})}const out=[];for(let i=0;i<raw.length;){if(raw[i].p==null){i++;continue}const midi=raw[i].p,start=raw[i].t;let j=i+1,confidence=raw[i].c;while(j<raw.length&&raw[j].p===midi&&raw[j].t-start<=.18){confidence=Math.max(confidence,raw[j].c);j++}const end=j<raw.length?raw[j].t:data.length/sr;if(end-start>=.12)out.push({midi,start,duration:end-start,confidence});i=j}const merged=[];for(const n of out){const last=merged[merged.length-1];if(last&&last.midi===n.midi&&n.start-(last.start+last.duration)<.08)last.duration=n.start+n.duration-last.start;else merged.push({...n})}return merged}
function renderNotes(){const grid=$('#note-grid');grid.innerHTML='';notes.slice(0,120).forEach(n=>{const el=document.createElement('span');el.className='note-pill';el.textContent=noteName(n.midi);el.title=`${fmt(n.start)} • ${n.duration.toFixed(2)}s`;grid.appendChild(el)});$('#note-count').textContent=notes.length;$('#duration').textContent=fmt(audioBuffer?.duration);const lo=Math.min(...notes.map(n=>n.midi)),hi=Math.max(...notes.map(n=>n.midi));$('#note-range').textContent=`${noteName(lo)} – ${noteName(hi)}`;$('#result-name').textContent=`${file.name} • ${notes.length} detected notes`}
function writeBE32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function writeVLQ(value){let v=Math.max(0,Math.floor(value)),buffer=v&0x7f,out=[buffer];while((v>>>=7)!==0){buffer=(v&0x7f)|0x80;out.unshift(buffer)}return out}
function makeMidi(){if(!notes.length)return;try{const ppq=480,bpm=120,ticksPerSecond=ppq*bpm/60,events=[];events.push({tick:0,order:0,data:[0xff,0x51,0x03,0x07,0xa1,0x20]});notes.forEach(n=>{const start=Math.max(0,Math.round(n.start*ticksPerSecond)),end=Math.max(start+1,Math.round((n.start+n.duration)*ticksPerSecond)),velocity=Math.min(127,Math.max(1,Math.round(n.confidence*100)));events.push({tick:start,order:2,data:[0x90,n.midi,velocity]});events.push({tick:end,order:1,data:[0x80,n.midi,0]})});events.sort((a,b)=>a.tick-b.tick||a.order-b.order);const track=[];let lastTick=0;for(const e of events){track.push(...writeVLQ(e.tick-lastTick),...e.data);lastTick=e.tick}track.push(0x00,0xff,0x2f,0x00);const header=[0x4d,0x54,0x68,0x64,...writeBE32(6),0x00,0x01,0x00,0x01,(ppq>>8)&255,ppq&255];const trackHeader=[0x4d,0x54,0x72,0x6b,...writeBE32(track.length)];const bytes=new Uint8Array([...header,...trackHeader,...track]);midiBlob=new Blob([bytes],{type:'audio/midi'});if(midiUrl)URL.revokeObjectURL(midiUrl);midiUrl=URL.createObjectURL(midiBlob);const base=file.name.replace(/\.[^.]+$/,'')||'audio';$('#download-name').textContent=`${base}-midi.mid`;window.Nexauren?.trackTool?.('tool_process',tool,{title:'Valid MIDI created',count:notes.length});step(3)}catch(e){error('Could not create the MIDI file. Please analyze the audio again.')}}
$('#analyze').onclick=analyze;$('#to-download').onclick=makeMidi;const modal=$('#modal');$('#download').onclick=()=>{if(midiBlob)modal.hidden=false};$('#close').onclick=()=>modal.hidden=true;$('#modal').onclick=e=>{if(e.target.classList.contains('modal-bg'))modal.hidden=true};$('#confirm').onclick=()=>{if(!midiBlob)return;const a=document.createElement('a');a.href=midiUrl;a.download=$('#download-name').textContent;document.body.appendChild(a);a.click();a.remove();modal.hidden=true;window.Nexauren?.trackTool?.('tool_download',tool,{title:'MIDI downloaded'})};window.Nexauren?.trackTool?.('tool_open',tool);
})();
