(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let file=null,sourceUrl='',audioBuffer=null,notes=[],midiBlob=null,midiUrl='';
const tool={id:'audio-to-midi',name:'Audio to MIDI',url:'/tools/audio/audio-to-midi/'};
const screens=$$('.screen'),dots=$$('[data-dot]');
const bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
const fmt=s=>Number.isFinite(s)?`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`:'—';
const noteName=n=>{const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return names[n%12]+(Math.floor(n/12)-1)};
function step(n){screens.forEach((x,i)=>{x.hidden=i!==n;x.classList.toggle('active',i===n)});dots.forEach((x,i)=>x.classList.toggle('active',i<=n));scrollTo({top:0,behavior:'smooth'})}
function error(t){const e=$('#error');e.textContent=t;e.hidden=!t}
function choose(f){error('');if(!f||!f.type.startsWith('audio/'))return error('Please choose a valid audio file.');if(f.size>30*1024*1024)return error('Please choose an audio file smaller than 30 MB.');file=f;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(f);$('#selected').hidden=false;$('#selected').textContent=`✓ ${f.name} • ${bytes(f.size)}`;$('#to-analyze').disabled=false;$('#name').textContent=f.name;$('#info').textContent=bytes(f.size);$('#player').src=sourceUrl;window.Nexauren?.trackTool?.('tool_start',tool,{title:'Audio selected'});step(1)}
$('#browse').onclick=e=>{e.stopPropagation();$('#file').click()};$('#file').onchange=e=>{choose(e.target.files[0]);e.target.value=''};$('#drop').onclick=e=>{if(!e.target.closest('button'))$('#file').click()};$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('drag')};$('#drop').ondragleave=()=>$('#drop').classList.remove('drag');$('#drop').ondrop=e=>{e.preventDefault();$('#drop').classList.remove('drag');choose(e.dataTransfer.files[0])};
$('#to-analyze').onclick=()=>step(1);$('#back-select').onclick=()=>step(0);$('#back-analyze').onclick=()=>step(1);$('#back-preview').onclick=()=>step(2);
$('#sensitivity').oninput=e=>$('#sensitivityValue').textContent=e.target.value+'%';
function freqToMidi(f){return Math.round(69+12*Math.log2(f/440))}
function detectPitch(data,sr,minHz,maxHz,threshold){let rms=0;for(let i=0;i<data.length;i++)rms+=data[i]*data[i];rms=Math.sqrt(rms/data.length);if(rms<threshold)return null;let minLag=Math.max(2,Math.floor(sr/maxHz)),maxLag=Math.min(data.length-2,Math.floor(sr/minHz));let bestLag=-1,best=-1;for(let lag=minLag;lag<=maxLag;lag++){let sum=0,energy=0;for(let i=0;i<data.length-lag;i++){sum+=data[i]*data[i+lag];energy+=data[i]*data[i]+data[i+lag]*data[i+lag]}const c=energy?2*sum/energy:0;if(c>best){best=c;bestLag=lag}}if(bestLag<0||best<0.45)return null;let f=sr/bestLag;if(f<minHz||f>maxHz)return null;return{midi:freqToMidi(f),confidence:best,rms}}
function analyze(){if(!file)return;const C=window.AudioContext||window.webkitAudioContext;if(!C){return error('This browser does not support audio analysis.')};$('#analysisStatus').textContent='Loading audio…';$('#analyze').disabled=true;const ctx=new C();const reader=new FileReader();reader.onload=async()=>{try{audioBuffer=await ctx.decodeAudioData(reader.result);if(audioBuffer.duration>120)throw new Error('Please use audio shorter than 2 minutes.');const ch=audioBuffer.numberOfChannels,len=audioBuffer.length;const mono=new Float32Array(len);for(let c=0;c<ch;c++){const d=audioBuffer.getChannelData(c);for(let i=0;i<len;i++)mono[i]+=d[i]/ch}notes=detectNotes(mono,audioBuffer.sampleRate);if(!notes.length)throw new Error('No clear melody was detected. Try a cleaner recording or adjust sensitivity.');renderNotes();$('#analysisStatus').textContent=`Detected ${notes.length} notes`;window.Nexauren?.trackTool?.('tool_process',tool,{title:'Notes detected',count:notes.length});step(2)}catch(e){error(e.message||'Audio analysis failed.');$('#analysisStatus').textContent='Analysis failed'}finally{$('#analyze').disabled=false;ctx.close().catch(()=>{})}};reader.onerror=()=>{$('#analyze').disabled=false;$('#analysisStatus').textContent='Analysis failed';error('Could not read this audio file.')};reader.readAsArrayBuffer(file)}
function detectNotes(data,sr){const frame=2048,hop=512,sensitivity=+$('#sensitivity').value/100;const minMidi=+$('#minNote').value,maxMidi=+$('#maxNote').value;const minHz=440*Math.pow(2,(minMidi-69)/12),maxHz=440*Math.pow(2,(maxMidi-69)/12);let raw=[],threshold=Math.max(.008,.06*(1-sensitivity*.55));for(let pos=0;pos+frame<=data.length;pos+=hop){const x=data.slice(pos,pos+frame);const p=detectPitch(x,sr,minHz,maxHz,threshold);raw.push({t:pos/sr,p:p?.midi??null,c:p?.confidence??0})}let out=[];for(let i=0;i<raw.length;){if(raw[i].p==null){i++;continue}let midi=raw[i].p,start=raw[i].t,j=i+1,confidence=raw[i].c;while(j<raw.length&&raw[j].p===midi&&raw[j].t-(start)<=.18){confidence=Math.max(confidence,raw[j].c);j++}let end=j<raw.length?raw[j].t:data.length/sr;if(end-start>=.12)out.push({midi,start,duration:end-start,confidence});i=j}let merged=[];for(const n of out){const last=merged[merged.length-1];if(last&&last.midi===n.midi&&n.start-last.start-last.duration<.08)last.duration=n.start+ n.duration-last.start;else merged.push({...n})}return merged}
function renderNotes(){const grid=$('#note-grid');grid.innerHTML='';notes.slice(0,120).forEach(n=>{const el=document.createElement('span');el.className='note-pill';el.textContent=noteName(n.midi);el.title=`${fmt(n.start)} • ${n.duration.toFixed(2)}s`;grid.appendChild(el)});$('#note-count').textContent=notes.length;const duration=audioBuffer?audioBuffer.duration:notes.at(-1).start+notes.at(-1).duration;$('#duration').textContent=fmt(duration);const lo=Math.min(...notes.map(n=>n.midi)),hi=Math.max(...notes.map(n=>n.midi));$('#note-range').textContent=`${noteName(lo)} – ${noteName(hi)}`;$('#result-name').textContent=`${file.name} • ${notes.length} detected notes`}
function vlq(v){let buffer=v&127,out=[];while(v>>=7){buffer<<=8;buffer|=(v&127)|128}while(true){out.push(buffer&255);if(buffer&128)buffer>>=8;else break}return out}
function bytesToString(a){return new Uint8Array(a)}
function makeMidi(){if(!notes.length)return;const ppq=480,bpm=120,tps=ppq*bpm/60;let events=[];events.push({t:0,data:[0xff,0x51,0x03,0x07,0xa1,0x20]});for(const n of notes){const start=Math.max(0,Math.round(n.start*tps));const end=Math.max(start+1,Math.round((n.start+n.duration)*tps));events.push({t:start,data:[0x90,n.midi,Math.min(110,Math.max(45,Math.round(n.confidence*110)))]});events.push({t:end,data:[0x80,n.midi,0]})}events.sort((a,b)=>a.t-b.t||(a.data[0]===0x80?1:-1));let track=[];let last=0;for(const e of events){track.push(...vlq(Math.max(0,e.t-last)),...e.data);last=e.t}track.push(0,0xff,0x2f,0);const h=[...new TextEncoder().encode('MThd'),0,0,0,6,0,0,0,1,1,0xe0,0,0];const th=[...new TextEncoder().encode('MTrk'),(track.length>>>24)&255,(track.length>>>16)&255,(track.length>>>8)&255,track.length&255];midiBlob=new Blob([bytesToString([...h,...th,...track])],{type:'audio/midi'});if(midiUrl)URL.revokeObjectURL(midiUrl);midiUrl=URL.createObjectURL(midiBlob);const base=file.name.replace(/\.[^.]+$/,'')||'audio';$('#download-name').textContent=`${base}-midi.mid`;window.Nexauren?.trackTool?.('tool_process',tool,{title:'MIDI created',count:notes.length});step(3)}
$('#analyze').onclick=analyze;$('#to-download').onclick=makeMidi;const modal=$('#modal');$('#download').onclick=()=>{if(midiBlob)modal.hidden=false};$('#close').onclick=()=>modal.hidden=true;$('#modal').onclick=e=>{if(e.target.classList.contains('modal-bg'))modal.hidden=true};$('#confirm').onclick=()=>{if(!midiBlob)return;const a=document.createElement('a');a.href=midiUrl;a.download=$('#download-name').textContent;document.body.appendChild(a);a.click();a.remove();modal.hidden=true;window.Nexauren?.trackTool?.('tool_download',tool,{title:'MIDI downloaded'})};window.Nexauren?.trackTool?.('tool_open',tool);
})();
