import { pipeline } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1';

(()=>{'use strict';
const $=s=>document.querySelector(s),input=$('#input'),output=$('#output'),from=$('#from'),to=$('#to'),status=$('#status'),btn=$('#translate');
const LANG={Portuguese:'por_Latn',English:'eng_Latn',Spanish:'spa_Latn',French:'fra_Latn',German:'deu_Latn',Italian:'ita_Latn',Dutch:'nld_Latn',Russian:'rus_Cyrl',Ukrainian:'ukr_Cyrl',Arabic:'arb_Arab',Hindi:'hin_Deva',Bengali:'ben_Beng',Chinese:'zho_Hans',Japanese:'jpn_Jpan',Korean:'kor_Hang',Turkish:'tur_Latn',Polish:'pol_Latn',Swedish:'swe_Latn',Greek:'ell_Grek',Indonesian:'ind_Latn'};
let translator=null,loading=null;
input.addEventListener('input',()=>$('#count').textContent=`${input.value.length} / 5000`);
$('#clear').onclick=()=>{input.value='';output.value='';$('#count').textContent='0 / 5000';status.textContent='Ready'};
$('#swap').onclick=()=>{if(from.value==='auto')return;const a=from.value;from.value=to.value;to.value=a;const t=input.value;input.value=output.value;output.value=t;input.dispatchEvent(new Event('input'))};
$('#copy').onclick=async()=>{if(!output.value)return;if(navigator.clipboard)await navigator.clipboard.writeText(output.value);else{output.select();document.execCommand('copy')}status.textContent='Copied'};
$('#download').onclick=()=>{if(!output.value)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([output.value],{type:'text/plain;charset=utf-8'}));a.download='nexauren-translation.txt';a.click();URL.revokeObjectURL(a.href);if(window.NexaurenLevels)window.NexaurenLevels.award(15,'tool_download','ai-translate-download')};
$('#file').onchange=async e=>{const f=e.target.files[0];if(f){input.value=(await f.text()).slice(0,5000);input.dispatchEvent(new Event('input'))}};
function speak(text){if(!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}
$('#speakInput').onclick=()=>speak(input.value);$('#speakOutput').onclick=()=>speak(output.value);
async function getTranslator(){if(translator)return translator;if(loading)return loading;status.textContent='Loading AI model… first load may take a while';loading=pipeline('translation','Xenova/nllb-200-distilled-600M',{dtype:'q8'}).then(p=>translator=p).finally(()=>loading=null);return loading}
$('#translate').onclick=async()=>{const text=input.value.trim();if(!text)return;btn.classList.add('working');btn.textContent='Loading AI…';status.textContent='Preparing browser AI';try{if(from.value==='auto'){status.textContent='Select the source language for local AI translation.';return}if(from.value===to.value){output.value=text;status.textContent='Same language'}else{const pipe=await getTranslator();btn.textContent='Translating…';const result=await pipe(text,{src_lang:LANG[from.value],tgt_lang:LANG[to.value],max_new_tokens:256});output.value=result[0]?.translation_text||'';status.textContent='Translated locally with AI';if(window.NexaurenLevels)window.NexaurenLevels.award(10,'tool_process','ai-translate-process')}}catch(err){console.error(err);status.textContent='AI model failed to load. Check your connection and try again.';output.value=''}finally{btn.classList.remove('working');btn.textContent='✨ Translate'}};
getTranslator().then(()=>{btn.disabled=false;btn.textContent='✨ Translate';status.textContent='AI model ready'}).catch(()=>{status.textContent='AI model could not be loaded. Click Translate to retry.';btn.disabled=false;btn.textContent='✨ Translate'});
})();