(()=>{'use strict';
const $=s=>document.querySelector(s);
const AC=()=>window.AudioContext||window.webkitAudioContext;
let proUrl='',originalUrl='',liveCtx=null,liveStream=null,liveRaf=0,liveAnalyser=null;
const setStatus=t=>{const e=$('#status');if(e)e.textContent=t};
const out=(id,v)=>{const e=$('#'+id+'Out');if(e)e.textContent=v+'%'};
['noiseReduction','smartGate','echoRepeats','mix'].forEach(id=>$('#'+id)?.addEventListener('input',e=>out(id,e.target.value)));
function currentBlob(){const p=$('#sourcePlayer');if(!p?.src)throw Error('Load or record a vocal first.');return fetch(p.src).then(r=>r.blob())}
async function decodeCurrent(){const b=await currentBlob(),C=AC();if(!C)throw Error('Web Audio is not supported in this browser.');const c=new C();try{if(c.state==='suspended')await c.resume();return await c.decodeAudioData(await b.arrayBuffer())}finally{c.close().catch(()=>{})}}
function wav(b){const ch=b.numberOfChannels,n=b.length,rate=b.sampleRate,ds=n*ch*2,ab=new ArrayBuffer(44+ds),v=new DataView(ab),s=(o,x)=>{for(let i=0;i<x.length;i++)v.setUint8(o+i,x.charCodeAt(i))};s(0,'RIFF');v.setUint32(4,36+ds,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2*ch,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,ds,true);let p=44;for(let i=0;i<n;i++)for(let c=0;c<ch;c++){const x=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([ab],{type:'audio/wav'})}
function publish(b,label){const blob=wav(b);if(proUrl)URL.revokeObjectURL(proUrl);proUrl=URL.createObjectURL(blob);if(!originalUrl){const p=$('#sourcePlayer');originalUrl=p?.src||''}const r=$('#resultPlayer');r.src=proUrl;r.hidden=false;$('#result').hidden=false;$('#resultInfo').textContent=`${b.duration.toFixed(2)}s • ${Math.round(blob.size/1024)} KB • ${label}`;setStatus('Ready • processed locally in your browser');return blob}
function mono(b){const out=new Float32Array(b.length);for(let c=0;c<b.numberOfChannels;c++){const d=b.getChannelData(c);for(let i=0;i<d.length;i++)out[i]+=d[i]/b.numberOfChannels}return out}
function pitchAt(d,rate,start,size){let rms=0;for(let i=0;i<size&&start+i<d.length;i++){const x=d[start+i];rms+=x*x}rms=Math.sqrt(rms/Math.min(size,d.length-start));if(rms<.012)return 0;let best=-Infinity,bestLag=0,min=Math.max(2,Math.floor(rate/1000)),max=Math.min(size-2,Math.floor(rate/70));for(let lag=min;lag<=max;lag++){let s=0;for(let i=0;i<size-lag&&start+i<d.length;i++)s+=d[start+i]*d[start+i+lag];if(s>best){best=s;bestLag=lag}}return bestLag?rate/bestLag:0}
function targetPitch(hz,scale,key){if(!hz||scale==='off')return hz;const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],ki=Math.max(0,names.indexOf(key)),allowed=scale==='major'?[0,2,4,5,7,9,11]:scale==='minor'?[0,2,3,5,7,8,10]:names.map((_,i)=>i),m=69+12*Math.log2(hz/440),base=Math.round(m),c=[];for(let x=base-12;x<=base+12;x++)if(allowed.includes((x-ki+120)%12))c.push(x);const n=c.sort((a,b)=>Math.abs(a-m)-Math.abs(b-m))[0];return n==null?hz:440*Math.pow(2,(n-69)/12)}
function renderPitch(input,rate,pitchSemis,scale,key,strength){const C=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!C)return null;const d=mono(input),grain=.075,hop=.0375,frames=Math.ceil(input.duration/hop)+2,ctx=new C(input.numberOfChannels,Math.ceil((frames*hop+grain+1)*rate),rate),out=ctx.createGain();out.connect(ctx.destination);let pos=0,t=0;for(let k=0;k<frames&&pos<input.duration;k++){const start=Math.floor(pos*rate),hz=pitchAt(d,rate,start,Math.min(Math.floor(grain*rate),d.length-start));let ratio=Math.pow(2,pitchSemis/12);if(hz&&scale!=='off'){const target=targetPitch(hz,scale,key);ratio*=Math.pow(target/hz,strength)}ratio=Math.max(.5,Math.min(2,ratio));const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=input;src.playbackRate.value=ratio;const dur=Math.min(grain,input.duration-pos);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.58,t+Math.min(.018,dur/2));g.gain.setValueAtTime(.58,t+Math.max(.018,dur-.018));g.gain.linearRampToValueAtTime(0,t+dur);src.connect(g).connect(out);src.start(t,pos,Math.min(dur*ratio,input.duration-pos));pos+=hop*ratio;t+=hop}return ctx.startRendering()}
function chain(ctx,src,settings){let n=src;const hp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=65;hp.Q.value=.7;n.connect(hp);n=hp;const eq=+settings.eq||0;if(Math.abs(eq)>2){const f=ctx.createBiquadFilter();f.type=eq>0?'highshelf':'lowshelf';f.frequency.value=eq>0?3200:480;f.gain.value=Math.max(-18,Math.min(18,eq*.16));n.connect(f);n=f}const tone=+settings.tone||50;if(tone!==50){const f=ctx.createBiquadFilter();f.type=tone>50?'peaking':'lowpass';f.frequency.value=tone>50?4200:9000;f.Q.value=.75;f.gain.value=Math.max(-10,Math.min(10,(tone-50)*.28));n.connect(f);n=f}const air=(+settings.air||0)/100;if(air){const f=ctx.createBiquadFilter();f.type='highshelf';f.frequency.value=7500;f.gain.value=air*12;n.connect(f);n=f}const comp=(+settings.comp||0)/100;if(comp){const c=ctx.createDynamicsCompressor();c.threshold.value=-10-comp*32;c.knee.value=18;c.ratio.value=2+comp*10;c.attack.value=.003;c.release.value=.12;n.connect(c);n=c}const drive=(+settings.drive||0)/100+(+settings.dist||0)/150;if(drive>.005){const w=ctx.createWaveShaper(),curve=new Float32Array(4096),a=1+drive*18;for(let i=0;i<curve.length;i++){const x=i*2/curve.length-1;curve[i]=Math.tanh(x*a)/Math.tanh(a)}w.curve=curve;w.oversample='4x';n.connect(w);n=w}const bit=(+settings.bit||0)/100;if(bit>.005){const w=ctx.createWaveShaper(),curve=new Float32Array(4096),steps=Math.max(2,Math.round(64-bit*60));for(let i=0;i<curve.length;i++){const x=i*2/curve.length-1;curve[i]=Math.round(x*steps)/steps}w.curve=curve;w.oversample='2x';n.connect(w);n=w}return n}
function impulse(ctx,seconds=.9,decay=2.2){const b=ctx.createBuffer(2,Math.ceil(ctx.sampleRate*seconds),ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,decay)}return b}
function renderMain(input){const C=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!C)throw Error('Offline audio processing is not supported.');const s={};['pitch','speed','reverb','delay','drive','eq','comp','tone','width','dist','bit','phaser','chorus','flanger','gate','air','scale','key'].forEach(id=>s[id]=$('#'+id)?.value);const speed=Math.max(.5,Math.min(1.5,(+s.speed||100)/100)),pitch=+s.pitch||0;return Promise.resolve(renderPitch(input,input.sampleRate,pitch,s.scale,s.key,1)).then(pitched=>{const outDur=Math.max(.05,pitched.duration/speed),ctx=new C(pitched.numberOfChannels,Math.ceil(outDur*pitched.sampleRate),pitched.sampleRate),src=ctx.createBufferSource();src.buffer=pitched;src.playbackRate.value=speed;const master=ctx.createGain();master.gain.value=.95;let n=chain(ctx,src,s);n.connect(master);const rv=(+s.reverb||0)/100;if(rv){const conv=ctx.createConvolver(),g=ctx.createGain();conv.buffer=impulse(ctx,.8+rv*1.4,2.4);g.gain.value=rv*.55;n.connect(conv).connect(g).connect(master)}const del=(+s.delay||0)/100;if(del){const d=ctx.createDelay(2),fb=ctx.createGain(),g=ctx.createGain();d.delayTime.value=.08+del*.34;fb.gain.value=Math.min(.65,del*.48);g.gain.value=del*.35;n.connect(d);d.connect(fb).connect(d);d.connect(g).connect(master)}const width=(+s.width||0)/100;if(width&&pitched.numberOfChannels>1){const sp=ctx.createChannelSplitter(2),mg=ctx.createChannelMerger(2),l=ctx.createGain(),r=ctx.createGain();n.disconnect();n.connect(sp);sp.connect(l,0);sp.connect(r,1);l.gain.value=1+width*.25;r.gain.value=1+width*.25;l.connect(mg,0,0);r.connect(mg,0,1);mg.connect(master)}for(const [id,freq,baseDepth,wetAmt] of [['chorus',.8,.025,.45],['flanger',.35,.006,.35],['phaser',.22,.018,.3]]){const a=(+s[id]||0)/100;if(a){const d=ctx.createDelay(.2),osc=ctx.createOscillator(),depth=ctx.createGain(),g=ctx.createGain();d.delayTime.value=baseDepth;osc.frequency.value=freq;depth.gain.value=a*(id==='chorus'?.012:id==='flanger'?.004:.01);osc.connect(depth).connect(d.delayTime);g.gain.value=a*wetAmt;n.connect(d).connect(g).connect(master);osc.start()}}const gate=(+s.gate||0)/100;if(gate){const g=ctx.createDynamicsCompressor();g.threshold.value=-45+gate*25;g.knee.value=8;g.ratio.value=1+gate*18;g.attack.value=.002;g.release.value=.08;n.connect(g).connect(master)}master.connect(ctx.destination);src.start();return ctx.startRendering()})}
async function process(){const btn=$('#process');if(btn)btn.disabled=true;try{setStatus('Rendering vocal • browser processing…');const input=await decodeCurrent(),b=await renderMain(input);publish(b,'mastered • pitch, effects and dynamics')}catch(e){console.error(e);setStatus(e.message||'Could not process vocal.')}finally{if(btn){btn.disabled=false;btn.textContent='Process vocal →'}}}
function applyGateInPlace(b,strength){if(strength<=0)return;const threshold=.004+strength*.02;for(let c=0;c<b.numberOfChannels;c++){const d=b.getChannelData(c);let env=1;for(let i=0;i<d.length;i++){const a=Math.abs(d[i]);if(a>threshold)env=Math.min(1,env+.025);else env=Math.max(.02,env-.004);d[i]*=env}}}
async function clean(){try{setStatus('Cleaning vocal…');const b=await decodeCurrent(),C=window.OfflineAudioContext||window.webkitOfflineAudioContext,ctx=new C(b.numberOfChannels,b.length,b.sampleRate),src=ctx.createBufferSource(),hp=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor(),mix=+($('#mix')?.value||100)/100,nr=+($('#noiseReduction')?.value||45)/100;src.buffer=b;hp.type='highpass';hp.frequency.value=70+nr*100;lp.type='lowpass';lp.frequency.value=18000-nr*4500;comp.threshold.value=-24;comp.knee.value=18;comp.ratio.value=2.5+nr*5;comp.attack.value=.004;comp.release.value=.14;const wet=ctx.createGain(),dry=ctx.createGain();wet.gain.value=mix;dry.gain.value=1-mix;src.connect(hp).connect(lp).connect(comp).connect(wet).connect(ctx.destination);src.connect(dry).connect(ctx.destination);src.start();const outb=await ctx.startRendering();applyGateInPlace(outb,(+($('#smartGate')?.value||30))/100);publish(outb,'cleaned • high/low filtering + smart gate')}catch(e){console.error(e);setStatus(e.message||'Could not clean vocal.')}}
async function echo(){try{setStatus('Building echo repeats…');const b=await decodeCurrent(),C=window.OfflineAudioContext||window.webkitOfflineAudioContext,a=(+($('#echoRepeats')?.value||25))/100,mix=(+($('#mix')?.value||100))/100,count=Math.max(1,Math.round(1+a*3)),tail=1.1+a*1.5,ctx=new C(b.numberOfChannels,b.length+Math.ceil(b.sampleRate*tail),b.sampleRate),src=ctx.createBufferSource(),master=ctx.createGain();src.buffer=b;src.connect(master).connect(ctx.destination);for(let i=1;i<=count;i++){const d=ctx.createDelay(3),g=ctx.createGain();d.delayTime.value=.16+i*(.11+a*.15);g.gain.value=Math.pow(.55,i)*Math.max(.08,a*.55)*mix;src.connect(d).connect(g).connect(master)}src.start();publish(await ctx.startRendering(),`echo / repeat • ${count} repeats`)}catch(e){console.error(e);setStatus(e.message||'Could not apply echo.')}}
async function autotune(){try{setStatus('Applying Smart Auto-Tune…');const b=await decodeCurrent(),scale=$('#scale')?.value||'chromatic',key=$('#key')?.value||'C';if(scale==='off'){setStatus('Choose Chromatic, Major or Minor for pitch correction.');return}const outb=await renderPitch(b,b.sampleRate,0,scale,key,.78);publish(outb,'Smart Auto-Tune • time-varying pitch correction')}catch(e){console.error(e);setStatus(e.message||'Could not tune this vocal.')}}
function setAB(){const r=$('#resultPlayer');if(!r)return;if(r.dataset.ab==='original'){r.src=proUrl;r.dataset.ab='processed';$('#abPro').textContent='A/B Original'}else{if(!originalUrl)return;r.src=originalUrl;r.dataset.ab='original';$('#abPro').textContent='A/B Processed'}}
function settings(){const ids=['pitch','speed','reverb','delay','drive','eq','comp','tone','width','dist','bit','phaser','chorus','flanger','gate','air','scale','key','noiseReduction','smartGate','echoRepeats','mix'];const s={};ids.forEach(id=>{const e=$('#'+id);if(e)s[id]=e.value});return s}
function applySettings(s){Object.entries(s||{}).forEach(([id,v])=>{const e=$('#'+id);if(e&&v!==undefined)e.value=v});Object.keys(s||{}).forEach(id=>$('#'+id)?.dispatchEvent(new Event('input',{bubbles:true})))}
function saveSession(){const blob=new Blob([JSON.stringify({version:2,tool:'nexauren-vocal-studio',savedAt:new Date().toISOString(),settings:settings()},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='nexauren-vocal-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setStatus('Session saved')}
$('#process')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();process()},true);
$('#cleanBtn')?.addEventListener('click',clean);$('#echoBtn')?.addEventListener('click',echo);$('#tuneBtn')?.addEventListener('click',autotune);$('#abPro')?.addEventListener('click',setAB);$('#saveSession')?.addEventListener('click',saveSession);
$('#loadSession')?.addEventListener('click',()=>$('#sessionFile')?.click());$('#sessionFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const j=JSON.parse(await f.text());applySettings(j.settings);setStatus('Session loaded')}catch{setStatus('Invalid session file')}});
$('#livePitchBtn')?.addEventListener('click',async()=>{const btn=$('#livePitchBtn');if(liveCtx){liveStream?.getTracks().forEach(t=>t.stop());liveCtx.close().catch(()=>{});liveCtx=null;liveStream=null;cancelAnimationFrame(liveRaf);$('#liveNote').textContent='Live pitch stopped.';btn.textContent='Start live pitch';return}try{liveStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false}});liveCtx=new (AC())();if(liveCtx.state==='suspended')await liveCtx.resume();liveAnalyser=liveCtx.createAnalyser();liveAnalyser.fftSize=2048;liveCtx.createMediaStreamSource(liveStream).connect(liveAnalyser);const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];const tick=()=>{const d=new Float32Array(liveAnalyser.fftSize);liveAnalyser.getFloatTimeDomainData(d);let best=-Infinity,lag=0;for(let l=Math.floor(liveCtx.sampleRate/1000);l<=Math.floor(liveCtx.sampleRate/70);l++){let s=0;for(let i=0;i<d.length-l;i++)s+=d[i]*d[i+l];if(s>best){best=s;lag=l}}if(lag&&best>.02){const hz=liveCtx.sampleRate/lag,m=69+12*Math.log2(hz/440),n=Math.round(m),c=Math.round((m-n)*100);$('#liveNote').textContent=`${names[(n+120)%12]} • ${Math.round(hz)} Hz • ${c>=0?'+':''}${c} cents`}else $('#liveNote').textContent='Listening…';liveRaf=requestAnimationFrame(tick)};btn.textContent='Stop live pitch';tick()}catch(e){console.error(e);setStatus('Microphone access is required for live pitch.')}});
window.addEventListener('beforeunload',()=>{liveStream?.getTracks().forEach(t=>t.stop());if(liveCtx)liveCtx.close().catch(()=>{});if(proUrl)URL.revokeObjectURL(proUrl)});
})();
