(()=>{'use strict';
const $=s=>document.querySelector(s);
const SETTINGS_KEY='nexauren:vocal-studio:settings:v2';
const state={steps:['Input','Shape','Analyze','Master'],current:0};
const setStatus=t=>{const e=$('#status');if(e){e.textContent=t;e.setAttribute('aria-live','polite')}};
function addStyles(){if($('#vocalUxStyles'))return;const s=document.createElement('style');s.id='vocalUxStyles';s.textContent=`
.vocal-workflow{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:0 0 22px}.vocal-step{position:relative;padding:10px 8px;border:1px solid #e9e3f5;border-radius:12px;background:#f8f5fc;text-align:center;font-size:12px;font-weight:900;color:#766d89}.vocal-step.active{background:#eee9ff;color:#7657ff;border-color:#d8ceff}.vocal-step.done{color:#2d6b45}.vocal-step small{display:block;font-size:10px;font-weight:700;margin-top:3px}.vocal-drop{border:1.5px dashed #d8cfee;border-radius:16px;padding:14px;margin-top:12px;text-align:center;color:#766d89;transition:.15s}.vocal-drop.drag{border-color:#7657ff;background:#f5f1ff;color:#7657ff}.vocal-file-info{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-top:10px;font-size:12px;color:#766d89}.vocal-shortcuts{margin-top:12px;color:#766d89;font-size:11px}.vocal-shortcuts kbd{padding:2px 6px;border:1px solid #ddd5ec;border-radius:5px;background:#fff;font-family:inherit}.vocal-warning{padding:11px 13px;border-radius:12px;background:#fff8e8;color:#6b5420;font-size:12px;margin-top:12px}.vocal-error{padding:11px 13px;border-radius:12px;background:#fff0f3;color:#8a2840;font-size:12px;margin-top:12px}.vocal-ready{padding:11px 13px;border-radius:12px;background:#eefaf1;color:#2d6b45;font-size:12px;margin-top:12px}@media(max-width:700px){.vocal-workflow{grid-template-columns:1fr 1fr}.vocal-step{font-size:11px}}
`;document.head.appendChild(s)}
function workflow(){const card=$('.studio-card'),bar=document.createElement('div');bar.className='vocal-workflow';bar.setAttribute('aria-label','Vocal workflow');state.steps.forEach((x,i)=>{const e=document.createElement('div');e.className='vocal-step';e.dataset.step=i;e.innerHTML=`${i+1}. ${x}<small>${['Record or upload','Effects and presets','Pitch and score','Preview and export'][i]}</small>`;bar.appendChild(e)});card?.prepend(bar)}
function setStep(i){state.current=Math.max(0,Math.min(3,i));document.querySelectorAll('.vocal-step').forEach((e,n)=>{e.classList.toggle('active',n===state.current);e.classList.toggle('done',n<state.current)})}
function fileDrop(){const input=$('#file'),actions=$('.input-actions');if(!input||!actions)return;const drop=document.createElement('div');drop.className='vocal-drop';drop.tabIndex=0;drop.setAttribute('role','button');drop.setAttribute('aria-label','Drop an audio file here or choose one');drop.innerHTML='<strong>Drop vocal here</strong><br><span>or use Upload vocal • audio files only</span>';actions.insertAdjacentElement('afterend',drop);const open=()=>input.click();drop.addEventListener('click',open);drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}});['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(!f)return;if(!f.type.startsWith('audio/')){notice('Please choose an audio file.','error');return}const dt=new DataTransfer();dt.items.add(f);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))});input.addEventListener('change',()=>{const f=input.files?.[0];if(f)showFile(f)})}
function showFile(f){let info=$('.vocal-file-info');if(!info){info=document.createElement('div');info.className='vocal-file-info';$('#file')?.closest('.input-actions')?.insertAdjacentElement('afterend',info)}info.innerHTML=`<span><strong>${escapeHtml(f.name)}</strong></span><span>${formatBytes(f.size)} • ${f.type||'audio'}</span>`;setStep(0)}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
function notice(text,type='ready'){let n=$('.vocal-notice');if(!n){n=document.createElement('div');n.className='vocal-notice';$('.studio-card')?.appendChild(n)}n.className=`vocal-notice vocal-${type}`;n.textContent=text}
function autoSave(){const fields=['pitch','speed','reverb','delay','drive','eq','comp','tone','width','dist','bit','phaser','chorus','flanger','gate','air','scale','key','noiseReduction','smartGate','echoRepeats','mix'];const s={};fields.forEach(id=>{const e=$('#'+id);if(e)s[id]=e.value});try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({savedAt:Date.now(),settings:s}))}catch{}}
function restore(){try{const raw=localStorage.getItem(SETTINGS_KEY);if(!raw)return;const data=JSON.parse(raw);if(!data?.settings)return;Object.entries(data.settings).forEach(([id,v])=>{const e=$('#'+id);if(e)e.value=v});document.querySelectorAll('.effect-grid input').forEach(e=>e.dispatchEvent(new Event('input',{bubbles:true})));['noiseReduction','smartGate','echoRepeats','mix'].forEach(id=>$('#'+id)?.dispatchEvent(new Event('input',{bubbles:true})));notice('Your last local settings were restored.','ready')}catch{}}
function wire(){const watched=['pitch','speed','reverb','delay','drive','eq','comp','tone','width','dist','bit','phaser','chorus','flanger','gate','air','scale','key','noiseReduction','smartGate','echoRepeats','mix'];watched.forEach(id=>$('#'+id)?.addEventListener('input',autoSave));$('#process')?.addEventListener('click',()=>{setStep(1);notice('Processing locally in your browser. Keep this tab open until it finishes.','ready')},{capture:true});['cleanBtn','echoBtn','tuneBtn'].forEach(id=>$('#'+id)?.addEventListener('click',()=>{setStep(1);notice('Enhancement is being rendered locally.','ready')},{capture:true}));$('#analyzeBtn')?.addEventListener('click',()=>setStep(2));$('#download')?.addEventListener('click',()=>{setStep(3);notice('Export started. Your audio stays local.','ready')});$('#resetAll')?.addEventListener('click',()=>{autoSave();setStep(0)});document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,button'))return;if(e.key==='Escape'){$('#resetAll')?.click();notice('Effects reset.','ready')}if(e.key.toLowerCase()==='u'){$('#uploadBtn')?.click()}})}
function access(){const ids=['record','uploadBtn','process','resetAll','analyzeBtn','download','cleanBtn','echoBtn','tuneBtn','livePitchBtn','saveSession','loadSession'];ids.forEach(id=>{const e=$('#'+id);if(e&&!e.getAttribute('aria-label'))e.setAttribute('aria-label',e.textContent.trim())});const p=$('#process');if(p)p.setAttribute('aria-describedby','vocalPrivacyNote');const note=document.querySelector('.reset-row small');if(note)note.id='vocalPrivacyNote';const audio=document.querySelectorAll('audio');audio.forEach(a=>a.setAttribute('aria-label',a.id==='sourcePlayer'?'Original vocal preview':'Processed vocal preview'))}
function init(){addStyles();workflow();fileDrop();access();wire();setStep(0);setTimeout(restore,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();