(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ensureMeta=()=>{if(!document.querySelector('link[rel="icon"]')){const l=document.createElement('link');l.rel='icon';l.type='image/png';l.href='/favicon.png?v=2';document.head.appendChild(l)}if(!document.querySelector('link[rel="apple-touch-icon"]')){const l=document.createElement('link');l.rel='apple-touch-icon';l.href='/favicon.png?v=2';document.head.appendChild(l)}};ensureMeta();
const load=(src,attr)=>{if(document.querySelector(`script[${attr}]`))return;const s=document.createElement('script');s.src=src;s.defer=true;s.setAttribute(attr,'true');document.head.appendChild(s)};
load('/js/tool-status.js','data-nexauren-tool-status');load('/js/notifications.js?v=2','data-nexauren-notifications');load('/ai/nexa/nexa-widget.js?v=20260903','data-nexa-widget');if(!document.querySelector('link[data-nexa-widget-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/ai/nexa/nexa-widget.css?v=20260903';l.dataset.nexaWidgetCss='true';document.head.appendChild(l)}
window.Nexauren=window.Nexauren||{};window.Nexauren.trackTool=window.Nexauren.trackTool||(()=>{});window.Nexauren.loadTools=()=>fetch('/data/tools.json',{cache:'default'}).then(r=>r.ok?r.json():Promise.reject(new Error('Tools unavailable'))).then(d=>Array.isArray(d.tools)?d.tools:[]);
const renderHeader=()=>`<header class="site-header"><div class="support-banner"><div class="container support-banner-inner"><span>💙 Gostas da Nexauren? Apoia o projeto.</span><a href="https://www.paypal.com/ncp/payment/WPTH2ZN6ZHBAW" target="_blank" rel="noopener noreferrer">Apoiar a Nexauren →</a></div></div><div class="container header-inner"><a class="brand" href="/"><span class="brand-mark">N</span><span>Nexauren</span></a><button class="menu-toggle" data-menu-toggle aria-expanded="false" aria-controls="main-nav"><span class="sr-only">Menu</span><span class="menu-bars" aria-hidden="true"></span></button><nav class="nav" id="main-nav" data-nav aria-label="Main navigation"><a href="/">Home</a><a href="/tools/">Tools</a><a href="/blog/">Blog</a><a href="/account/" data-account-link>Minha conta</a><a class="nav-auth" href="/auth/" data-auth-link>Entrar / Criar conta</a></nav></div></header>`;
const renderFooter=()=>`<footer class="site-footer"><div class="container footer-main"><div class="footer-brand"><a class="footer-logo" href="/"><span class="brand-mark">N</span><span>Nexauren</span></a><p>Uma plataforma para ferramentas, conteúdo e experiências digitais.</p><a class="footer-support" href="https://www.paypal.com/ncp/payment/WPTH2ZN6ZHBAW" target="_blank" rel="noopener noreferrer">💙 Apoiar a Nexauren</a></div><div class="footer-col"><h3>Explorar</h3><a href="/tools/">Tools</a><a href="/blog/">Blog</a><a href="/account/">Minha conta</a></div><div class="footer-col"><h3>Nexauren</h3><a href="/about.html">Sobre</a><a href="/faq.html">FAQ</a><a href="/contact.html">Contacto</a><a href="/suggestions.html">Sugestões</a></div><div class="footer-col"><h3>Legal</h3><a href="/privacy.html">Privacidade</a><a href="/terms.html">Termos</a><a href="/complaints.html">Reportar um problema</a><a href="https://www.facebook.com/nexauren" target="_blank" rel="noopener noreferrer">Facebook</a><a href="https://youtube.com/@nexauren" target="_blank" rel="noopener noreferrer">YouTube</a></div></div><div class="container footer-bottom"><span>© <span data-year></span> Nexauren</span><span>Construído para ser útil.</span></div></footer>`;
const hp=$('#site-header'),fp=$('#site-footer');if(hp)hp.outerHTML=renderHeader();if(fp)fp.outerHTML=renderFooter();
const updateAuth=async()=>{try{const r=await fetch('/api/account/me',{credentials:'include',cache:'default'});const d=await r.json().catch(()=>({}));if(d?.authenticated){const links=$$('[data-auth-link]');links.forEach(a=>{a.textContent='Sair';a.href='#';a.dataset.logout='true'});$$('[data-account-link]').forEach(a=>a.textContent='Minha conta')}}catch{}};updateAuth();
document.addEventListener('click',async e=>{const logout=e.target.closest?.('[data-logout]');if(logout){e.preventDefault();try{await fetch('/api/account/logout',{method:'POST',credentials:'include'})}finally{location.reload()}}});
const menu=$('[data-menu-toggle]'),nav=$('[data-nav]');if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});$$('.nav a',nav).forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
$$('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());const current=location.pathname.replace(/\/$/,'')||'/';$$('.nav a').forEach(a=>{const t=new URL(a.href,location.href).pathname.replace(/\/$/,'')||'/';a.classList.toggle('active',t===current)});
const i18n=document.createElement('script');i18n.src='/js/i18n.js';i18n.defer=true;document.head.appendChild(i18n);
})();